CREATE TABLE m_challenge_cell(
  id INTEGER NOT NULL,
  set_m_id INTEGER NOT NULL,
  title TEXT,
  description TEXT,
  summary TEXT,
  scene_transition_link INTEGER,
  scene_transition_param TEXT,
  display_order INTEGER NOT NULL,
  mission_clear_condition_type INTEGER NOT NULL,
  mission_clear_condition_count INTEGER,
  mission_clear_condition_param1 INTEGER,
  mission_clear_condition_param2 INTEGER,
  start_count INTEGER NOT NULL,
  PRIMARY KEY (id)
);
INSERT INTO `m_challenge_cell` VALUES (/*id*/500101, /*set_m_id*/5001, /*title*/"m.mission_name_18", /*description*/"k.beginnermission_desc_500101_01", /*summary*/"k.beginnermission_summary_500002", /*scene_transition_link*/20, /*scene_transition_param*/20, /*display_order*/1, /*mission_clear_condition_type*/13, /*mission_clear_condition_count*/1, /*mission_clear_condition_param1*/"", /*mission_clear_condition_param2*/"", /*start_count*/1);
INSERT INTO `m_challenge_cell` VALUES (/*id*/500102, /*set_m_id*/5001, /*title*/"m.mission_name_7", /*description*/"k.beginnermission_desc_500102", /*summary*/"k.beginnermission_summary_500006", /*scene_transition_link*/14, /*scene_transition_param*/14, /*display_order*/2, /*mission_clear_condition_type*/58, /*mission_clear_condition_count*/1, /*mission_clear_condition_param1*/"", /*mission_clear_condition_param2*/"", /*start_count*/1);
INSERT INTO `m_challenge_cell` VALUES (/*id*/500103, /*set_m_id*/5001, /*title*/"m.mission_name_9", /*description*/"k.beginnermission_desc_500103_01", /*summary*/"k.beginnermission_summary_500007", /*scene_transition_link*/4, /*scene_transition_param*/32, /*display_order*/3, /*mission_clear_condition_type*/63, /*mission_clear_condition_count*/1, /*mission_clear_condition_param1*/"", /*mission_clear_condition_param2*/"", /*start_count*/1);
INSERT INTO `m_challenge_cell` VALUES (/*id*/500104, /*set_m_id*/5001, /*title*/"m.mission_name_7", /*description*/"k.beginnermission_desc_500104", /*summary*/"k.beginnermission_summary_500006", /*scene_transition_link*/14, /*scene_transition_param*/14, /*display_order*/4, /*mission_clear_condition_type*/58, /*mission_clear_condition_count*/3, /*mission_clear_condition_param1*/"", /*mission_clear_condition_param2*/"", /*start_count*/1);
INSERT INTO `m_challenge_cell` VALUES (/*id*/500105, /*set_m_id*/5001, /*title*/"m.mission_name_3", /*description*/"k.beginnermission_desc_500105_01", /*summary*/"k.beginnermission_summary_500005", /*scene_transition_link*/75, /*scene_transition_param*/"", /*display_order*/5, /*mission_clear_condition_type*/101, /*mission_clear_condition_count*/1, /*mission_clear_condition_param1*/"", /*mission_clear_condition_param2*/"", /*start_count*/1);
INSERT INTO `m_challenge_cell` VALUES (/*id*/500201, /*set_m_id*/5002, /*title*/"m.mission_name_18", /*description*/"k.beginnermission_desc_500201_01", /*summary*/"k.beginnermission_summary_500002", /*scene_transition_link*/20, /*scene_transition_param*/20, /*display_order*/1, /*mission_clear_condition_type*/13, /*mission_clear_condition_count*/3, /*mission_clear_condition_param1*/"", /*mission_clear_condition_param2*/"", /*start_count*/1);
INSERT INTO `m_challenge_cell` VALUES (/*id*/500202, /*set_m_id*/5002, /*title*/"m.mission_name_11", /*description*/"k.beginnermission_desc_500202", /*summary*/"k.beginnermission_summary_500001", /*scene_transition_link*/1, /*scene_transition_param*/"", /*display_order*/2, /*mission_clear_condition_type*/85, /*mission_clear_condition_count*/13, /*mission_clear_condition_param1*/"", /*mission_clear_condition_param2*/"", /*start_count*/1);
INSERT INTO `m_challenge_cell` VALUES (/*id*/500203, /*set_m_id*/5002, /*title*/"m.mission_name_9", /*description*/"k.beginnermission_desc_500203_01", /*summary*/"k.beginnermission_summary_500007", /*scene_transition_link*/4, /*scene_transition_param*/32, /*display_order*/3, /*mission_clear_condition_type*/63, /*mission_clear_condition_count*/2, /*mission_clear_condition_param1*/"", /*mission_clear_condition_param2*/"", /*start_count*/1);
INSERT INTO `m_challenge_cell` VALUES (/*id*/500204, /*set_m_id*/5002, /*title*/"m.mission_name_9", /*description*/"k.beginnermission_desc_500204", /*summary*/"k.beginnermission_summary_500012", /*scene_transition_link*/4, /*scene_transition_param*/32, /*display_order*/4, /*mission_clear_condition_type*/72, /*mission_clear_condition_count*/20, /*mission_clear_condition_param1*/"", /*mission_clear_condition_param2*/"", /*start_count*/1);
INSERT INTO `m_challenge_cell` VALUES (/*id*/500205, /*set_m_id*/5002, /*title*/"m.mission_name_3", /*description*/"k.beginnermission_desc_500205_01", /*summary*/"k.beginnermission_summary_500005", /*scene_transition_link*/75, /*scene_transition_param*/"", /*display_order*/5, /*mission_clear_condition_type*/101, /*mission_clear_condition_count*/2, /*mission_clear_condition_param1*/"", /*mission_clear_condition_param2*/"", /*start_count*/1);
INSERT INTO `m_challenge_cell` VALUES (/*id*/500301, /*set_m_id*/5003, /*title*/"m.mission_name_7", /*description*/"k.beginnermission_desc_500301", /*summary*/"k.beginnermission_summary_500006", /*scene_transition_link*/14, /*scene_transition_param*/14, /*display_order*/1, /*mission_clear_condition_type*/58, /*mission_clear_condition_count*/6, /*mission_clear_condition_param1*/"", /*mission_clear_condition_param2*/"", /*start_count*/1);
INSERT INTO `m_challenge_cell` VALUES (/*id*/500302, /*set_m_id*/5003, /*title*/"m.mission_name_9", /*description*/"k.beginnermission_desc_500302", /*summary*/"k.beginnermission_summary_500008", /*scene_transition_link*/4, /*scene_transition_param*/32, /*display_order*/2, /*mission_clear_condition_type*/72, /*mission_clear_condition_count*/1, /*mission_clear_condition_param1*/9, /*mission_clear_condition_param2*/"", /*start_count*/1);
INSERT INTO `m_challenge_cell` VALUES (/*id*/500303, /*set_m_id*/5003, /*title*/"m.mission_name_9", /*description*/"k.beginnermission_desc_500303_01", /*summary*/"k.beginnermission_summary_500007", /*scene_transition_link*/4, /*scene_transition_param*/32, /*display_order*/3, /*mission_clear_condition_type*/63, /*mission_clear_condition_count*/3, /*mission_clear_condition_param1*/"", /*mission_clear_condition_param2*/"", /*start_count*/1);
INSERT INTO `m_challenge_cell` VALUES (/*id*/500304, /*set_m_id*/5003, /*title*/"m.mission_name_9", /*description*/"k.beginnermission_desc_500304", /*summary*/"k.beginnermission_summary_500010", /*scene_transition_link*/4, /*scene_transition_param*/32, /*display_order*/4, /*mission_clear_condition_type*/64, /*mission_clear_condition_count*/1, /*mission_clear_condition_param1*/"", /*mission_clear_condition_param2*/"", /*start_count*/1);
INSERT INTO `m_challenge_cell` VALUES (/*id*/500305, /*set_m_id*/5003, /*title*/"m.mission_name_3", /*description*/"k.beginnermission_desc_500305_01", /*summary*/"k.beginnermission_summary_500005", /*scene_transition_link*/75, /*scene_transition_param*/"", /*display_order*/5, /*mission_clear_condition_type*/101, /*mission_clear_condition_count*/3, /*mission_clear_condition_param1*/"", /*mission_clear_condition_param2*/"", /*start_count*/1);
INSERT INTO `m_challenge_cell` VALUES (/*id*/500401, /*set_m_id*/5004, /*title*/"m.mission_name_18", /*description*/"k.beginnermission_desc_500401_01", /*summary*/"k.beginnermission_summary_500011", /*scene_transition_link*/20, /*scene_transition_param*/20, /*display_order*/1, /*mission_clear_condition_type*/14, /*mission_clear_condition_count*/3, /*mission_clear_condition_param1*/"", /*mission_clear_condition_param2*/"", /*start_count*/1);
INSERT INTO `m_challenge_cell` VALUES (/*id*/500402, /*set_m_id*/5004, /*title*/"m.mission_name_18", /*description*/"k.beginnermission_desc_500402", /*summary*/"k.beginnermission_summary_500011", /*scene_transition_link*/20, /*scene_transition_param*/20, /*display_order*/2, /*mission_clear_condition_type*/87, /*mission_clear_condition_count*/3, /*mission_clear_condition_param1*/"", /*mission_clear_condition_param2*/"", /*start_count*/1);
INSERT INTO `m_challenge_cell` VALUES (/*id*/500403, /*set_m_id*/5004, /*title*/"m.mission_name_9", /*description*/"k.beginnermission_desc_500403", /*summary*/"k.beginnermission_summary_500009", /*scene_transition_link*/4, /*scene_transition_param*/32, /*display_order*/3, /*mission_clear_condition_type*/72, /*mission_clear_condition_count*/1, /*mission_clear_condition_param1*/7, /*mission_clear_condition_param2*/"", /*start_count*/1);
INSERT INTO `m_challenge_cell` VALUES (/*id*/500404, /*set_m_id*/5004, /*title*/"m.mission_name_9", /*description*/"k.beginnermission_desc_500404", /*summary*/"k.beginnermission_summary_500010", /*scene_transition_link*/4, /*scene_transition_param*/32, /*display_order*/4, /*mission_clear_condition_type*/64, /*mission_clear_condition_count*/2, /*mission_clear_condition_param1*/"", /*mission_clear_condition_param2*/"", /*start_count*/1);
INSERT INTO `m_challenge_cell` VALUES (/*id*/500405, /*set_m_id*/5004, /*title*/"m.mission_name_3", /*description*/"k.beginnermission_desc_500405_01", /*summary*/"k.beginnermission_summary_500005", /*scene_transition_link*/75, /*scene_transition_param*/"", /*display_order*/5, /*mission_clear_condition_type*/101, /*mission_clear_condition_count*/4, /*mission_clear_condition_param1*/"", /*mission_clear_condition_param2*/"", /*start_count*/1);
INSERT INTO `m_challenge_cell` VALUES (/*id*/500501, /*set_m_id*/5005, /*title*/"m.mission_name_18", /*description*/"k.beginnermission_desc_500501_01", /*summary*/"k.beginnermission_summary_500011", /*scene_transition_link*/20, /*scene_transition_param*/20, /*display_order*/1, /*mission_clear_condition_type*/14, /*mission_clear_condition_count*/5, /*mission_clear_condition_param1*/"", /*mission_clear_condition_param2*/"", /*start_count*/1);
INSERT INTO `m_challenge_cell` VALUES (/*id*/500502, /*set_m_id*/5005, /*title*/"m.mission_name_18", /*description*/"k.beginnermission_desc_500502", /*summary*/"k.beginnermission_summary_500011", /*scene_transition_link*/20, /*scene_transition_param*/20, /*display_order*/2, /*mission_clear_condition_type*/87, /*mission_clear_condition_count*/5, /*mission_clear_condition_param1*/"", /*mission_clear_condition_param2*/"", /*start_count*/1);
INSERT INTO `m_challenge_cell` VALUES (/*id*/500503, /*set_m_id*/5005, /*title*/"m.mission_name_9", /*description*/"k.beginnermission_desc_500503_01", /*summary*/"k.beginnermission_summary_500007", /*scene_transition_link*/4, /*scene_transition_param*/32, /*display_order*/1, /*mission_clear_condition_type*/63, /*mission_clear_condition_count*/4, /*mission_clear_condition_param1*/"", /*mission_clear_condition_param2*/"", /*start_count*/1);
INSERT INTO `m_challenge_cell` VALUES (/*id*/500504, /*set_m_id*/5005, /*title*/"m.mission_name_9", /*description*/"k.beginnermission_desc_500504", /*summary*/"k.beginnermission_summary_500010", /*scene_transition_link*/4, /*scene_transition_param*/32, /*display_order*/4, /*mission_clear_condition_type*/64, /*mission_clear_condition_count*/3, /*mission_clear_condition_param1*/"", /*mission_clear_condition_param2*/"", /*start_count*/1);
INSERT INTO `m_challenge_cell` VALUES (/*id*/500505, /*set_m_id*/5005, /*title*/"m.mission_name_3", /*description*/"k.beginnermission_desc_500505_01", /*summary*/"k.beginnermission_summary_500005", /*scene_transition_link*/75, /*scene_transition_param*/"", /*display_order*/5, /*mission_clear_condition_type*/101, /*mission_clear_condition_count*/5, /*mission_clear_condition_param1*/"", /*mission_clear_condition_param2*/"", /*start_count*/1);
INSERT INTO `m_challenge_cell` VALUES (/*id*/500601, /*set_m_id*/5006, /*title*/"k.mission_name_21", /*description*/"m.beginnermission_desc_500601", /*summary*/"k.beginnermission_summary_500013", /*scene_transition_link*/25, /*scene_transition_param*/"", /*display_order*/1, /*mission_clear_condition_type*/94, /*mission_clear_condition_count*/1, /*mission_clear_condition_param1*/"", /*mission_clear_condition_param2*/"", /*start_count*/1);
INSERT INTO `m_challenge_cell` VALUES (/*id*/500602, /*set_m_id*/5006, /*title*/"k.mission_name_21", /*description*/"m.beginnermission_desc_500602", /*summary*/"k.beginnermission_summary_500013", /*scene_transition_link*/25, /*scene_transition_param*/"", /*display_order*/2, /*mission_clear_condition_type*/94, /*mission_clear_condition_count*/5, /*mission_clear_condition_param1*/"", /*mission_clear_condition_param2*/"", /*start_count*/1);
INSERT INTO `m_challenge_cell` VALUES (/*id*/500603, /*set_m_id*/5006, /*title*/"k.mission_name_21", /*description*/"m.beginnermission_desc_500603", /*summary*/"k.beginnermission_summary_500013", /*scene_transition_link*/25, /*scene_transition_param*/"", /*display_order*/3, /*mission_clear_condition_type*/94, /*mission_clear_condition_count*/10, /*mission_clear_condition_param1*/"", /*mission_clear_condition_param2*/"", /*start_count*/1);
INSERT INTO `m_challenge_cell` VALUES (/*id*/500604, /*set_m_id*/5006, /*title*/"k.mission_name_22", /*description*/"m.beginnermission_desc_500604", /*summary*/"m.beginnermission_summary_500014", /*scene_transition_link*/25, /*scene_transition_param*/"", /*display_order*/4, /*mission_clear_condition_type*/9, /*mission_clear_condition_count*/1, /*mission_clear_condition_param1*/"", /*mission_clear_condition_param2*/"", /*start_count*/1);
INSERT INTO `m_challenge_cell` VALUES (/*id*/500605, /*set_m_id*/5006, /*title*/"k.mission_name_23", /*description*/"m.beginnermission_desc_500605", /*summary*/"m.beginnermission_summary_500015", /*scene_transition_link*/25, /*scene_transition_param*/"", /*display_order*/5, /*mission_clear_condition_type*/100, /*mission_clear_condition_count*/1, /*mission_clear_condition_param1*/"", /*mission_clear_condition_param2*/"", /*start_count*/1);
