CREATE TABLE m_coop_stamp(
  id INTEGER NOT NULL,
  stamp_asset_path TEXT NOT NULL,
  PRIMARY KEY (id)
);
INSERT INTO `m_coop_stamp` VALUES (/*id*/1, /*stamp_asset_path*/")fY");
INSERT INTO `m_coop_stamp` VALUES (/*id*/2, /*stamp_asset_path*/"8Dz");
INSERT INTO `m_coop_stamp` VALUES (/*id*/3, /*stamp_asset_path*/"u]C");
INSERT INTO `m_coop_stamp` VALUES (/*id*/4, /*stamp_asset_path*/"FF!");
INSERT INTO `m_coop_stamp` VALUES (/*id*/5, /*stamp_asset_path*/"!\'");
INSERT INTO `m_coop_stamp` VALUES (/*id*/6, /*stamp_asset_path*/"N].");
INSERT INTO `m_coop_stamp` VALUES (/*id*/7, /*stamp_asset_path*/"Us7");
INSERT INTO `m_coop_stamp` VALUES (/*id*/8, /*stamp_asset_path*/"~Rf");
INSERT INTO `m_coop_stamp` VALUES (/*id*/9, /*stamp_asset_path*/"w-S");
INSERT INTO `m_coop_stamp` VALUES (/*id*/10, /*stamp_asset_path*/"8`*");
INSERT INTO `m_coop_stamp` VALUES (/*id*/11, /*stamp_asset_path*/"/\"}");
INSERT INTO `m_coop_stamp` VALUES (/*id*/12, /*stamp_asset_path*/"2L-");
INSERT INTO `m_coop_stamp` VALUES (/*id*/13, /*stamp_asset_path*/"IN$");
INSERT INTO `m_coop_stamp` VALUES (/*id*/14, /*stamp_asset_path*/"0VV");
INSERT INTO `m_coop_stamp` VALUES (/*id*/15, /*stamp_asset_path*/"d7p");
INSERT INTO `m_coop_stamp` VALUES (/*id*/16, /*stamp_asset_path*/"~nt");
INSERT INTO `m_coop_stamp` VALUES (/*id*/17, /*stamp_asset_path*/"#[i");
INSERT INTO `m_coop_stamp` VALUES (/*id*/18, /*stamp_asset_path*/">i/");
INSERT INTO `m_coop_stamp` VALUES (/*id*/19, /*stamp_asset_path*/"2bm");
INSERT INTO `m_coop_stamp` VALUES (/*id*/20, /*stamp_asset_path*/"vdB");
INSERT INTO `m_coop_stamp` VALUES (/*id*/21, /*stamp_asset_path*/"5T0");
INSERT INTO `m_coop_stamp` VALUES (/*id*/22, /*stamp_asset_path*/"0rd");
INSERT INTO `m_coop_stamp` VALUES (/*id*/23, /*stamp_asset_path*/"^.k");
INSERT INTO `m_coop_stamp` VALUES (/*id*/24, /*stamp_asset_path*/"jt\"");
INSERT INTO `m_coop_stamp` VALUES (/*id*/25, /*stamp_asset_path*/"{aH");
INSERT INTO `m_coop_stamp` VALUES (/*id*/26, /*stamp_asset_path*/"h~K");
INSERT INTO `m_coop_stamp` VALUES (/*id*/27, /*stamp_asset_path*/",Yh");
INSERT INTO `m_coop_stamp` VALUES (/*id*/28, /*stamp_asset_path*/"dnN");
INSERT INTO `m_coop_stamp` VALUES (/*id*/29, /*stamp_asset_path*/"=-E");
INSERT INTO `m_coop_stamp` VALUES (/*id*/30, /*stamp_asset_path*/"Z9P");
INSERT INTO `m_coop_stamp` VALUES (/*id*/31, /*stamp_asset_path*/"xNa");
INSERT INTO `m_coop_stamp` VALUES (/*id*/32, /*stamp_asset_path*/"o80");
INSERT INTO `m_coop_stamp` VALUES (/*id*/33, /*stamp_asset_path*/"Bp+");
INSERT INTO `m_coop_stamp` VALUES (/*id*/34, /*stamp_asset_path*/"O=d");
INSERT INTO `m_coop_stamp` VALUES (/*id*/35, /*stamp_asset_path*/"H8y");
INSERT INTO `m_coop_stamp` VALUES (/*id*/36, /*stamp_asset_path*/"=5N");
INSERT INTO `m_coop_stamp` VALUES (/*id*/37, /*stamp_asset_path*/"TIt");
INSERT INTO `m_coop_stamp` VALUES (/*id*/38, /*stamp_asset_path*/"qf?");
INSERT INTO `m_coop_stamp` VALUES (/*id*/39, /*stamp_asset_path*/"VKR");
INSERT INTO `m_coop_stamp` VALUES (/*id*/40, /*stamp_asset_path*/"uA5");
INSERT INTO `m_coop_stamp` VALUES (/*id*/41, /*stamp_asset_path*/"L?B");
INSERT INTO `m_coop_stamp` VALUES (/*id*/42, /*stamp_asset_path*/"?c]");
INSERT INTO `m_coop_stamp` VALUES (/*id*/43, /*stamp_asset_path*/"^75");
INSERT INTO `m_coop_stamp` VALUES (/*id*/44, /*stamp_asset_path*/"gJj");
INSERT INTO `m_coop_stamp` VALUES (/*id*/45, /*stamp_asset_path*/">Z>");
