CREATE TABLE m_event_marathon_booster_item(
  id INTEGER NOT NULL,
  name TEXT NOT NULL,
  description TEXT NOT NULL,
  image_asset_path TEXT NOT NULL,
  thumbnail_asset_path TEXT NOT NULL,
  item_list_category_type INTEGER NOT NULL,
  scene_id INTEGER NOT NULL,
  banner_image_asset_path TEXT,
  multiple INTEGER NOT NULL,
  inline_image TEXT NOT NULL,
  inline_image_small TEXT NOT NULL,
  PRIMARY KEY (id)
);
INSERT INTO `m_event_marathon_booster_item` VALUES (/*id*/15001, /*name*/"k.item_name_15001", /*description*/"k.item_desc_15001", /*image_asset_path*/"8^F", /*thumbnail_asset_path*/"8^F", /*item_list_category_type*/255, /*scene_id*/1, /*banner_image_asset_path*/"", /*multiple*/15000, /*inline_image*/"k.item_inline_image_15001", /*inline_image_small*/"k.item_inline_image_small_15001");
INSERT INTO `m_event_marathon_booster_item` VALUES (/*id*/15002, /*name*/"k.item_name_15002", /*description*/"k.item_desc_15002", /*image_asset_path*/"wra", /*thumbnail_asset_path*/"wra", /*item_list_category_type*/255, /*scene_id*/1, /*banner_image_asset_path*/"", /*multiple*/15000, /*inline_image*/"k.item_inline_image_15002", /*inline_image_small*/"k.item_inline_image_small_15002");
INSERT INTO `m_event_marathon_booster_item` VALUES (/*id*/15003, /*name*/"k.item_name_15003", /*description*/"k.item_desc_15003", /*image_asset_path*/"%Uj", /*thumbnail_asset_path*/"%Uj", /*item_list_category_type*/255, /*scene_id*/1, /*banner_image_asset_path*/"", /*multiple*/15000, /*inline_image*/"k.item_inline_image_15003", /*inline_image_small*/"k.item_inline_image_small_15003");
INSERT INTO `m_event_marathon_booster_item` VALUES (/*id*/15004, /*name*/"k.item_name_15004", /*description*/"k.item_desc_15004", /*image_asset_path*/"F<s", /*thumbnail_asset_path*/"F<s", /*item_list_category_type*/255, /*scene_id*/1, /*banner_image_asset_path*/"", /*multiple*/15000, /*inline_image*/"k.item_inline_image_15004", /*inline_image_small*/"k.item_inline_image_small_15004");
INSERT INTO `m_event_marathon_booster_item` VALUES (/*id*/15005, /*name*/"k.item_name_15005", /*description*/"k.item_desc_15005", /*image_asset_path*/"s2U", /*thumbnail_asset_path*/"s2U", /*item_list_category_type*/255, /*scene_id*/1, /*banner_image_asset_path*/"", /*multiple*/15000, /*inline_image*/"k.item_inline_image_15005", /*inline_image_small*/"k.item_inline_image_small_15005");
INSERT INTO `m_event_marathon_booster_item` VALUES (/*id*/15006, /*name*/"k.item_name_15006", /*description*/"k.item_desc_15006", /*image_asset_path*/"_c8", /*thumbnail_asset_path*/"_c8", /*item_list_category_type*/255, /*scene_id*/1, /*banner_image_asset_path*/"", /*multiple*/15000, /*inline_image*/"k.item_inline_image_15006", /*inline_image_small*/"k.item_inline_image_small_15006");
INSERT INTO `m_event_marathon_booster_item` VALUES (/*id*/15007, /*name*/"k.item_name_15007", /*description*/"k.item_desc_15007", /*image_asset_path*/"ZOb", /*thumbnail_asset_path*/"ZOb", /*item_list_category_type*/255, /*scene_id*/1, /*banner_image_asset_path*/"", /*multiple*/15000, /*inline_image*/"k.item_inline_image_15007", /*inline_image_small*/"k.item_inline_image_small_15007");
INSERT INTO `m_event_marathon_booster_item` VALUES (/*id*/15008, /*name*/"k.item_name_15008", /*description*/"k.item_desc_15008", /*image_asset_path*/"-'D", /*thumbnail_asset_path*/"-'D", /*item_list_category_type*/255, /*scene_id*/1, /*banner_image_asset_path*/"", /*multiple*/15000, /*inline_image*/"k.item_inline_image_15008", /*inline_image_small*/"k.item_inline_image_small_15008");
INSERT INTO `m_event_marathon_booster_item` VALUES (/*id*/15009, /*name*/"k.item_name_15009", /*description*/"k.item_desc_15009", /*image_asset_path*/"K/E", /*thumbnail_asset_path*/"K/E", /*item_list_category_type*/255, /*scene_id*/1, /*banner_image_asset_path*/"", /*multiple*/15000, /*inline_image*/"k.item_inline_image_15009", /*inline_image_small*/"k.item_inline_image_small_15009");
INSERT INTO `m_event_marathon_booster_item` VALUES (/*id*/15010, /*name*/"k.item_name_15010", /*description*/"k.item_desc_15010", /*image_asset_path*/"miX", /*thumbnail_asset_path*/"miX", /*item_list_category_type*/255, /*scene_id*/1, /*banner_image_asset_path*/"", /*multiple*/15000, /*inline_image*/"k.item_inline_image_15010", /*inline_image_small*/"k.item_inline_image_small_15010");
INSERT INTO `m_event_marathon_booster_item` VALUES (/*id*/15011, /*name*/"k.item_name_15011", /*description*/"k.item_desc_15011", /*image_asset_path*/"L6?", /*thumbnail_asset_path*/"L6?", /*item_list_category_type*/255, /*scene_id*/1, /*banner_image_asset_path*/"", /*multiple*/15000, /*inline_image*/"k.item_inline_image_15011", /*inline_image_small*/"k.item_inline_image_small_15011");
INSERT INTO `m_event_marathon_booster_item` VALUES (/*id*/15012, /*name*/"k.item_name_15012", /*description*/"k.item_desc_15012", /*image_asset_path*/"2#c", /*thumbnail_asset_path*/"2#c", /*item_list_category_type*/255, /*scene_id*/1, /*banner_image_asset_path*/"", /*multiple*/15000, /*inline_image*/"k.item_inline_image_15012", /*inline_image_small*/"k.item_inline_image_small_15012");
INSERT INTO `m_event_marathon_booster_item` VALUES (/*id*/15013, /*name*/"k.item_name_15013", /*description*/"k.item_desc_15013", /*image_asset_path*/"o'o", /*thumbnail_asset_path*/"o'o", /*item_list_category_type*/255, /*scene_id*/1, /*banner_image_asset_path*/"", /*multiple*/15000, /*inline_image*/"k.item_inline_image_15013", /*inline_image_small*/"k.item_inline_image_small_15013");
INSERT INTO `m_event_marathon_booster_item` VALUES (/*id*/15014, /*name*/"k.item_name_15014", /*description*/"k.item_desc_15014", /*image_asset_path*/"{[6", /*thumbnail_asset_path*/"{[6", /*item_list_category_type*/255, /*scene_id*/1, /*banner_image_asset_path*/"", /*multiple*/15000, /*inline_image*/"k.item_inline_image_15014", /*inline_image_small*/"k.item_inline_image_small_15014");
INSERT INTO `m_event_marathon_booster_item` VALUES (/*id*/15015, /*name*/"k.item_name_15015", /*description*/"k.item_desc_15015", /*image_asset_path*/"z4R", /*thumbnail_asset_path*/"z4R", /*item_list_category_type*/255, /*scene_id*/1, /*banner_image_asset_path*/"", /*multiple*/15000, /*inline_image*/"k.item_inline_image_15015", /*inline_image_small*/"k.item_inline_image_small_15015");
INSERT INTO `m_event_marathon_booster_item` VALUES (/*id*/15901, /*name*/"k.item_name_15901", /*description*/"k.item_desc_15901", /*image_asset_path*/"%q%", /*thumbnail_asset_path*/"%q%", /*item_list_category_type*/255, /*scene_id*/1, /*banner_image_asset_path*/"", /*multiple*/15000, /*inline_image*/"k.item_inline_image_15901", /*inline_image_small*/"k.item_inline_image_small_15901");
