CREATE TABLE m_event_marathon_booster_item(
  id INTEGER NOT NULL,
  name TEXT NOT NULL,
  description TEXT NOT NULL,
  image_asset_path TEXT NOT NULL,
  thumbnail_asset_path TEXT NOT NULL,
  item_list_category_type INTEGER NOT NULL,
  scene_id INTEGER NOT NULL,
  banner_image_asset_path TEXT,
  multiple INTEGER NOT NULL,
  inline_image TEXT NOT NULL,
  inline_image_small TEXT NOT NULL,
  PRIMARY KEY (id)
);
INSERT INTO `m_event_marathon_booster_item` VALUES (/*id*/15001, /*name*/"k.item_name_15001", /*description*/"k.item_desc_15001", /*image_asset_path*/"8^F", /*thumbnail_asset_path*/"8^F", /*item_list_category_type*/255, /*scene_id*/1, /*banner_image_asset_path*/"", /*multiple*/15000, /*inline_image*/"k.item_inline_image_15001", /*inline_image_small*/"k.item_inline_image_small_15001");
INSERT INTO `m_event_marathon_booster_item` VALUES (/*id*/15002, /*name*/"k.item_name_15002", /*description*/"k.item_desc_15002", /*image_asset_path*/"wra", /*thumbnail_asset_path*/"wra", /*item_list_category_type*/255, /*scene_id*/1, /*banner_image_asset_path*/"", /*multiple*/15000, /*inline_image*/"k.item_inline_image_15002", /*inline_image_small*/"k.item_inline_image_small_15002");
INSERT INTO `m_event_marathon_booster_item` VALUES (/*id*/15003, /*name*/"k.item_name_15003", /*description*/"k.item_desc_15003", /*image_asset_path*/"%Uj", /*thumbnail_asset_path*/"%Uj", /*item_list_category_type*/255, /*scene_id*/1, /*banner_image_asset_path*/"", /*multiple*/15000, /*inline_image*/"k.item_inline_image_15003", /*inline_image_small*/"k.item_inline_image_small_15003");
INSERT INTO `m_event_marathon_booster_item` VALUES (/*id*/15004, /*name*/"k.item_name_15004", /*description*/"k.item_desc_15004", /*image_asset_path*/"F<s", /*thumbnail_asset_path*/"F<s", /*item_list_category_type*/255, /*scene_id*/1, /*banner_image_asset_path*/"", /*multiple*/15000, /*inline_image*/"k.item_inline_image_15004", /*inline_image_small*/"k.item_inline_image_small_15004");
INSERT INTO `m_event_marathon_booster_item` VALUES (/*id*/15005, /*name*/"k.item_name_15005", /*description*/"k.item_desc_15005", /*image_asset_path*/"s2U", /*thumbnail_asset_path*/"s2U", /*item_list_category_type*/255, /*scene_id*/1, /*banner_image_asset_path*/"", /*multiple*/15000, /*inline_image*/"k.item_inline_image_15005", /*inline_image_small*/"k.item_inline_image_small_15005");
INSERT INTO `m_event_marathon_booster_item` VALUES (/*id*/15006, /*name*/"k.item_name_15006", /*description*/"k.item_desc_15006", /*image_asset_path*/"_c8", /*thumbnail_asset_path*/"_c8", /*item_list_category_type*/255, /*scene_id*/1, /*banner_image_asset_path*/"", /*multiple*/15000, /*inline_image*/"k.item_inline_image_15006", /*inline_image_small*/"k.item_inline_image_small_15006");
INSERT INTO `m_event_marathon_booster_item` VALUES (/*id*/15007, /*name*/"k.item_name_15007", /*description*/"k.item_desc_15007", /*image_asset_path*/"ZOb", /*thumbnail_asset_path*/"ZOb", /*item_list_category_type*/255, /*scene_id*/1, /*banner_image_asset_path*/"", /*multiple*/15000, /*inline_image*/"k.item_inline_image_15007", /*inline_image_small*/"k.item_inline_image_small_15007");
INSERT INTO `m_event_marathon_booster_item` VALUES (/*id*/15008, /*name*/"k.item_name_15008", /*description*/"k.item_desc_15008", /*image_asset_path*/"-'D", /*thumbnail_asset_path*/"-'D", /*item_list_category_type*/255, /*scene_id*/1, /*banner_image_asset_path*/"", /*multiple*/15000, /*inline_image*/"k.item_inline_image_15008", /*inline_image_small*/"k.item_inline_image_small_15008");
INSERT INTO `m_event_marathon_booster_item` VALUES (/*id*/15009, /*name*/"k.item_name_15009", /*description*/"k.item_desc_15009", /*image_asset_path*/"K/E", /*thumbnail_asset_path*/"K/E", /*item_list_category_type*/255, /*scene_id*/1, /*banner_image_asset_path*/"", /*multiple*/15000, /*inline_image*/"k.item_inline_image_15009", /*inline_image_small*/"k.item_inline_image_small_15009");
INSERT INTO `m_event_marathon_booster_item` VALUES (/*id*/15010, /*name*/"k.item_name_15010", /*description*/"k.item_desc_15010", /*image_asset_path*/"miX", /*thumbnail_asset_path*/"miX", /*item_list_category_type*/255, /*scene_id*/1, /*banner_image_asset_path*/"", /*multiple*/15000, /*inline_image*/"k.item_inline_image_15010", /*inline_image_small*/"k.item_inline_image_small_15010");
INSERT INTO `m_event_marathon_booster_item` VALUES (/*id*/15011, /*name*/"k.item_name_15011", /*description*/"k.item_desc_15011", /*image_asset_path*/"L6?", /*thumbnail_asset_path*/"L6?", /*item_list_category_type*/255, /*scene_id*/1, /*banner_image_asset_path*/"", /*multiple*/15000, /*inline_image*/"k.item_inline_image_15011", /*inline_image_small*/"k.item_inline_image_small_15011");
INSERT INTO `m_event_marathon_booster_item` VALUES (/*id*/15012, /*name*/"k.item_name_15012", /*description*/"k.item_desc_15012", /*image_asset_path*/"2#c", /*thumbnail_asset_path*/"2#c", /*item_list_category_type*/255, /*scene_id*/1, /*banner_image_asset_path*/"", /*multiple*/15000, /*inline_image*/"k.item_inline_image_15012", /*inline_image_small*/"k.item_inline_image_small_15012");
INSERT INTO `m_event_marathon_booster_item` VALUES (/*id*/15013, /*name*/"k.item_name_15013", /*description*/"k.item_desc_15013", /*image_asset_path*/"o'o", /*thumbnail_asset_path*/"o'o", /*item_list_category_type*/255, /*scene_id*/1, /*banner_image_asset_path*/"", /*multiple*/15000, /*inline_image*/"k.item_inline_image_15013", /*inline_image_small*/"k.item_inline_image_small_15013");
INSERT INTO `m_event_marathon_booster_item` VALUES (/*id*/15014, /*name*/"k.item_name_15014", /*description*/"k.item_desc_15014", /*image_asset_path*/"{[6", /*thumbnail_asset_path*/"{[6", /*item_list_category_type*/255, /*scene_id*/1, /*banner_image_asset_path*/"", /*multiple*/15000, /*inline_image*/"k.item_inline_image_15014", /*inline_image_small*/"k.item_inline_image_small_15014");
INSERT INTO `m_event_marathon_booster_item` VALUES (/*id*/15015, /*name*/"k.item_name_15015", /*description*/"k.item_desc_15015", /*image_asset_path*/"z4R", /*thumbnail_asset_path*/"z4R", /*item_list_category_type*/255, /*scene_id*/1, /*banner_image_asset_path*/"", /*multiple*/15000, /*inline_image*/"k.item_inline_image_15015", /*inline_image_small*/"k.item_inline_image_small_15015");
INSERT INTO `m_event_marathon_booster_item` VALUES (/*id*/15016, /*name*/"k.item_name_15016", /*description*/"k.item_desc_15016", /*image_asset_path*/"utd", /*thumbnail_asset_path*/"utd", /*item_list_category_type*/255, /*scene_id*/1, /*banner_image_asset_path*/"", /*multiple*/15000, /*inline_image*/"k.item_inline_image_15016", /*inline_image_small*/"k.item_inline_image_small_15016");
INSERT INTO `m_event_marathon_booster_item` VALUES (/*id*/15017, /*name*/"k.item_name_15017", /*description*/"k.item_desc_15017", /*image_asset_path*/"mv7", /*thumbnail_asset_path*/"mv7", /*item_list_category_type*/255, /*scene_id*/1, /*banner_image_asset_path*/"", /*multiple*/15000, /*inline_image*/"k.item_inline_image_15017", /*inline_image_small*/"k.item_inline_image_small_15017");
INSERT INTO `m_event_marathon_booster_item` VALUES (/*id*/15018, /*name*/"k.item_name_15018", /*description*/"k.item_desc_15018", /*image_asset_path*/"ZkX", /*thumbnail_asset_path*/"ZkX", /*item_list_category_type*/255, /*scene_id*/1, /*banner_image_asset_path*/"", /*multiple*/15000, /*inline_image*/"k.item_inline_image_15018", /*inline_image_small*/"k.item_inline_image_small_15018");
INSERT INTO `m_event_marathon_booster_item` VALUES (/*id*/15019, /*name*/"k.item_name_15019", /*description*/"k.item_desc_15019", /*image_asset_path*/"HTC", /*thumbnail_asset_path*/"HTC", /*item_list_category_type*/255, /*scene_id*/1, /*banner_image_asset_path*/"", /*multiple*/15000, /*inline_image*/"k.item_inline_image_15019", /*inline_image_small*/"k.item_inline_image_small_15019");
INSERT INTO `m_event_marathon_booster_item` VALUES (/*id*/15020, /*name*/"k.item_name_15020", /*description*/"k.item_desc_15020", /*image_asset_path*/"JvG", /*thumbnail_asset_path*/"JvG", /*item_list_category_type*/255, /*scene_id*/1, /*banner_image_asset_path*/"", /*multiple*/15000, /*inline_image*/"k.item_inline_image_15020", /*inline_image_small*/"k.item_inline_image_small_15020");
INSERT INTO `m_event_marathon_booster_item` VALUES (/*id*/15021, /*name*/"k.item_name_15021", /*description*/"k.item_desc_15021", /*image_asset_path*/"n[0", /*thumbnail_asset_path*/"n[0", /*item_list_category_type*/255, /*scene_id*/1, /*banner_image_asset_path*/"", /*multiple*/15000, /*inline_image*/"k.item_inline_image_15021", /*inline_image_small*/"k.item_inline_image_small_15021");
INSERT INTO `m_event_marathon_booster_item` VALUES (/*id*/15022, /*name*/"k.item_name_15022", /*description*/"k.item_desc_15022", /*image_asset_path*/347, /*thumbnail_asset_path*/347, /*item_list_category_type*/255, /*scene_id*/1, /*banner_image_asset_path*/"", /*multiple*/15000, /*inline_image*/"k.item_inline_image_15022", /*inline_image_small*/"k.item_inline_image_small_15022");
INSERT INTO `m_event_marathon_booster_item` VALUES (/*id*/15023, /*name*/"k.item_name_15023", /*description*/"k.item_desc_15023", /*image_asset_path*/":5W", /*thumbnail_asset_path*/":5W", /*item_list_category_type*/255, /*scene_id*/1, /*banner_image_asset_path*/"", /*multiple*/15000, /*inline_image*/"k.item_inline_image_15023", /*inline_image_small*/"k.item_inline_image_small_15023");
INSERT INTO `m_event_marathon_booster_item` VALUES (/*id*/15024, /*name*/"k.item_name_15024", /*description*/"k.item_desc_15024", /*image_asset_path*/"ez,", /*thumbnail_asset_path*/"ez,", /*item_list_category_type*/255, /*scene_id*/1, /*banner_image_asset_path*/"", /*multiple*/15000, /*inline_image*/"k.item_inline_image_15024", /*inline_image_small*/"k.item_inline_image_small_15024");
INSERT INTO `m_event_marathon_booster_item` VALUES (/*id*/15025, /*name*/"k.item_name_15025", /*description*/"k.item_desc_15025", /*image_asset_path*/"|mB", /*thumbnail_asset_path*/"|mB", /*item_list_category_type*/255, /*scene_id*/1, /*banner_image_asset_path*/"", /*multiple*/15000, /*inline_image*/"k.item_inline_image_15025", /*inline_image_small*/"k.item_inline_image_small_15025");
INSERT INTO `m_event_marathon_booster_item` VALUES (/*id*/15026, /*name*/"k.item_name_15026", /*description*/"k.item_desc_15026", /*image_asset_path*/"~ZQ", /*thumbnail_asset_path*/"~ZQ", /*item_list_category_type*/255, /*scene_id*/1, /*banner_image_asset_path*/"", /*multiple*/15000, /*inline_image*/"k.item_inline_image_15026", /*inline_image_small*/"k.item_inline_image_small_15026");
INSERT INTO `m_event_marathon_booster_item` VALUES (/*id*/15027, /*name*/"k.item_name_15027", /*description*/"k.item_desc_15027", /*image_asset_path*/"X[I", /*thumbnail_asset_path*/"X[I", /*item_list_category_type*/255, /*scene_id*/1, /*banner_image_asset_path*/"", /*multiple*/15000, /*inline_image*/"k.item_inline_image_15027", /*inline_image_small*/"k.item_inline_image_small_15027");
INSERT INTO `m_event_marathon_booster_item` VALUES (/*id*/15028, /*name*/"k.item_name_15028", /*description*/"k.item_desc_15028", /*image_asset_path*/"/@G", /*thumbnail_asset_path*/"/@G", /*item_list_category_type*/255, /*scene_id*/1, /*banner_image_asset_path*/"", /*multiple*/15000, /*inline_image*/"k.item_inline_image_15028", /*inline_image_small*/"k.item_inline_image_small_15028");
INSERT INTO `m_event_marathon_booster_item` VALUES (/*id*/15029, /*name*/"k.item_name_15029", /*description*/"k.item_desc_15029", /*image_asset_path*/"0jm", /*thumbnail_asset_path*/"0jm", /*item_list_category_type*/255, /*scene_id*/1, /*banner_image_asset_path*/"", /*multiple*/15000, /*inline_image*/"k.item_inline_image_15029", /*inline_image_small*/"k.item_inline_image_small_15029");
INSERT INTO `m_event_marathon_booster_item` VALUES (/*id*/15030, /*name*/"k.item_name_15030", /*description*/"k.item_desc_15030", /*image_asset_path*/"[qQ", /*thumbnail_asset_path*/"[qQ", /*item_list_category_type*/255, /*scene_id*/1, /*banner_image_asset_path*/"", /*multiple*/15000, /*inline_image*/"k.item_inline_image_15030", /*inline_image_small*/"k.item_inline_image_small_15030");
INSERT INTO `m_event_marathon_booster_item` VALUES (/*id*/15031, /*name*/"k.item_name_15031", /*description*/"k.item_desc_15031", /*image_asset_path*/"7;R", /*thumbnail_asset_path*/"7;R", /*item_list_category_type*/255, /*scene_id*/1, /*banner_image_asset_path*/"", /*multiple*/15000, /*inline_image*/"k.item_inline_image_15031", /*inline_image_small*/"k.item_inline_image_small_15031");
INSERT INTO `m_event_marathon_booster_item` VALUES (/*id*/15032, /*name*/"k.item_name_15032", /*description*/"k.item_desc_15032", /*image_asset_path*/".\_", /*thumbnail_asset_path*/".\_", /*item_list_category_type*/255, /*scene_id*/1, /*banner_image_asset_path*/"", /*multiple*/15000, /*inline_image*/"k.item_inline_image_15032", /*inline_image_small*/"k.item_inline_image_small_15032");
INSERT INTO `m_event_marathon_booster_item` VALUES (/*id*/15033, /*name*/"k.item_name_15033", /*description*/"k.item_desc_15033", /*image_asset_path*/",OC", /*thumbnail_asset_path*/",OC", /*item_list_category_type*/255, /*scene_id*/1, /*banner_image_asset_path*/"", /*multiple*/15000, /*inline_image*/"k.item_inline_image_15033", /*inline_image_small*/"k.item_inline_image_small_15033");
INSERT INTO `m_event_marathon_booster_item` VALUES (/*id*/15034, /*name*/"k.item_name_15034", /*description*/"k.item_desc_15034", /*image_asset_path*/"\"{P", /*thumbnail_asset_path*/"\"{P", /*item_list_category_type*/255, /*scene_id*/1, /*banner_image_asset_path*/"", /*multiple*/15000, /*inline_image*/"k.item_inline_image_15034", /*inline_image_small*/"k.item_inline_image_small_15034");
INSERT INTO `m_event_marathon_booster_item` VALUES (/*id*/15035, /*name*/"k.item_name_15035", /*description*/"k.item_desc_15035", /*image_asset_path*/"R<e", /*thumbnail_asset_path*/"R<e", /*item_list_category_type*/255, /*scene_id*/1, /*banner_image_asset_path*/"", /*multiple*/15000, /*inline_image*/"k.item_inline_image_15035", /*inline_image_small*/"k.item_inline_image_small_15035");
INSERT INTO `m_event_marathon_booster_item` VALUES (/*id*/15036, /*name*/"k.item_name_15036", /*description*/"k.item_desc_15036", /*image_asset_path*/"!L0", /*thumbnail_asset_path*/"!L0", /*item_list_category_type*/255, /*scene_id*/1, /*banner_image_asset_path*/"", /*multiple*/15000, /*inline_image*/"k.item_inline_image_15036", /*inline_image_small*/"k.item_inline_image_small_15036");
INSERT INTO `m_event_marathon_booster_item` VALUES (/*id*/15037, /*name*/"k.item_name_15037", /*description*/"k.item_desc_15037", /*image_asset_path*/")/[", /*thumbnail_asset_path*/")/[", /*item_list_category_type*/255, /*scene_id*/1, /*banner_image_asset_path*/"", /*multiple*/15000, /*inline_image*/"k.item_inline_image_15037", /*inline_image_small*/"k.item_inline_image_small_15037");
INSERT INTO `m_event_marathon_booster_item` VALUES (/*id*/15901, /*name*/"k.item_name_15901", /*description*/"k.item_desc_15901", /*image_asset_path*/"%q%", /*thumbnail_asset_path*/"%q%", /*item_list_category_type*/255, /*scene_id*/1, /*banner_image_asset_path*/"", /*multiple*/15000, /*inline_image*/"k.item_inline_image_15901", /*inline_image_small*/"k.item_inline_image_small_15901");
