CREATE TABLE m_gacha_payment_setting(
  gacha_payment_type INTEGER NOT NULL,
  gacha_ticket_master_id INTEGER NOT NULL,
  name TEXT NOT NULL,
  icon TEXT NOT NULL,
  icon_s TEXT NOT NULL,
  icon_l TEXT NOT NULL,
  default_icon TEXT NOT NULL,
  default_icon_s TEXT NOT NULL,
  default_icon_l TEXT NOT NULL,
  PRIMARY KEY (gacha_payment_type, gacha_ticket_master_id)
);
INSERT INTO `m_gacha_payment_setting` VALUES (/*gacha_payment_type*/1, /*gacha_ticket_master_id*/0, /*name*/"k.m_gacha_top_draw_payment_name_text_1", /*icon*/"k.m_gacha_top_draw_payment_icon_text_1", /*icon_s*/"k.m_gacha_top_draw_payment_icon_text_5", /*icon_l*/"k.m_gacha_top_draw_payment_icon_text_9", /*default_icon*/"k.m_gacha_top_draw_payment_icon_text_1", /*default_icon_s*/"k.m_gacha_top_draw_payment_icon_text_5", /*default_icon_l*/"k.m_gacha_top_draw_payment_icon_text_9");
INSERT INTO `m_gacha_payment_setting` VALUES (/*gacha_payment_type*/2, /*gacha_ticket_master_id*/0, /*name*/"k.m_gacha_top_draw_payment_name_text_2", /*icon*/"k.m_gacha_top_draw_payment_icon_text_2", /*icon_s*/"k.m_gacha_top_draw_payment_icon_text_5", /*icon_l*/"k.m_gacha_top_draw_payment_icon_text_9", /*default_icon*/"k.m_gacha_top_draw_payment_icon_text_2", /*default_icon_s*/"k.m_gacha_top_draw_payment_icon_text_6", /*default_icon_l*/"k.m_gacha_top_draw_payment_icon_text_10");
INSERT INTO `m_gacha_payment_setting` VALUES (/*gacha_payment_type*/3, /*gacha_ticket_master_id*/9000, /*name*/"k.m_gacha_ticket_icon_text_9000", /*icon*/"k.m_gacha_ticket_icon_text_9000", /*icon_s*/"k.m_gacha_ticket_icon_text_9000_28", /*icon_l*/"k.m_gacha_ticket_icon_text_9000_32", /*default_icon*/"k.m_gacha_ticket_icon_text_9000", /*default_icon_s*/"k.m_gacha_ticket_icon_text_9000_28", /*default_icon_l*/"k.m_gacha_ticket_icon_text_9000_32");
INSERT INTO `m_gacha_payment_setting` VALUES (/*gacha_payment_type*/3, /*gacha_ticket_master_id*/9002, /*name*/"k.m_gacha_ticket_icon_text_9002", /*icon*/"k.m_gacha_ticket_icon_text_9002", /*icon_s*/"k.m_gacha_ticket_icon_text_9002_28", /*icon_l*/"k.m_gacha_ticket_icon_text_9002_32", /*default_icon*/"k.m_gacha_ticket_icon_text_9002", /*default_icon_s*/"k.m_gacha_ticket_icon_text_9002_28", /*default_icon_l*/"k.m_gacha_ticket_icon_text_9002_32");
INSERT INTO `m_gacha_payment_setting` VALUES (/*gacha_payment_type*/3, /*gacha_ticket_master_id*/9012, /*name*/"k.m_gacha_ticket_icon_text_9012", /*icon*/"k.m_gacha_ticket_icon_text_9012", /*icon_s*/"k.m_gacha_ticket_icon_text_9012_28", /*icon_l*/"k.m_gacha_ticket_icon_text_9012_32", /*default_icon*/"k.m_gacha_ticket_icon_text_9012", /*default_icon_s*/"k.m_gacha_ticket_icon_text_9012_28", /*default_icon_l*/"k.m_gacha_ticket_icon_text_9012_32");
INSERT INTO `m_gacha_payment_setting` VALUES (/*gacha_payment_type*/3, /*gacha_ticket_master_id*/9013, /*name*/"k.m_gacha_ticket_icon_text_9013", /*icon*/"k.m_gacha_ticket_icon_text_9013", /*icon_s*/"k.m_gacha_ticket_icon_text_9013_28", /*icon_l*/"k.m_gacha_ticket_icon_text_9013_32", /*default_icon*/"k.m_gacha_ticket_icon_text_9013", /*default_icon_s*/"k.m_gacha_ticket_icon_text_9013_28", /*default_icon_l*/"k.m_gacha_ticket_icon_text_9013_32");
INSERT INTO `m_gacha_payment_setting` VALUES (/*gacha_payment_type*/3, /*gacha_ticket_master_id*/9014, /*name*/"k.m_gacha_ticket_icon_text_9014", /*icon*/"k.m_gacha_ticket_icon_text_9014", /*icon_s*/"k.m_gacha_ticket_icon_text_9014_28", /*icon_l*/"k.m_gacha_ticket_icon_text_9014_32", /*default_icon*/"k.m_gacha_ticket_icon_text_9014", /*default_icon_s*/"k.m_gacha_ticket_icon_text_9014_28", /*default_icon_l*/"k.m_gacha_ticket_icon_text_9014_32");
INSERT INTO `m_gacha_payment_setting` VALUES (/*gacha_payment_type*/3, /*gacha_ticket_master_id*/9015, /*name*/"k.m_gacha_ticket_icon_text_9015", /*icon*/"k.m_gacha_ticket_icon_text_9015", /*icon_s*/"k.m_gacha_ticket_icon_text_9015_28", /*icon_l*/"k.m_gacha_ticket_icon_text_9015_32", /*default_icon*/"k.m_gacha_ticket_icon_text_9015", /*default_icon_s*/"k.m_gacha_ticket_icon_text_9015_28", /*default_icon_l*/"k.m_gacha_ticket_icon_text_9015_32");
INSERT INTO `m_gacha_payment_setting` VALUES (/*gacha_payment_type*/4, /*gacha_ticket_master_id*/9001, /*name*/"k.m_gacha_ticket_icon_text_9001", /*icon*/"k.m_gacha_ticket_icon_text_9001", /*icon_s*/"k.m_gacha_ticket_icon_text_9001_28", /*icon_l*/"k.m_gacha_ticket_icon_text_9001_32", /*default_icon*/"k.m_gacha_ticket_icon_text_9001", /*default_icon_s*/"k.m_gacha_ticket_icon_text_9001_28", /*default_icon_l*/"k.m_gacha_ticket_icon_text_9001_32");
INSERT INTO `m_gacha_payment_setting` VALUES (/*gacha_payment_type*/4, /*gacha_ticket_master_id*/9003, /*name*/"k.m_gacha_ticket_icon_text_9003", /*icon*/"k.m_gacha_ticket_icon_text_9003", /*icon_s*/"k.m_gacha_ticket_icon_text_9003_28", /*icon_l*/"k.m_gacha_ticket_icon_text_9003_32", /*default_icon*/"k.m_gacha_ticket_icon_text_9003", /*default_icon_s*/"k.m_gacha_ticket_icon_text_9003_28", /*default_icon_l*/"k.m_gacha_ticket_icon_text_9003_32");
INSERT INTO `m_gacha_payment_setting` VALUES (/*gacha_payment_type*/4, /*gacha_ticket_master_id*/9004, /*name*/"k.m_gacha_ticket_icon_text_9004", /*icon*/"k.m_gacha_ticket_icon_text_9004", /*icon_s*/"k.m_gacha_ticket_icon_text_9004_28", /*icon_l*/"k.m_gacha_ticket_icon_text_9004_32", /*default_icon*/"k.m_gacha_ticket_icon_text_9004", /*default_icon_s*/"k.m_gacha_ticket_icon_text_9004_28", /*default_icon_l*/"k.m_gacha_ticket_icon_text_9004_32");
INSERT INTO `m_gacha_payment_setting` VALUES (/*gacha_payment_type*/4, /*gacha_ticket_master_id*/9005, /*name*/"k.m_gacha_ticket_icon_text_9005", /*icon*/"k.m_gacha_ticket_icon_text_9005", /*icon_s*/"k.m_gacha_ticket_icon_text_9005_28", /*icon_l*/"k.m_gacha_ticket_icon_text_9005_32", /*default_icon*/"k.m_gacha_ticket_icon_text_9005", /*default_icon_s*/"k.m_gacha_ticket_icon_text_9005_28", /*default_icon_l*/"k.m_gacha_ticket_icon_text_9005_32");
INSERT INTO `m_gacha_payment_setting` VALUES (/*gacha_payment_type*/4, /*gacha_ticket_master_id*/9006, /*name*/"k.m_gacha_ticket_icon_text_9006", /*icon*/"k.m_gacha_ticket_icon_text_9006", /*icon_s*/"k.m_gacha_ticket_icon_text_9006_28", /*icon_l*/"k.m_gacha_ticket_icon_text_9006_32", /*default_icon*/"k.m_gacha_ticket_icon_text_9006", /*default_icon_s*/"k.m_gacha_ticket_icon_text_9006_28", /*default_icon_l*/"k.m_gacha_ticket_icon_text_9006_32");
INSERT INTO `m_gacha_payment_setting` VALUES (/*gacha_payment_type*/4, /*gacha_ticket_master_id*/9007, /*name*/"k.m_gacha_ticket_icon_text_9007", /*icon*/"k.m_gacha_ticket_icon_text_9007", /*icon_s*/"k.m_gacha_ticket_icon_text_9007_28", /*icon_l*/"k.m_gacha_ticket_icon_text_9007_32", /*default_icon*/"k.m_gacha_ticket_icon_text_9007", /*default_icon_s*/"k.m_gacha_ticket_icon_text_9007_28", /*default_icon_l*/"k.m_gacha_ticket_icon_text_9007_32");
INSERT INTO `m_gacha_payment_setting` VALUES (/*gacha_payment_type*/4, /*gacha_ticket_master_id*/9008, /*name*/"k.m_gacha_ticket_icon_text_9008", /*icon*/"k.m_gacha_ticket_icon_text_9008", /*icon_s*/"k.m_gacha_ticket_icon_text_9008_28", /*icon_l*/"k.m_gacha_ticket_icon_text_9008_32", /*default_icon*/"k.m_gacha_ticket_icon_text_9008", /*default_icon_s*/"k.m_gacha_ticket_icon_text_9008_28", /*default_icon_l*/"k.m_gacha_ticket_icon_text_9008_32");
INSERT INTO `m_gacha_payment_setting` VALUES (/*gacha_payment_type*/4, /*gacha_ticket_master_id*/9009, /*name*/"k.m_gacha_ticket_icon_text_9009", /*icon*/"k.m_gacha_ticket_icon_text_9009", /*icon_s*/"k.m_gacha_ticket_icon_text_9009_28", /*icon_l*/"k.m_gacha_ticket_icon_text_9009_32", /*default_icon*/"k.m_gacha_ticket_icon_text_9009", /*default_icon_s*/"k.m_gacha_ticket_icon_text_9009_28", /*default_icon_l*/"k.m_gacha_ticket_icon_text_9009_32");
INSERT INTO `m_gacha_payment_setting` VALUES (/*gacha_payment_type*/4, /*gacha_ticket_master_id*/9010, /*name*/"k.m_gacha_ticket_icon_text_9010", /*icon*/"k.m_gacha_ticket_icon_text_9010", /*icon_s*/"k.m_gacha_ticket_icon_text_9010_28", /*icon_l*/"k.m_gacha_ticket_icon_text_9010_32", /*default_icon*/"k.m_gacha_ticket_icon_text_9010", /*default_icon_s*/"k.m_gacha_ticket_icon_text_9010_28", /*default_icon_l*/"k.m_gacha_ticket_icon_text_9010_32");
INSERT INTO `m_gacha_payment_setting` VALUES (/*gacha_payment_type*/4, /*gacha_ticket_master_id*/9011, /*name*/"k.m_gacha_ticket_icon_text_9011", /*icon*/"k.m_gacha_ticket_icon_text_9011", /*icon_s*/"k.m_gacha_ticket_icon_text_9011_28", /*icon_l*/"k.m_gacha_ticket_icon_text_9011_32", /*default_icon*/"k.m_gacha_ticket_icon_text_9011", /*default_icon_s*/"k.m_gacha_ticket_icon_text_9011_28", /*default_icon_l*/"k.m_gacha_ticket_icon_text_9011_32");
INSERT INTO `m_gacha_payment_setting` VALUES (/*gacha_payment_type*/4, /*gacha_ticket_master_id*/9021, /*name*/"k.m_gacha_ticket_icon_text_9021", /*icon*/"k.m_gacha_ticket_icon_text_9021", /*icon_s*/"k.m_gacha_ticket_icon_text_9021_28", /*icon_l*/"k.m_gacha_ticket_icon_text_9021_32", /*default_icon*/"k.m_gacha_ticket_icon_text_9021", /*default_icon_s*/"k.m_gacha_ticket_icon_text_9021_28", /*default_icon_l*/"k.m_gacha_ticket_icon_text_9021_32");
INSERT INTO `m_gacha_payment_setting` VALUES (/*gacha_payment_type*/4, /*gacha_ticket_master_id*/9022, /*name*/"k.m_gacha_ticket_icon_text_9022", /*icon*/"k.m_gacha_ticket_icon_text_9022", /*icon_s*/"k.m_gacha_ticket_icon_text_9022_28", /*icon_l*/"k.m_gacha_ticket_icon_text_9022_32", /*default_icon*/"k.m_gacha_ticket_icon_text_9022", /*default_icon_s*/"k.m_gacha_ticket_icon_text_9022_28", /*default_icon_l*/"k.m_gacha_ticket_icon_text_9022_32");
INSERT INTO `m_gacha_payment_setting` VALUES (/*gacha_payment_type*/4, /*gacha_ticket_master_id*/9023, /*name*/"k.m_gacha_ticket_icon_text_9023", /*icon*/"k.m_gacha_ticket_icon_text_9023", /*icon_s*/"k.m_gacha_ticket_icon_text_9023_28", /*icon_l*/"k.m_gacha_ticket_icon_text_9023_32", /*default_icon*/"k.m_gacha_ticket_icon_text_9023", /*default_icon_s*/"k.m_gacha_ticket_icon_text_9023_28", /*default_icon_l*/"k.m_gacha_ticket_icon_text_9023_32");
INSERT INTO `m_gacha_payment_setting` VALUES (/*gacha_payment_type*/4, /*gacha_ticket_master_id*/9024, /*name*/"k.m_gacha_ticket_icon_text_9024", /*icon*/"k.m_gacha_ticket_icon_text_9024", /*icon_s*/"k.m_gacha_ticket_icon_text_9024_28", /*icon_l*/"k.m_gacha_ticket_icon_text_9024_32", /*default_icon*/"k.m_gacha_ticket_icon_text_9024", /*default_icon_s*/"k.m_gacha_ticket_icon_text_9024_28", /*default_icon_l*/"k.m_gacha_ticket_icon_text_9024_32");
INSERT INTO `m_gacha_payment_setting` VALUES (/*gacha_payment_type*/4, /*gacha_ticket_master_id*/9025, /*name*/"k.m_gacha_ticket_icon_text_9025", /*icon*/"k.m_gacha_ticket_icon_text_9025", /*icon_s*/"k.m_gacha_ticket_icon_text_9025_28", /*icon_l*/"k.m_gacha_ticket_icon_text_9025_32", /*default_icon*/"k.m_gacha_ticket_icon_text_9025", /*default_icon_s*/"k.m_gacha_ticket_icon_text_9025_28", /*default_icon_l*/"k.m_gacha_ticket_icon_text_9025_32");
INSERT INTO `m_gacha_payment_setting` VALUES (/*gacha_payment_type*/3, /*gacha_ticket_master_id*/9026, /*name*/"k.m_gacha_ticket_icon_text_9026", /*icon*/"k.m_gacha_ticket_icon_text_9026", /*icon_s*/"k.m_gacha_ticket_icon_text_9026_28", /*icon_l*/"k.m_gacha_ticket_icon_text_9026_32", /*default_icon*/"k.m_gacha_ticket_icon_text_9026", /*default_icon_s*/"k.m_gacha_ticket_icon_text_9026_28", /*default_icon_l*/"k.m_gacha_ticket_icon_text_9026_32");
INSERT INTO `m_gacha_payment_setting` VALUES (/*gacha_payment_type*/3, /*gacha_ticket_master_id*/9027, /*name*/"k.m_gacha_ticket_icon_text_9027", /*icon*/"k.m_gacha_ticket_icon_text_9027", /*icon_s*/"k.m_gacha_ticket_icon_text_9027_28", /*icon_l*/"k.m_gacha_ticket_icon_text_9027_32", /*default_icon*/"k.m_gacha_ticket_icon_text_9027", /*default_icon_s*/"k.m_gacha_ticket_icon_text_9027_28", /*default_icon_l*/"k.m_gacha_ticket_icon_text_9027_32");
INSERT INTO `m_gacha_payment_setting` VALUES (/*gacha_payment_type*/3, /*gacha_ticket_master_id*/9018, /*name*/"k.m_gacha_ticket_icon_text_9018", /*icon*/"k.m_gacha_ticket_icon_text_9018", /*icon_s*/"k.m_gacha_ticket_icon_text_9018_28", /*icon_l*/"k.m_gacha_ticket_icon_text_9018_32", /*default_icon*/"k.m_gacha_ticket_icon_text_9018", /*default_icon_s*/"k.m_gacha_ticket_icon_text_9018_28", /*default_icon_l*/"k.m_gacha_ticket_icon_text_9018_32");
INSERT INTO `m_gacha_payment_setting` VALUES (/*gacha_payment_type*/3, /*gacha_ticket_master_id*/9020, /*name*/"k.m_gacha_ticket_icon_text_9020", /*icon*/"k.m_gacha_ticket_icon_text_9020", /*icon_s*/"k.m_gacha_ticket_icon_text_9020_28", /*icon_l*/"k.m_gacha_ticket_icon_text_9020_32", /*default_icon*/"k.m_gacha_ticket_icon_text_9020", /*default_icon_s*/"k.m_gacha_ticket_icon_text_9020_28", /*default_icon_l*/"k.m_gacha_ticket_icon_text_9020_32");
INSERT INTO `m_gacha_payment_setting` VALUES (/*gacha_payment_type*/3, /*gacha_ticket_master_id*/9028, /*name*/"k.m_gacha_ticket_icon_text_9028", /*icon*/"k.m_gacha_ticket_icon_text_9028", /*icon_s*/"k.m_gacha_ticket_icon_text_9028_28", /*icon_l*/"k.m_gacha_ticket_icon_text_9028_32", /*default_icon*/"k.m_gacha_ticket_icon_text_9028", /*default_icon_s*/"k.m_gacha_ticket_icon_text_9028_28", /*default_icon_l*/"k.m_gacha_ticket_icon_text_9028_32");
