CREATE TABLE m_gacha_performance_monitor(
  id INTEGER NOT NULL,
  performance_id INTEGER NOT NULL,
  performance_level INTEGER NOT NULL,
  performance_level_limit INTEGER NOT NULL,
  most_rarity INTEGER NOT NULL,
  min_draw_count INTEGER NOT NULL,
  max_draw_count INTEGER NOT NULL,
  weight INTEGER NOT NULL,
  cut01_movie_monitor_asset_path TEXT NOT NULL,
  cut03_movie_monitor_in_asset_path TEXT NOT NULL,
  cut03_movie_monitor_loop_asset_path TEXT NOT NULL,
  cut02_se TEXT NOT NULL,
  PRIMARY KEY (id, performance_id, most_rarity, min_draw_count, max_draw_count)
);
INSERT INTO `m_gacha_performance_monitor` VALUES (/*id*/1, /*performance_id*/1, /*performance_level*/401, /*performance_level_limit*/301, /*most_rarity*/10, /*min_draw_count*/1, /*max_draw_count*/10, /*weight*/10000, /*cut01_movie_monitor_asset_path*/"c89", /*cut03_movie_monitor_in_asset_path*/"_Q<", /*cut03_movie_monitor_loop_asset_path*/"Res", /*cut02_se*/"se_150_0002");
INSERT INTO `m_gacha_performance_monitor` VALUES (/*id*/2, /*performance_id*/1, /*performance_level*/401, /*performance_level_limit*/301, /*most_rarity*/20, /*min_draw_count*/1, /*max_draw_count*/10, /*weight*/3000, /*cut01_movie_monitor_asset_path*/"c89", /*cut03_movie_monitor_in_asset_path*/"_Q<", /*cut03_movie_monitor_loop_asset_path*/"Res", /*cut02_se*/"se_150_0002");
INSERT INTO `m_gacha_performance_monitor` VALUES (/*id*/3, /*performance_id*/1, /*performance_level*/402, /*performance_level_limit*/301, /*most_rarity*/20, /*min_draw_count*/1, /*max_draw_count*/10, /*weight*/7000, /*cut01_movie_monitor_asset_path*/"c89", /*cut03_movie_monitor_in_asset_path*/"k$z", /*cut03_movie_monitor_loop_asset_path*/"*6{", /*cut02_se*/"se_150_0003");
INSERT INTO `m_gacha_performance_monitor` VALUES (/*id*/4, /*performance_id*/1, /*performance_level*/401, /*performance_level_limit*/301, /*most_rarity*/30, /*min_draw_count*/1, /*max_draw_count*/10, /*weight*/500, /*cut01_movie_monitor_asset_path*/"c89", /*cut03_movie_monitor_in_asset_path*/"_Q<", /*cut03_movie_monitor_loop_asset_path*/"Res", /*cut02_se*/"se_150_0002");
INSERT INTO `m_gacha_performance_monitor` VALUES (/*id*/5, /*performance_id*/1, /*performance_level*/402, /*performance_level_limit*/301, /*most_rarity*/30, /*min_draw_count*/1, /*max_draw_count*/10, /*weight*/1500, /*cut01_movie_monitor_asset_path*/"c89", /*cut03_movie_monitor_in_asset_path*/"k$z", /*cut03_movie_monitor_loop_asset_path*/"*6{", /*cut02_se*/"se_150_0003");
INSERT INTO `m_gacha_performance_monitor` VALUES (/*id*/6, /*performance_id*/1, /*performance_level*/403, /*performance_level_limit*/301, /*most_rarity*/30, /*min_draw_count*/1, /*max_draw_count*/10, /*weight*/8000, /*cut01_movie_monitor_asset_path*/"c89", /*cut03_movie_monitor_in_asset_path*/"mds", /*cut03_movie_monitor_loop_asset_path*/"d>^", /*cut02_se*/"se_150_0004");
INSERT INTO `m_gacha_performance_monitor` VALUES (/*id*/7, /*performance_id*/1, /*performance_level*/402, /*performance_level_limit*/302, /*most_rarity*/20, /*min_draw_count*/1, /*max_draw_count*/10, /*weight*/10000, /*cut01_movie_monitor_asset_path*/"c89", /*cut03_movie_monitor_in_asset_path*/"k$z", /*cut03_movie_monitor_loop_asset_path*/"*6{", /*cut02_se*/"se_150_0003");
INSERT INTO `m_gacha_performance_monitor` VALUES (/*id*/8, /*performance_id*/1, /*performance_level*/402, /*performance_level_limit*/302, /*most_rarity*/30, /*min_draw_count*/1, /*max_draw_count*/10, /*weight*/7000, /*cut01_movie_monitor_asset_path*/"c89", /*cut03_movie_monitor_in_asset_path*/"k$z", /*cut03_movie_monitor_loop_asset_path*/"*6{", /*cut02_se*/"se_150_0003");
INSERT INTO `m_gacha_performance_monitor` VALUES (/*id*/9, /*performance_id*/1, /*performance_level*/403, /*performance_level_limit*/302, /*most_rarity*/30, /*min_draw_count*/1, /*max_draw_count*/10, /*weight*/3000, /*cut01_movie_monitor_asset_path*/"c89", /*cut03_movie_monitor_in_asset_path*/"mds", /*cut03_movie_monitor_loop_asset_path*/"d>^", /*cut02_se*/"se_150_0004");
INSERT INTO `m_gacha_performance_monitor` VALUES (/*id*/10, /*performance_id*/1, /*performance_level*/403, /*performance_level_limit*/303, /*most_rarity*/30, /*min_draw_count*/1, /*max_draw_count*/10, /*weight*/7000, /*cut01_movie_monitor_asset_path*/"c89", /*cut03_movie_monitor_in_asset_path*/"mds", /*cut03_movie_monitor_loop_asset_path*/"d>^", /*cut02_se*/"se_150_0004");
INSERT INTO `m_gacha_performance_monitor` VALUES (/*id*/11, /*performance_id*/1, /*performance_level*/403, /*performance_level_limit*/303, /*most_rarity*/30, /*min_draw_count*/1, /*max_draw_count*/10, /*weight*/2000, /*cut01_movie_monitor_asset_path*/"c89", /*cut03_movie_monitor_in_asset_path*/"E1a", /*cut03_movie_monitor_loop_asset_path*/"@O/", /*cut02_se*/"se_150_0005");
INSERT INTO `m_gacha_performance_monitor` VALUES (/*id*/12, /*performance_id*/1, /*performance_level*/404, /*performance_level_limit*/303, /*most_rarity*/30, /*min_draw_count*/1, /*max_draw_count*/10, /*weight*/1000, /*cut01_movie_monitor_asset_path*/"c89", /*cut03_movie_monitor_in_asset_path*/"E1a", /*cut03_movie_monitor_loop_asset_path*/"@O/", /*cut02_se*/"se_150_0005");
INSERT INTO `m_gacha_performance_monitor` VALUES (/*id*/13, /*performance_id*/1, /*performance_level*/404, /*performance_level_limit*/304, /*most_rarity*/30, /*min_draw_count*/1, /*max_draw_count*/10, /*weight*/10000, /*cut01_movie_monitor_asset_path*/"P)6", /*cut03_movie_monitor_in_asset_path*/"E1a", /*cut03_movie_monitor_loop_asset_path*/"@O/", /*cut02_se*/"se_150_0005");
INSERT INTO `m_gacha_performance_monitor` VALUES (/*id*/14, /*performance_id*/2, /*performance_level*/402, /*performance_level_limit*/302, /*most_rarity*/20, /*min_draw_count*/1, /*max_draw_count*/10, /*weight*/10000, /*cut01_movie_monitor_asset_path*/"c89", /*cut03_movie_monitor_in_asset_path*/"k$z", /*cut03_movie_monitor_loop_asset_path*/"*6{", /*cut02_se*/"se_150_0003");
INSERT INTO `m_gacha_performance_monitor` VALUES (/*id*/15, /*performance_id*/2, /*performance_level*/404, /*performance_level_limit*/303, /*most_rarity*/30, /*min_draw_count*/1, /*max_draw_count*/10, /*weight*/7000, /*cut01_movie_monitor_asset_path*/"c89", /*cut03_movie_monitor_in_asset_path*/"mds", /*cut03_movie_monitor_loop_asset_path*/"d>^", /*cut02_se*/"se_150_0004");
INSERT INTO `m_gacha_performance_monitor` VALUES (/*id*/16, /*performance_id*/2, /*performance_level*/404, /*performance_level_limit*/303, /*most_rarity*/30, /*min_draw_count*/1, /*max_draw_count*/10, /*weight*/3000, /*cut01_movie_monitor_asset_path*/"c89", /*cut03_movie_monitor_in_asset_path*/"mds", /*cut03_movie_monitor_loop_asset_path*/"d>^", /*cut02_se*/"se_150_0004");
INSERT INTO `m_gacha_performance_monitor` VALUES (/*id*/17, /*performance_id*/3, /*performance_level*/404, /*performance_level_limit*/304, /*most_rarity*/30, /*min_draw_count*/1, /*max_draw_count*/10, /*weight*/10000, /*cut01_movie_monitor_asset_path*/"P)6", /*cut03_movie_monitor_in_asset_path*/"E1a", /*cut03_movie_monitor_loop_asset_path*/"@O/", /*cut02_se*/"se_150_0005");
INSERT INTO `m_gacha_performance_monitor` VALUES (/*id*/18, /*performance_id*/4, /*performance_level*/401, /*performance_level_limit*/301, /*most_rarity*/10, /*min_draw_count*/1, /*max_draw_count*/10, /*weight*/10000, /*cut01_movie_monitor_asset_path*/"c89", /*cut03_movie_monitor_in_asset_path*/"_Q<", /*cut03_movie_monitor_loop_asset_path*/"Res", /*cut02_se*/"se_150_0002");
INSERT INTO `m_gacha_performance_monitor` VALUES (/*id*/19, /*performance_id*/4, /*performance_level*/401, /*performance_level_limit*/301, /*most_rarity*/20, /*min_draw_count*/1, /*max_draw_count*/10, /*weight*/3000, /*cut01_movie_monitor_asset_path*/"c89", /*cut03_movie_monitor_in_asset_path*/"_Q<", /*cut03_movie_monitor_loop_asset_path*/"Res", /*cut02_se*/"se_150_0002");
INSERT INTO `m_gacha_performance_monitor` VALUES (/*id*/20, /*performance_id*/4, /*performance_level*/402, /*performance_level_limit*/301, /*most_rarity*/20, /*min_draw_count*/1, /*max_draw_count*/10, /*weight*/7000, /*cut01_movie_monitor_asset_path*/"c89", /*cut03_movie_monitor_in_asset_path*/"k$z", /*cut03_movie_monitor_loop_asset_path*/"*6{", /*cut02_se*/"se_150_0003");
INSERT INTO `m_gacha_performance_monitor` VALUES (/*id*/21, /*performance_id*/4, /*performance_level*/401, /*performance_level_limit*/301, /*most_rarity*/30, /*min_draw_count*/1, /*max_draw_count*/10, /*weight*/500, /*cut01_movie_monitor_asset_path*/"c89", /*cut03_movie_monitor_in_asset_path*/"_Q<", /*cut03_movie_monitor_loop_asset_path*/"Res", /*cut02_se*/"se_150_0002");
INSERT INTO `m_gacha_performance_monitor` VALUES (/*id*/22, /*performance_id*/4, /*performance_level*/402, /*performance_level_limit*/301, /*most_rarity*/30, /*min_draw_count*/1, /*max_draw_count*/10, /*weight*/1500, /*cut01_movie_monitor_asset_path*/"c89", /*cut03_movie_monitor_in_asset_path*/"k$z", /*cut03_movie_monitor_loop_asset_path*/"*6{", /*cut02_se*/"se_150_0003");
INSERT INTO `m_gacha_performance_monitor` VALUES (/*id*/23, /*performance_id*/4, /*performance_level*/403, /*performance_level_limit*/301, /*most_rarity*/30, /*min_draw_count*/1, /*max_draw_count*/10, /*weight*/8000, /*cut01_movie_monitor_asset_path*/"c89", /*cut03_movie_monitor_in_asset_path*/"mds", /*cut03_movie_monitor_loop_asset_path*/"d>^", /*cut02_se*/"se_150_0004");
INSERT INTO `m_gacha_performance_monitor` VALUES (/*id*/24, /*performance_id*/4, /*performance_level*/402, /*performance_level_limit*/302, /*most_rarity*/20, /*min_draw_count*/1, /*max_draw_count*/10, /*weight*/10000, /*cut01_movie_monitor_asset_path*/"c89", /*cut03_movie_monitor_in_asset_path*/"k$z", /*cut03_movie_monitor_loop_asset_path*/"*6{", /*cut02_se*/"se_150_0003");
INSERT INTO `m_gacha_performance_monitor` VALUES (/*id*/25, /*performance_id*/4, /*performance_level*/402, /*performance_level_limit*/302, /*most_rarity*/30, /*min_draw_count*/1, /*max_draw_count*/10, /*weight*/7000, /*cut01_movie_monitor_asset_path*/"c89", /*cut03_movie_monitor_in_asset_path*/"k$z", /*cut03_movie_monitor_loop_asset_path*/"*6{", /*cut02_se*/"se_150_0003");
INSERT INTO `m_gacha_performance_monitor` VALUES (/*id*/26, /*performance_id*/4, /*performance_level*/403, /*performance_level_limit*/302, /*most_rarity*/30, /*min_draw_count*/1, /*max_draw_count*/10, /*weight*/3000, /*cut01_movie_monitor_asset_path*/"c89", /*cut03_movie_monitor_in_asset_path*/"mds", /*cut03_movie_monitor_loop_asset_path*/"d>^", /*cut02_se*/"se_150_0004");
INSERT INTO `m_gacha_performance_monitor` VALUES (/*id*/27, /*performance_id*/4, /*performance_level*/403, /*performance_level_limit*/303, /*most_rarity*/30, /*min_draw_count*/1, /*max_draw_count*/10, /*weight*/7000, /*cut01_movie_monitor_asset_path*/"c89", /*cut03_movie_monitor_in_asset_path*/"mds", /*cut03_movie_monitor_loop_asset_path*/"d>^", /*cut02_se*/"se_150_0004");
INSERT INTO `m_gacha_performance_monitor` VALUES (/*id*/28, /*performance_id*/4, /*performance_level*/403, /*performance_level_limit*/303, /*most_rarity*/30, /*min_draw_count*/1, /*max_draw_count*/10, /*weight*/2000, /*cut01_movie_monitor_asset_path*/"c89", /*cut03_movie_monitor_in_asset_path*/"E1a", /*cut03_movie_monitor_loop_asset_path*/"@O/", /*cut02_se*/"se_150_0005");
INSERT INTO `m_gacha_performance_monitor` VALUES (/*id*/29, /*performance_id*/4, /*performance_level*/404, /*performance_level_limit*/303, /*most_rarity*/30, /*min_draw_count*/1, /*max_draw_count*/10, /*weight*/1000, /*cut01_movie_monitor_asset_path*/"c89", /*cut03_movie_monitor_in_asset_path*/"E1a", /*cut03_movie_monitor_loop_asset_path*/"@O/", /*cut02_se*/"se_150_0005");
INSERT INTO `m_gacha_performance_monitor` VALUES (/*id*/30, /*performance_id*/4, /*performance_level*/404, /*performance_level_limit*/304, /*most_rarity*/30, /*min_draw_count*/1, /*max_draw_count*/10, /*weight*/10000, /*cut01_movie_monitor_asset_path*/"P)6", /*cut03_movie_monitor_in_asset_path*/"E1a", /*cut03_movie_monitor_loop_asset_path*/"@O/", /*cut02_se*/"se_150_0005");
