CREATE TABLE m_info_trigger_scene(
  scene_id INTEGER NOT NULL,
  info_trigger_type INTEGER NOT NULL,
  display_priority INTEGER NOT NULL,
  PRIMARY KEY (scene_id, info_trigger_type)
);
INSERT INTO `m_info_trigger_scene` VALUES (/*scene_id*/12, /*info_trigger_type*/1, /*display_priority*/1);
INSERT INTO `m_info_trigger_scene` VALUES (/*scene_id*/12, /*info_trigger_type*/2, /*display_priority*/2);
INSERT INTO `m_info_trigger_scene` VALUES (/*scene_id*/12, /*info_trigger_type*/3, /*display_priority*/3);
INSERT INTO `m_info_trigger_scene` VALUES (/*scene_id*/12, /*info_trigger_type*/6, /*display_priority*/4);
INSERT INTO `m_info_trigger_scene` VALUES (/*scene_id*/46, /*info_trigger_type*/7, /*display_priority*/1);
INSERT INTO `m_info_trigger_scene` VALUES (/*scene_id*/46, /*info_trigger_type*/13, /*display_priority*/2);
INSERT INTO `m_info_trigger_scene` VALUES (/*scene_id*/46, /*info_trigger_type*/14, /*display_priority*/3);
INSERT INTO `m_info_trigger_scene` VALUES (/*scene_id*/37, /*info_trigger_type*/1, /*display_priority*/1);
INSERT INTO `m_info_trigger_scene` VALUES (/*scene_id*/39, /*info_trigger_type*/4, /*display_priority*/1);
INSERT INTO `m_info_trigger_scene` VALUES (/*scene_id*/32, /*info_trigger_type*/5, /*display_priority*/1);
INSERT INTO `m_info_trigger_scene` VALUES (/*scene_id*/20, /*info_trigger_type*/6, /*display_priority*/1);
INSERT INTO `m_info_trigger_scene` VALUES (/*scene_id*/16, /*info_trigger_type*/6, /*display_priority*/1);
INSERT INTO `m_info_trigger_scene` VALUES (/*scene_id*/14, /*info_trigger_type*/6, /*display_priority*/1);
INSERT INTO `m_info_trigger_scene` VALUES (/*scene_id*/22, /*info_trigger_type*/6, /*display_priority*/1);
INSERT INTO `m_info_trigger_scene` VALUES (/*scene_id*/26, /*info_trigger_type*/6, /*display_priority*/1);
INSERT INTO `m_info_trigger_scene` VALUES (/*scene_id*/29, /*info_trigger_type*/2, /*display_priority*/1);
INSERT INTO `m_info_trigger_scene` VALUES (/*scene_id*/36, /*info_trigger_type*/2, /*display_priority*/1);
INSERT INTO `m_info_trigger_scene` VALUES (/*scene_id*/12, /*info_trigger_type*/9, /*display_priority*/98);
INSERT INTO `m_info_trigger_scene` VALUES (/*scene_id*/47, /*info_trigger_type*/8, /*display_priority*/1);
INSERT INTO `m_info_trigger_scene` VALUES (/*scene_id*/47, /*info_trigger_type*/10, /*display_priority*/2);
INSERT INTO `m_info_trigger_scene` VALUES (/*scene_id*/23, /*info_trigger_type*/11, /*display_priority*/1);
INSERT INTO `m_info_trigger_scene` VALUES (/*scene_id*/23, /*info_trigger_type*/12, /*display_priority*/2);
INSERT INTO `m_info_trigger_scene` VALUES (/*scene_id*/23, /*info_trigger_type*/41, /*display_priority*/3);
INSERT INTO `m_info_trigger_scene` VALUES (/*scene_id*/46, /*info_trigger_type*/15, /*display_priority*/4);
INSERT INTO `m_info_trigger_scene` VALUES (/*scene_id*/58, /*info_trigger_type*/17, /*display_priority*/1);
INSERT INTO `m_info_trigger_scene` VALUES (/*scene_id*/12, /*info_trigger_type*/7, /*display_priority*/5);
INSERT INTO `m_info_trigger_scene` VALUES (/*scene_id*/12, /*info_trigger_type*/13, /*display_priority*/6);
INSERT INTO `m_info_trigger_scene` VALUES (/*scene_id*/12, /*info_trigger_type*/14, /*display_priority*/7);
INSERT INTO `m_info_trigger_scene` VALUES (/*scene_id*/12, /*info_trigger_type*/19, /*display_priority*/99);
INSERT INTO `m_info_trigger_scene` VALUES (/*scene_id*/60, /*info_trigger_type*/18, /*display_priority*/1);
INSERT INTO `m_info_trigger_scene` VALUES (/*scene_id*/60, /*info_trigger_type*/20, /*display_priority*/2);
INSERT INTO `m_info_trigger_scene` VALUES (/*scene_id*/64, /*info_trigger_type*/24, /*display_priority*/9);
INSERT INTO `m_info_trigger_scene` VALUES (/*scene_id*/12, /*info_trigger_type*/23, /*display_priority*/97);
INSERT INTO `m_info_trigger_scene` VALUES (/*scene_id*/64, /*info_trigger_type*/22, /*display_priority*/9);
INSERT INTO `m_info_trigger_scene` VALUES (/*scene_id*/64, /*info_trigger_type*/25, /*display_priority*/10);
INSERT INTO `m_info_trigger_scene` VALUES (/*scene_id*/64, /*info_trigger_type*/26, /*display_priority*/11);
INSERT INTO `m_info_trigger_scene` VALUES (/*scene_id*/72, /*info_trigger_type*/27, /*display_priority*/1);
INSERT INTO `m_info_trigger_scene` VALUES (/*scene_id*/72, /*info_trigger_type*/29, /*display_priority*/2);
INSERT INTO `m_info_trigger_scene` VALUES (/*scene_id*/72, /*info_trigger_type*/31, /*display_priority*/9);
INSERT INTO `m_info_trigger_scene` VALUES (/*scene_id*/73, /*info_trigger_type*/32, /*display_priority*/1);
INSERT INTO `m_info_trigger_scene` VALUES (/*scene_id*/1, /*info_trigger_type*/28, /*display_priority*/1);
INSERT INTO `m_info_trigger_scene` VALUES (/*scene_id*/1, /*info_trigger_type*/30, /*display_priority*/1);
INSERT INTO `m_info_trigger_scene` VALUES (/*scene_id*/12, /*info_trigger_type*/30, /*display_priority*/5);
INSERT INTO `m_info_trigger_scene` VALUES (/*scene_id*/12, /*info_trigger_type*/33, /*display_priority*/1);
INSERT INTO `m_info_trigger_scene` VALUES (/*scene_id*/12, /*info_trigger_type*/34, /*display_priority*/1);
INSERT INTO `m_info_trigger_scene` VALUES (/*scene_id*/78, /*info_trigger_type*/35, /*display_priority*/6);
INSERT INTO `m_info_trigger_scene` VALUES (/*scene_id*/78, /*info_trigger_type*/36, /*display_priority*/5);
INSERT INTO `m_info_trigger_scene` VALUES (/*scene_id*/78, /*info_trigger_type*/37, /*display_priority*/2);
INSERT INTO `m_info_trigger_scene` VALUES (/*scene_id*/78, /*info_trigger_type*/38, /*display_priority*/3);
INSERT INTO `m_info_trigger_scene` VALUES (/*scene_id*/78, /*info_trigger_type*/39, /*display_priority*/1);
INSERT INTO `m_info_trigger_scene` VALUES (/*scene_id*/78, /*info_trigger_type*/40, /*display_priority*/4);
INSERT INTO `m_info_trigger_scene` VALUES (/*scene_id*/78, /*info_trigger_type*/42, /*display_priority*/7);
INSERT INTO `m_info_trigger_scene` VALUES (/*scene_id*/12, /*info_trigger_type*/43, /*display_priority*/8);
INSERT INTO `m_info_trigger_scene` VALUES (/*scene_id*/79, /*info_trigger_type*/44, /*display_priority*/1);
INSERT INTO `m_info_trigger_scene` VALUES (/*scene_id*/79, /*info_trigger_type*/45, /*display_priority*/2);
INSERT INTO `m_info_trigger_scene` VALUES (/*scene_id*/12, /*info_trigger_type*/47, /*display_priority*/100);
INSERT INTO `m_info_trigger_scene` VALUES (/*scene_id*/79, /*info_trigger_type*/46, /*display_priority*/1);
