CREATE TABLE m_lesson_animation_finish(
  member_id INTEGER NOT NULL,
  running_emotion_asset_path TEXT NOT NULL,
  exhaust_emotion_asset_path TEXT NOT NULL,
  normal_emotion_asset_path TEXT NOT NULL,
  happy_emotion_asset_path TEXT NOT NULL,
  happy_flash_emotion_asset_path TEXT NOT NULL,
  happy_emotion_rank_up_asset_path TEXT NOT NULL,
  happy_flash_emotion_rank_up_asset_path TEXT NOT NULL,
  PRIMARY KEY (member_id),
  FOREIGN KEY (member_id) REFERENCES m_member(id)
);
INSERT INTO `m_lesson_animation_finish` VALUES (/*member_id*/1, /*running_emotion_asset_path*/"?R", /*exhaust_emotion_asset_path*/"gC", /*normal_emotion_asset_path*/"gD", /*happy_emotion_asset_path*/"w-", /*happy_flash_emotion_asset_path*/"xK", /*happy_emotion_rank_up_asset_path*/"r_5", /*happy_flash_emotion_rank_up_asset_path*/"/nY");
INSERT INTO `m_lesson_animation_finish` VALUES (/*member_id*/2, /*running_emotion_asset_path*/"$V", /*exhaust_emotion_asset_path*/"CR", /*normal_emotion_asset_path*/"Uv", /*happy_emotion_asset_path*/":X", /*happy_flash_emotion_asset_path*/",c", /*happy_emotion_rank_up_asset_path*/"j2z", /*happy_flash_emotion_rank_up_asset_path*/"s5m");
INSERT INTO `m_lesson_animation_finish` VALUES (/*member_id*/3, /*running_emotion_asset_path*/"5y", /*exhaust_emotion_asset_path*/"p3", /*normal_emotion_asset_path*/",~", /*happy_emotion_asset_path*/"PL", /*happy_flash_emotion_asset_path*/">p", /*happy_emotion_rank_up_asset_path*/"@\S", /*happy_flash_emotion_rank_up_asset_path*/"IM}");
INSERT INTO `m_lesson_animation_finish` VALUES (/*member_id*/4, /*running_emotion_asset_path*/"4p", /*exhaust_emotion_asset_path*/"(T", /*normal_emotion_asset_path*/"jf", /*happy_emotion_asset_path*/"0~", /*happy_flash_emotion_asset_path*/"sD", /*happy_emotion_rank_up_asset_path*/"D?a", /*happy_flash_emotion_rank_up_asset_path*/"#IF");
INSERT INTO `m_lesson_animation_finish` VALUES (/*member_id*/5, /*running_emotion_asset_path*/"s]", /*exhaust_emotion_asset_path*/"e{", /*normal_emotion_asset_path*/"E)", /*happy_emotion_asset_path*/"u#", /*happy_flash_emotion_asset_path*/"M3", /*happy_emotion_rank_up_asset_path*/"r{C", /*happy_flash_emotion_rank_up_asset_path*/"#Zd");
INSERT INTO `m_lesson_animation_finish` VALUES (/*member_id*/6, /*running_emotion_asset_path*/"%{", /*exhaust_emotion_asset_path*/"=w", /*normal_emotion_asset_path*/"Je", /*happy_emotion_asset_path*/"wH", /*happy_flash_emotion_asset_path*/"oL", /*happy_emotion_rank_up_asset_path*/"p;!", /*happy_flash_emotion_rank_up_asset_path*/"a^:");
INSERT INTO `m_lesson_animation_finish` VALUES (/*member_id*/7, /*running_emotion_asset_path*/"Jn", /*exhaust_emotion_asset_path*/"1<", /*normal_emotion_asset_path*/"m(", /*happy_emotion_asset_path*/"{!", /*happy_flash_emotion_asset_path*/"jx", /*happy_emotion_rank_up_asset_path*/"jqo", /*happy_flash_emotion_rank_up_asset_path*/"OV$");
INSERT INTO `m_lesson_animation_finish` VALUES (/*member_id*/8, /*running_emotion_asset_path*/"f&", /*exhaust_emotion_asset_path*/"T:", /*normal_emotion_asset_path*/"{a", /*happy_emotion_asset_path*/"+F", /*happy_flash_emotion_asset_path*/"~M", /*happy_emotion_rank_up_asset_path*/">F@", /*happy_flash_emotion_rank_up_asset_path*/"%*t");
INSERT INTO `m_lesson_animation_finish` VALUES (/*member_id*/9, /*running_emotion_asset_path*/"G%", /*exhaust_emotion_asset_path*/"^)", /*normal_emotion_asset_path*/"T!", /*happy_emotion_asset_path*/"IW", /*happy_flash_emotion_asset_path*/"$a", /*happy_emotion_rank_up_asset_path*/"x&I", /*happy_flash_emotion_rank_up_asset_path*/"9Y~");
INSERT INTO `m_lesson_animation_finish` VALUES (/*member_id*/101, /*running_emotion_asset_path*/"b*", /*exhaust_emotion_asset_path*/"Nr", /*normal_emotion_asset_path*/")A", /*happy_emotion_asset_path*/"[`", /*happy_flash_emotion_asset_path*/"K@", /*happy_emotion_rank_up_asset_path*/"6<l", /*happy_flash_emotion_rank_up_asset_path*/"7#;");
INSERT INTO `m_lesson_animation_finish` VALUES (/*member_id*/102, /*running_emotion_asset_path*/"rl", /*exhaust_emotion_asset_path*/"I*", /*normal_emotion_asset_path*/"V@", /*happy_emotion_asset_path*/"YQ", /*happy_flash_emotion_asset_path*/"Xp", /*happy_emotion_rank_up_asset_path*/"\"q+", /*happy_flash_emotion_rank_up_asset_path*/"yk@");
INSERT INTO `m_lesson_animation_finish` VALUES (/*member_id*/103, /*running_emotion_asset_path*/"@h", /*exhaust_emotion_asset_path*/"@r", /*normal_emotion_asset_path*/"P?", /*happy_emotion_asset_path*/"|b", /*happy_flash_emotion_asset_path*/"e.", /*happy_emotion_rank_up_asset_path*/"DOE", /*happy_flash_emotion_rank_up_asset_path*/";)0");
INSERT INTO `m_lesson_animation_finish` VALUES (/*member_id*/104, /*running_emotion_asset_path*/"Sg", /*exhaust_emotion_asset_path*/"Ra", /*normal_emotion_asset_path*/"C3", /*happy_emotion_asset_path*/"F`", /*happy_flash_emotion_asset_path*/"oH", /*happy_emotion_rank_up_asset_path*/"JQ6", /*happy_flash_emotion_rank_up_asset_path*/")!x");
INSERT INTO `m_lesson_animation_finish` VALUES (/*member_id*/105, /*running_emotion_asset_path*/"&L", /*exhaust_emotion_asset_path*/25, /*normal_emotion_asset_path*/"<m", /*happy_emotion_asset_path*/"C8", /*happy_flash_emotion_asset_path*/"aM", /*happy_emotion_rank_up_asset_path*/"tot", /*happy_flash_emotion_rank_up_asset_path*/"3}[");
INSERT INTO `m_lesson_animation_finish` VALUES (/*member_id*/106, /*running_emotion_asset_path*/"e$", /*exhaust_emotion_asset_path*/"ND", /*normal_emotion_asset_path*/"2E", /*happy_emotion_asset_path*/"!s", /*happy_flash_emotion_asset_path*/"s8", /*happy_emotion_rank_up_asset_path*/"\J[", /*happy_flash_emotion_rank_up_asset_path*/"1kZ");
INSERT INTO `m_lesson_animation_finish` VALUES (/*member_id*/107, /*running_emotion_asset_path*/"0q", /*exhaust_emotion_asset_path*/"0w", /*normal_emotion_asset_path*/"P4", /*happy_emotion_asset_path*/"T'", /*happy_flash_emotion_asset_path*/"4}", /*happy_emotion_rank_up_asset_path*/"8;P", /*happy_flash_emotion_rank_up_asset_path*/"oK0");
INSERT INTO `m_lesson_animation_finish` VALUES (/*member_id*/108, /*running_emotion_asset_path*/"jg", /*exhaust_emotion_asset_path*/"]*", /*normal_emotion_asset_path*/"M.", /*happy_emotion_asset_path*/"6~", /*happy_flash_emotion_asset_path*/"D!", /*happy_emotion_rank_up_asset_path*/"8za", /*happy_flash_emotion_rank_up_asset_path*/"iwA");
INSERT INTO `m_lesson_animation_finish` VALUES (/*member_id*/109, /*running_emotion_asset_path*/"p5", /*exhaust_emotion_asset_path*/56, /*normal_emotion_asset_path*/"4F", /*happy_emotion_asset_path*/"#2", /*happy_flash_emotion_asset_path*/"w[", /*happy_emotion_rank_up_asset_path*/"J4u", /*happy_flash_emotion_rank_up_asset_path*/"3;j");
INSERT INTO `m_lesson_animation_finish` VALUES (/*member_id*/201, /*running_emotion_asset_path*/"Ad", /*exhaust_emotion_asset_path*/"%<", /*normal_emotion_asset_path*/"2+", /*happy_emotion_asset_path*/".B", /*happy_flash_emotion_asset_path*/"q|G", /*happy_emotion_rank_up_asset_path*/"0p/", /*happy_flash_emotion_rank_up_asset_path*/"e/[");
INSERT INTO `m_lesson_animation_finish` VALUES (/*member_id*/202, /*running_emotion_asset_path*/"'E", /*exhaust_emotion_asset_path*/"JH", /*normal_emotion_asset_path*/"Cv", /*happy_emotion_asset_path*/"W<", /*happy_flash_emotion_asset_path*/"th<", /*happy_emotion_rank_up_asset_path*/"N:j", /*happy_flash_emotion_rank_up_asset_path*/"kGQ");
INSERT INTO `m_lesson_animation_finish` VALUES (/*member_id*/203, /*running_emotion_asset_path*/"3p", /*exhaust_emotion_asset_path*/"x[", /*normal_emotion_asset_path*/"EW", /*happy_emotion_asset_path*/"X>", /*happy_flash_emotion_asset_path*/"/bD", /*happy_emotion_rank_up_asset_path*/"l>b", /*happy_flash_emotion_rank_up_asset_path*/"i5P");
INSERT INTO `m_lesson_animation_finish` VALUES (/*member_id*/204, /*running_emotion_asset_path*/"V=", /*exhaust_emotion_asset_path*/"Q+", /*normal_emotion_asset_path*/"b8", /*happy_emotion_asset_path*/"Yh", /*happy_flash_emotion_asset_path*/".lc", /*happy_emotion_rank_up_asset_path*/"F08", /*happy_flash_emotion_rank_up_asset_path*/"}@v");
INSERT INTO `m_lesson_animation_finish` VALUES (/*member_id*/205, /*running_emotion_asset_path*/"db", /*exhaust_emotion_asset_path*/"]T", /*normal_emotion_asset_path*/"`2", /*happy_emotion_asset_path*/".-", /*happy_flash_emotion_asset_path*/"K+/", /*happy_emotion_rank_up_asset_path*/"0.>", /*happy_flash_emotion_rank_up_asset_path*/"a+|");
INSERT INTO `m_lesson_animation_finish` VALUES (/*member_id*/206, /*running_emotion_asset_path*/":p", /*exhaust_emotion_asset_path*/"~Z", /*normal_emotion_asset_path*/"hK", /*happy_emotion_asset_path*/"O5", /*happy_flash_emotion_asset_path*/"xn1", /*happy_emotion_rank_up_asset_path*/"$]j", /*happy_flash_emotion_rank_up_asset_path*/"kc_");
INSERT INTO `m_lesson_animation_finish` VALUES (/*member_id*/207, /*running_emotion_asset_path*/"|I", /*exhaust_emotion_asset_path*/"Ts", /*normal_emotion_asset_path*/"Ss", /*happy_emotion_asset_path*/"+B", /*happy_flash_emotion_asset_path*/"=u{", /*happy_emotion_rank_up_asset_path*/"h:%", /*happy_flash_emotion_rank_up_asset_path*/"U;\");
INSERT INTO `m_lesson_animation_finish` VALUES (/*member_id*/208, /*running_emotion_asset_path*/"wg", /*exhaust_emotion_asset_path*/"p{", /*normal_emotion_asset_path*/"YT", /*happy_emotion_asset_path*/"(^", /*happy_flash_emotion_asset_path*/"n~%", /*happy_emotion_rank_up_asset_path*/"FLF", /*happy_flash_emotion_rank_up_asset_path*/"}\&");
INSERT INTO `m_lesson_animation_finish` VALUES (/*member_id*/209, /*running_emotion_asset_path*/"ct", /*exhaust_emotion_asset_path*/"d@", /*normal_emotion_asset_path*/40, /*happy_emotion_asset_path*/"`", /*happy_flash_emotion_asset_path*/"{K^", /*happy_emotion_rank_up_asset_path*/"z3J", /*happy_flash_emotion_rank_up_asset_path*/"?(m");
