CREATE TABLE m_live_stage(
  id INTEGER NOT NULL,
  stage_model_asset_path TEXT NOT NULL,
  stage_name TEXT NOT NULL,
  scene_name TEXT NOT NULL,
  stage_thumbnail_asset_path TEXT NOT NULL,
  stage_background_asset_path TEXT NOT NULL,
  PRIMARY KEY (id)
);
INSERT INTO `m_live_stage` VALUES (/*id*/1000101, /*stage_model_asset_path*/"Y)", /*stage_name*/"k.m_dic_stage_name_bg0001_01_s1", /*scene_name*/"bg0001_01_s1", /*stage_thumbnail_asset_path*/"vg", /*stage_background_asset_path*/"SI");
INSERT INTO `m_live_stage` VALUES (/*id*/1000201, /*stage_model_asset_path*/"t\", /*stage_name*/"k.m_dic_stage_name_bg0002_01_s1", /*scene_name*/"bg0002_01_s1", /*stage_thumbnail_asset_path*/":ZE", /*stage_background_asset_path*/"Ls");
INSERT INTO `m_live_stage` VALUES (/*id*/1000301, /*stage_model_asset_path*/"h8", /*stage_name*/"k.m_dic_stage_name_bg0003_01_s1", /*scene_name*/"bg0003_01_s1", /*stage_thumbnail_asset_path*/"O9{", /*stage_background_asset_path*/"t/");
INSERT INTO `m_live_stage` VALUES (/*id*/1000401, /*stage_model_asset_path*/"%j", /*stage_name*/"k.m_dic_stage_name_bg0004_01_s1", /*scene_name*/"bg0004_01_s1", /*stage_thumbnail_asset_path*/"fq9", /*stage_background_asset_path*/"oA");
INSERT INTO `m_live_stage` VALUES (/*id*/1000501, /*stage_model_asset_path*/"vq", /*stage_name*/"k.m_dic_stage_name_bg0005_01_s1", /*scene_name*/"bg0005_01_s1", /*stage_thumbnail_asset_path*/"q]J", /*stage_background_asset_path*/":w");
INSERT INTO `m_live_stage` VALUES (/*id*/1000601, /*stage_model_asset_path*/13, /*stage_name*/"k.m_dic_stage_name_bg0006_01_s1", /*scene_name*/"bg0006_01_s1", /*stage_thumbnail_asset_path*/"LSj", /*stage_background_asset_path*/"z@");
INSERT INTO `m_live_stage` VALUES (/*id*/1000602, /*stage_model_asset_path*/"@]^", /*stage_name*/"k.m_dic_stage_name_bg0006_02_s1", /*scene_name*/"bg0006_02_s1", /*stage_thumbnail_asset_path*/"C6J", /*stage_background_asset_path*/"<2x");
INSERT INTO `m_live_stage` VALUES (/*id*/1000603, /*stage_model_asset_path*/"'Z?", /*stage_name*/"k.m_dic_stage_name_bg0006_03_s1", /*scene_name*/"bg0006_03_s1", /*stage_thumbnail_asset_path*/"<N(", /*stage_background_asset_path*/"+a`");
INSERT INTO `m_live_stage` VALUES (/*id*/1000604, /*stage_model_asset_path*/"OpK", /*stage_name*/"k.m_dic_stage_name_bg0006_04_s1", /*scene_name*/"bg0006_04_s1", /*stage_thumbnail_asset_path*/"M>F", /*stage_background_asset_path*/"_z_");
INSERT INTO `m_live_stage` VALUES (/*id*/1000610, /*stage_model_asset_path*/"#0", /*stage_name*/"k.m_dic_stage_name_bg0006_10_s1", /*scene_name*/"bg0006_10_s1", /*stage_thumbnail_asset_path*/"jtk", /*stage_background_asset_path*/"wn?");
INSERT INTO `m_live_stage` VALUES (/*id*/1000701, /*stage_model_asset_path*/"N{", /*stage_name*/"k.m_dic_stage_name_bg0007_01_s1", /*scene_name*/"bg0007_01_s1", /*stage_thumbnail_asset_path*/"m_", /*stage_background_asset_path*/">/");
INSERT INTO `m_live_stage` VALUES (/*id*/1000702, /*stage_model_asset_path*/"Eo", /*stage_name*/"k.m_dic_stage_name_bg0007_02_s1", /*scene_name*/"bg0007_02_s1", /*stage_thumbnail_asset_path*/"a2B", /*stage_background_asset_path*/"k;");
INSERT INTO `m_live_stage` VALUES (/*id*/1000703, /*stage_model_asset_path*/"YXy", /*stage_name*/"k.m_dic_stage_name_bg0007_03_s1", /*scene_name*/"bg0007_03_s1", /*stage_thumbnail_asset_path*/"m_", /*stage_background_asset_path*/">/");
INSERT INTO `m_live_stage` VALUES (/*id*/1000704, /*stage_model_asset_path*/".Dm", /*stage_name*/"k.m_dic_stage_name_bg0007_04_s1", /*scene_name*/"bg0007_04_s1", /*stage_thumbnail_asset_path*/"0P&", /*stage_background_asset_path*/"e4i");
INSERT INTO `m_live_stage` VALUES (/*id*/1000710, /*stage_model_asset_path*/"MG", /*stage_name*/"k.m_dic_stage_name_bg0007_10_s1", /*scene_name*/"bg0007_10_s1", /*stage_thumbnail_asset_path*/":SN", /*stage_background_asset_path*/"`XK");
INSERT INTO `m_live_stage` VALUES (/*id*/1000801, /*stage_model_asset_path*/"7T", /*stage_name*/"k.m_dic_stage_name_bg0008_01_s1", /*scene_name*/"bg0008_01_s1", /*stage_thumbnail_asset_path*/"nN", /*stage_background_asset_path*/"JL");
INSERT INTO `m_live_stage` VALUES (/*id*/1000810, /*stage_model_asset_path*/"`D", /*stage_name*/"k.m_dic_stage_name_bg0008_10_s1", /*scene_name*/"bg0008_10_s1", /*stage_thumbnail_asset_path*/"bF9", /*stage_background_asset_path*/"![\"");
INSERT INTO `m_live_stage` VALUES (/*id*/1000901, /*stage_model_asset_path*/"'Op", /*stage_name*/"k.m_dic_stage_name_bg0009_01_s1", /*scene_name*/"bg0009_01_s1", /*stage_thumbnail_asset_path*/"*as", /*stage_background_asset_path*/"vB");
INSERT INTO `m_live_stage` VALUES (/*id*/1001001, /*stage_model_asset_path*/"4zJ", /*stage_name*/"k.m_dic_stage_name_bg0010_01_s1", /*scene_name*/"bg0010_01_s1", /*stage_thumbnail_asset_path*/"Hs=", /*stage_background_asset_path*/"VP");
INSERT INTO `m_live_stage` VALUES (/*id*/1001101, /*stage_model_asset_path*/"7*", /*stage_name*/"k.m_dic_stage_name_bg0011_01_s1", /*scene_name*/"bg0011_01_s1", /*stage_thumbnail_asset_path*/"n|E", /*stage_background_asset_path*/"8g");
INSERT INTO `m_live_stage` VALUES (/*id*/1001201, /*stage_model_asset_path*/"Q)2", /*stage_name*/"k.m_dic_stage_name_bg0012_01_s1", /*scene_name*/"bg0012_01_s1", /*stage_thumbnail_asset_path*/"G4c", /*stage_background_asset_path*/"x~?");
INSERT INTO `m_live_stage` VALUES (/*id*/1001301, /*stage_model_asset_path*/"<v2", /*stage_name*/"k.m_dic_stage_name_bg0013_01_s1", /*scene_name*/"bg0013_01_s1", /*stage_thumbnail_asset_path*/"n?q", /*stage_background_asset_path*/"]RK");
INSERT INTO `m_live_stage` VALUES (/*id*/1001401, /*stage_model_asset_path*/"Qi$", /*stage_name*/"k.m_dic_stage_name_bg0014_01_s1", /*scene_name*/"bg0014_01_s1", /*stage_thumbnail_asset_path*/"c\"X", /*stage_background_asset_path*/"0\"#");
INSERT INTO `m_live_stage` VALUES (/*id*/1001501, /*stage_model_asset_path*/"2De", /*stage_name*/"k.m_dic_stage_name_bg0015_01_s1", /*scene_name*/"bg0015_01_s1", /*stage_thumbnail_asset_path*/"d^[", /*stage_background_asset_path*/"16L");
INSERT INTO `m_live_stage` VALUES (/*id*/1001601, /*stage_model_asset_path*/"[b%", /*stage_name*/"k.m_dic_stage_name_bg0016_01_s1", /*scene_name*/"bg0016_01_s1", /*stage_thumbnail_asset_path*/"\0r", /*stage_background_asset_path*/"u<Z");
INSERT INTO `m_live_stage` VALUES (/*id*/1001701, /*stage_model_asset_path*/"Tiu", /*stage_name*/"k.m_dic_stage_name_bg0017_01_s1", /*scene_name*/"bg0017_01_s1", /*stage_thumbnail_asset_path*/"}/y", /*stage_background_asset_path*/"Z;V");
INSERT INTO `m_live_stage` VALUES (/*id*/1001801, /*stage_model_asset_path*/">Xc", /*stage_name*/"k.m_dic_stage_name_bg0018_01_s1", /*scene_name*/"bg0018_01_s1", /*stage_thumbnail_asset_path*/"t^W", /*stage_background_asset_path*/"NkQ");
INSERT INTO `m_live_stage` VALUES (/*id*/1001802, /*stage_model_asset_path*/"h6<", /*stage_name*/"k.m_dic_stage_name_bg0018_02_s1", /*scene_name*/"bg0018_02_s1", /*stage_thumbnail_asset_path*/"MFn", /*stage_background_asset_path*/"ha[");
INSERT INTO `m_live_stage` VALUES (/*id*/1001803, /*stage_model_asset_path*/"E^k", /*stage_name*/"k.m_dic_stage_name_bg0018_03_s1", /*scene_name*/"bg0018_03_s1", /*stage_thumbnail_asset_path*/"c#U", /*stage_background_asset_path*/"hQW");
INSERT INTO `m_live_stage` VALUES (/*id*/1001901, /*stage_model_asset_path*/"<`2", /*stage_name*/"k.m_dic_stage_name_bg0019_01_s1", /*scene_name*/"bg0019_01_s1", /*stage_thumbnail_asset_path*/"-6!", /*stage_background_asset_path*/"@-8");
INSERT INTO `m_live_stage` VALUES (/*id*/1001902, /*stage_model_asset_path*/"^Vv", /*stage_name*/"k.m_dic_stage_name_bg0019_02_s1", /*scene_name*/"bg0019_02_s1", /*stage_thumbnail_asset_path*/":z}", /*stage_background_asset_path*/"W&@");
INSERT INTO `m_live_stage` VALUES (/*id*/1002001, /*stage_model_asset_path*/"2g1", /*stage_name*/"k.m_dic_stage_name_bg0020_01_s1", /*scene_name*/"bg0020_01_s1", /*stage_thumbnail_asset_path*/">RB", /*stage_background_asset_path*/"[Ro");
INSERT INTO `m_live_stage` VALUES (/*id*/1002002, /*stage_model_asset_path*/"PCo", /*stage_name*/"k.m_dic_stage_name_bg0020_02_s1", /*scene_name*/"bg0020_02_s1", /*stage_thumbnail_asset_path*/"Zc)", /*stage_background_asset_path*/"cC5");
INSERT INTO `m_live_stage` VALUES (/*id*/1002101, /*stage_model_asset_path*/"MMX", /*stage_name*/"k.m_dic_stage_name_bg0021_01_s1", /*scene_name*/"bg0021_01_s1", /*stage_thumbnail_asset_path*/"v3Z", /*stage_background_asset_path*/"m~$");
INSERT INTO `m_live_stage` VALUES (/*id*/1002201, /*stage_model_asset_path*/"wyE", /*stage_name*/"k.m_dic_stage_name_bg0022_01_s1", /*scene_name*/"bg0022_01_s1", /*stage_thumbnail_asset_path*/"T%P", /*stage_background_asset_path*/"G:(");
INSERT INTO `m_live_stage` VALUES (/*id*/1002301, /*stage_model_asset_path*/"ka", /*stage_name*/"k.m_dic_stage_name_bg0023_01_s1", /*scene_name*/"bg0023_01_s1", /*stage_thumbnail_asset_path*/"B&G", /*stage_background_asset_path*/"$j&");
INSERT INTO `m_live_stage` VALUES (/*id*/1002401, /*stage_model_asset_path*/"/;S", /*stage_name*/"k.m_dic_stage_name_bg0024_01_s1", /*scene_name*/"bg0024_01_s1", /*stage_thumbnail_asset_path*/"bqy", /*stage_background_asset_path*/"%J;");
INSERT INTO `m_live_stage` VALUES (/*id*/1002501, /*stage_model_asset_path*/"]!#", /*stage_name*/"k.m_dic_stage_name_bg0025_01_s1", /*scene_name*/"bg0025_01_s1", /*stage_thumbnail_asset_path*/"sWo", /*stage_background_asset_path*/"@{8");
INSERT INTO `m_live_stage` VALUES (/*id*/1002502, /*stage_model_asset_path*/"4/r", /*stage_name*/"k.m_dic_stage_name_bg0025_02_s1", /*scene_name*/"bg0025_02_s1", /*stage_thumbnail_asset_path*/"hx&", /*stage_background_asset_path*/"A,Z");
INSERT INTO `m_live_stage` VALUES (/*id*/1002503, /*stage_model_asset_path*/"CG6", /*stage_name*/"k.m_dic_stage_name_bg0025_03_s1", /*scene_name*/"bg0025_03_s1", /*stage_thumbnail_asset_path*/"F,H", /*stage_background_asset_path*/"5Ak");
INSERT INTO `m_live_stage` VALUES (/*id*/1002504, /*stage_model_asset_path*/"fq~", /*stage_name*/"k.m_dic_stage_name_bg0025_04_s1", /*scene_name*/"bg0025_04_s1", /*stage_thumbnail_asset_path*/"6uD", /*stage_background_asset_path*/"Iv<");
INSERT INTO `m_live_stage` VALUES (/*id*/1002505, /*stage_model_asset_path*/"/BR", /*stage_name*/"k.m_dic_stage_name_bg0025_05_s1", /*scene_name*/"bg0025_05_s1", /*stage_thumbnail_asset_path*/"Y}v", /*stage_background_asset_path*/"xnk");
INSERT INTO `m_live_stage` VALUES (/*id*/1002506, /*stage_model_asset_path*/"l;Y", /*stage_name*/"k.m_dic_stage_name_bg0025_06_s1", /*scene_name*/"bg0025_06_s1", /*stage_thumbnail_asset_path*/"+s]", /*stage_background_asset_path*/"Tq6");
INSERT INTO `m_live_stage` VALUES (/*id*/1002507, /*stage_model_asset_path*/"7Wt", /*stage_name*/"k.m_dic_stage_name_bg0025_07_s1", /*scene_name*/"bg0025_07_s1", /*stage_thumbnail_asset_path*/"+#d", /*stage_background_asset_path*/"lc:");
INSERT INTO `m_live_stage` VALUES (/*id*/1002508, /*stage_model_asset_path*/"A`\"", /*stage_name*/"k.m_dic_stage_name_bg0025_08_s1", /*scene_name*/"bg0025_08_s1", /*stage_thumbnail_asset_path*/"=Lk", /*stage_background_asset_path*/"~YA");
INSERT INTO `m_live_stage` VALUES (/*id*/1002509, /*stage_model_asset_path*/"F<E", /*stage_name*/"k.m_dic_stage_name_bg0025_09_s1", /*scene_name*/"bg0025_09_s1", /*stage_thumbnail_asset_path*/"3YK", /*stage_background_asset_path*/"Luu");
INSERT INTO `m_live_stage` VALUES (/*id*/1002510, /*stage_model_asset_path*/"+y?", /*stage_name*/"k.m_dic_stage_name_bg0025_10_s1", /*scene_name*/"bg0025_10_s1", /*stage_thumbnail_asset_path*/"3ud", /*stage_background_asset_path*/"L31");
INSERT INTO `m_live_stage` VALUES (/*id*/1002511, /*stage_model_asset_path*/"jW(", /*stage_name*/"k.m_dic_stage_name_bg0025_11_s1", /*scene_name*/"bg0025_11_s1", /*stage_thumbnail_asset_path*/"@};", /*stage_background_asset_path*/")Y1");
INSERT INTO `m_live_stage` VALUES (/*id*/1002512, /*stage_model_asset_path*/"EF7", /*stage_name*/"k.m_dic_stage_name_bg0025_12_s1", /*scene_name*/"bg0025_12_s1", /*stage_thumbnail_asset_path*/"=SL", /*stage_background_asset_path*/".+F");
INSERT INTO `m_live_stage` VALUES (/*id*/1002601, /*stage_model_asset_path*/"@\G", /*stage_name*/"k.m_dic_stage_name_bg0026_01_s1", /*scene_name*/"bg0026_01_s1", /*stage_thumbnail_asset_path*/"zZ0", /*stage_background_asset_path*/"{b6");
INSERT INTO `m_live_stage` VALUES (/*id*/1002602, /*stage_model_asset_path*/"kbS", /*stage_name*/"k.m_dic_stage_name_bg0026_02_s1", /*scene_name*/"bg0026_02_s1", /*stage_thumbnail_asset_path*/"$'R", /*stage_background_asset_path*/"E-I");
INSERT INTO `m_live_stage` VALUES (/*id*/1002701, /*stage_model_asset_path*/"V\"/", /*stage_name*/"k.m_dic_stage_name_bg0027_01_s1", /*scene_name*/"bg0027_01_s1", /*stage_thumbnail_asset_path*/"ae)", /*stage_background_asset_path*/"]|@");
INSERT INTO `m_live_stage` VALUES (/*id*/1002702, /*stage_model_asset_path*/"jqB", /*stage_name*/"k.m_dic_stage_name_bg0027_02_s1", /*scene_name*/"bg0027_02_s1", /*stage_thumbnail_asset_path*/"#[X", /*stage_background_asset_path*/"6Ro");
INSERT INTO `m_live_stage` VALUES (/*id*/1002801, /*stage_model_asset_path*/"v+,", /*stage_name*/"k.m_dic_stage_name_bg0028_01_s1", /*scene_name*/"bg0028_01_s1", /*stage_thumbnail_asset_path*/"h3\", /*stage_background_asset_path*/"YSP");
INSERT INTO `m_live_stage` VALUES (/*id*/1002901, /*stage_model_asset_path*/";0}", /*stage_name*/"k.m_dic_stage_name_bg0029_01_s1", /*scene_name*/"bg0029_01_s1", /*stage_thumbnail_asset_path*/"Uug", /*stage_background_asset_path*/"+I>");
INSERT INTO `m_live_stage` VALUES (/*id*/1003001, /*stage_model_asset_path*/",2b", /*stage_name*/"k.m_dic_stage_name_bg0030_01_s1", /*scene_name*/"bg0030_01_s1", /*stage_thumbnail_asset_path*/")L?", /*stage_background_asset_path*/"d!U");
INSERT INTO `m_live_stage` VALUES (/*id*/1003002, /*stage_model_asset_path*/"q=0", /*stage_name*/"k.m_dic_stage_name_bg0030_02_s1", /*scene_name*/"bg0030_02_s1", /*stage_thumbnail_asset_path*/"o-\"", /*stage_background_asset_path*/"-G]");
INSERT INTO `m_live_stage` VALUES (/*id*/1003101, /*stage_model_asset_path*/"p~N", /*stage_name*/"k.m_dic_stage_name_bg0031_01_s1", /*scene_name*/"bg0031_01_s1", /*stage_thumbnail_asset_path*/"-q}", /*stage_background_asset_path*/"21>");
INSERT INTO `m_live_stage` VALUES (/*id*/1003201, /*stage_model_asset_path*/"Hbc", /*stage_name*/"k.m_dic_stage_name_bg0032_01_s1", /*scene_name*/"bg0032_01_s1", /*stage_thumbnail_asset_path*/"V[1", /*stage_background_asset_path*/"%^Q");
INSERT INTO `m_live_stage` VALUES (/*id*/1003301, /*stage_model_asset_path*/"jdm", /*stage_name*/"k.m_dic_stage_name_bg0033_01_s1", /*scene_name*/"bg0033_01_s1", /*stage_thumbnail_asset_path*/"_N'", /*stage_background_asset_path*/"z{9");
