CREATE TABLE m_live_texture(
  asset_type INTEGER NOT NULL,
  asset_path TEXT NOT NULL,
  PRIMARY KEY (asset_type)
);
INSERT INTO `m_live_texture` VALUES (/*asset_type*/1, /*asset_path*/"}\"");
INSERT INTO `m_live_texture` VALUES (/*asset_type*/2, /*asset_path*/"A/");
INSERT INTO `m_live_texture` VALUES (/*asset_type*/3, /*asset_path*/"xB");
INSERT INTO `m_live_texture` VALUES (/*asset_type*/4, /*asset_path*/"Uh");
INSERT INTO `m_live_texture` VALUES (/*asset_type*/5, /*asset_path*/"GQ");
INSERT INTO `m_live_texture` VALUES (/*asset_type*/6, /*asset_path*/"tx");
INSERT INTO `m_live_texture` VALUES (/*asset_type*/7, /*asset_path*/"?L");
INSERT INTO `m_live_texture` VALUES (/*asset_type*/8, /*asset_path*/"A\");
INSERT INTO `m_live_texture` VALUES (/*asset_type*/9, /*asset_path*/"!N");
INSERT INTO `m_live_texture` VALUES (/*asset_type*/10, /*asset_path*/"M4");
INSERT INTO `m_live_texture` VALUES (/*asset_type*/11, /*asset_path*/"yV");
INSERT INTO `m_live_texture` VALUES (/*asset_type*/12, /*asset_path*/-6);
INSERT INTO `m_live_texture` VALUES (/*asset_type*/13, /*asset_path*/"M&");
INSERT INTO `m_live_texture` VALUES (/*asset_type*/14, /*asset_path*/"1~");
INSERT INTO `m_live_texture` VALUES (/*asset_type*/15, /*asset_path*/"S\");
INSERT INTO `m_live_texture` VALUES (/*asset_type*/16, /*asset_path*/"o");
INSERT INTO `m_live_texture` VALUES (/*asset_type*/17, /*asset_path*/"d0");
INSERT INTO `m_live_texture` VALUES (/*asset_type*/18, /*asset_path*/">F");
INSERT INTO `m_live_texture` VALUES (/*asset_type*/19, /*asset_path*/"X!");
INSERT INTO `m_live_texture` VALUES (/*asset_type*/20, /*asset_path*/"G[");
INSERT INTO `m_live_texture` VALUES (/*asset_type*/21, /*asset_path*/"n");
INSERT INTO `m_live_texture` VALUES (/*asset_type*/22, /*asset_path*/53);
INSERT INTO `m_live_texture` VALUES (/*asset_type*/23, /*asset_path*/"FE");
INSERT INTO `m_live_texture` VALUES (/*asset_type*/24, /*asset_path*/"sH");
INSERT INTO `m_live_texture` VALUES (/*asset_type*/25, /*asset_path*/"ev");
INSERT INTO `m_live_texture` VALUES (/*asset_type*/26, /*asset_path*/"uL");
INSERT INTO `m_live_texture` VALUES (/*asset_type*/27, /*asset_path*/"l9P");
INSERT INTO `m_live_texture` VALUES (/*asset_type*/28, /*asset_path*/"1d:");
INSERT INTO `m_live_texture` VALUES (/*asset_type*/29, /*asset_path*/"0dN");
INSERT INTO `m_live_texture` VALUES (/*asset_type*/30, /*asset_path*/"\N*");
INSERT INTO `m_live_texture` VALUES (/*asset_type*/31, /*asset_path*/"W^(");
INSERT INTO `m_live_texture` VALUES (/*asset_type*/32, /*asset_path*/"a]>");
INSERT INTO `m_live_texture` VALUES (/*asset_type*/33, /*asset_path*/"T!o");
INSERT INTO `m_live_texture` VALUES (/*asset_type*/34, /*asset_path*/"\0L");
INSERT INTO `m_live_texture` VALUES (/*asset_type*/35, /*asset_path*/"~=d");
INSERT INTO `m_live_texture` VALUES (/*asset_type*/36, /*asset_path*/"W_");
INSERT INTO `m_live_texture` VALUES (/*asset_type*/37, /*asset_path*/"<#");
INSERT INTO `m_live_texture` VALUES (/*asset_type*/38, /*asset_path*/"$\"");
INSERT INTO `m_live_texture` VALUES (/*asset_type*/39, /*asset_path*/"5,h");
INSERT INTO `m_live_texture` VALUES (/*asset_type*/40, /*asset_path*/"UtS");
INSERT INTO `m_live_texture` VALUES (/*asset_type*/41, /*asset_path*/"kqW");
INSERT INTO `m_live_texture` VALUES (/*asset_type*/42, /*asset_path*/"kRi");
INSERT INTO `m_live_texture` VALUES (/*asset_type*/43, /*asset_path*/"PhC");
INSERT INTO `m_live_texture` VALUES (/*asset_type*/44, /*asset_path*/"^,'");
INSERT INTO `m_live_texture` VALUES (/*asset_type*/45, /*asset_path*/"kYm");
INSERT INTO `m_live_texture` VALUES (/*asset_type*/46, /*asset_path*/"#Lv");
INSERT INTO `m_live_texture` VALUES (/*asset_type*/47, /*asset_path*/">{}");
INSERT INTO `m_live_texture` VALUES (/*asset_type*/48, /*asset_path*/"GC5");
INSERT INTO `m_live_texture` VALUES (/*asset_type*/49, /*asset_path*/"K^p");
INSERT INTO `m_live_texture` VALUES (/*asset_type*/50, /*asset_path*/"6d|");
INSERT INTO `m_live_texture` VALUES (/*asset_type*/51, /*asset_path*/"QLg");
INSERT INTO `m_live_texture` VALUES (/*asset_type*/52, /*asset_path*/"&c?");
INSERT INTO `m_live_texture` VALUES (/*asset_type*/53, /*asset_path*/"/f2");
