CREATE TABLE m_live_visible_definition(
  live_m_id INTEGER NOT NULL,
  safe_swing_bone INTEGER,
  live_mixer_base_mode INTEGER,
  live_enable_skin_merge INTEGER,
  PRIMARY KEY (live_m_id),
  FOREIGN KEY (live_m_id) REFERENCES m_live(live_id)
);
INSERT INTO `m_live_visible_definition` VALUES (/*live_m_id*/9999, /*safe_swing_bone*/"", /*live_mixer_base_mode*/1, /*live_enable_skin_merge*/0);
INSERT INTO `m_live_visible_definition` VALUES (/*live_m_id*/10001, /*safe_swing_bone*/"", /*live_mixer_base_mode*/1, /*live_enable_skin_merge*/0);
INSERT INTO `m_live_visible_definition` VALUES (/*live_m_id*/10002, /*safe_swing_bone*/"", /*live_mixer_base_mode*/1, /*live_enable_skin_merge*/0);
INSERT INTO `m_live_visible_definition` VALUES (/*live_m_id*/10003, /*safe_swing_bone*/"", /*live_mixer_base_mode*/2, /*live_enable_skin_merge*/0);
INSERT INTO `m_live_visible_definition` VALUES (/*live_m_id*/10004, /*safe_swing_bone*/"", /*live_mixer_base_mode*/1, /*live_enable_skin_merge*/0);
INSERT INTO `m_live_visible_definition` VALUES (/*live_m_id*/10005, /*safe_swing_bone*/"", /*live_mixer_base_mode*/1, /*live_enable_skin_merge*/0);
INSERT INTO `m_live_visible_definition` VALUES (/*live_m_id*/10008, /*safe_swing_bone*/"", /*live_mixer_base_mode*/2, /*live_enable_skin_merge*/0);
INSERT INTO `m_live_visible_definition` VALUES (/*live_m_id*/10009, /*safe_swing_bone*/"", /*live_mixer_base_mode*/2, /*live_enable_skin_merge*/0);
INSERT INTO `m_live_visible_definition` VALUES (/*live_m_id*/10010, /*safe_swing_bone*/"", /*live_mixer_base_mode*/2, /*live_enable_skin_merge*/0);
INSERT INTO `m_live_visible_definition` VALUES (/*live_m_id*/10011, /*safe_swing_bone*/"", /*live_mixer_base_mode*/1, /*live_enable_skin_merge*/0);
INSERT INTO `m_live_visible_definition` VALUES (/*live_m_id*/10012, /*safe_swing_bone*/"", /*live_mixer_base_mode*/2, /*live_enable_skin_merge*/0);
INSERT INTO `m_live_visible_definition` VALUES (/*live_m_id*/10013, /*safe_swing_bone*/"", /*live_mixer_base_mode*/2, /*live_enable_skin_merge*/0);
INSERT INTO `m_live_visible_definition` VALUES (/*live_m_id*/10014, /*safe_swing_bone*/"", /*live_mixer_base_mode*/1, /*live_enable_skin_merge*/0);
INSERT INTO `m_live_visible_definition` VALUES (/*live_m_id*/10015, /*safe_swing_bone*/"", /*live_mixer_base_mode*/1, /*live_enable_skin_merge*/0);
INSERT INTO `m_live_visible_definition` VALUES (/*live_m_id*/10016, /*safe_swing_bone*/"", /*live_mixer_base_mode*/1, /*live_enable_skin_merge*/0);
INSERT INTO `m_live_visible_definition` VALUES (/*live_m_id*/10017, /*safe_swing_bone*/"", /*live_mixer_base_mode*/2, /*live_enable_skin_merge*/0);
INSERT INTO `m_live_visible_definition` VALUES (/*live_m_id*/10021, /*safe_swing_bone*/"", /*live_mixer_base_mode*/2, /*live_enable_skin_merge*/0);
INSERT INTO `m_live_visible_definition` VALUES (/*live_m_id*/10036, /*safe_swing_bone*/"", /*live_mixer_base_mode*/2, /*live_enable_skin_merge*/0);
INSERT INTO `m_live_visible_definition` VALUES (/*live_m_id*/10037, /*safe_swing_bone*/"", /*live_mixer_base_mode*/2, /*live_enable_skin_merge*/0);
INSERT INTO `m_live_visible_definition` VALUES (/*live_m_id*/10043, /*safe_swing_bone*/"", /*live_mixer_base_mode*/2, /*live_enable_skin_merge*/0);
INSERT INTO `m_live_visible_definition` VALUES (/*live_m_id*/10049, /*safe_swing_bone*/"", /*live_mixer_base_mode*/2, /*live_enable_skin_merge*/0);
INSERT INTO `m_live_visible_definition` VALUES (/*live_m_id*/10060, /*safe_swing_bone*/"", /*live_mixer_base_mode*/2, /*live_enable_skin_merge*/0);
INSERT INTO `m_live_visible_definition` VALUES (/*live_m_id*/10062, /*safe_swing_bone*/"", /*live_mixer_base_mode*/2, /*live_enable_skin_merge*/0);
INSERT INTO `m_live_visible_definition` VALUES (/*live_m_id*/10068, /*safe_swing_bone*/"", /*live_mixer_base_mode*/2, /*live_enable_skin_merge*/0);
INSERT INTO `m_live_visible_definition` VALUES (/*live_m_id*/10071, /*safe_swing_bone*/"", /*live_mixer_base_mode*/2, /*live_enable_skin_merge*/0);
INSERT INTO `m_live_visible_definition` VALUES (/*live_m_id*/10077, /*safe_swing_bone*/"", /*live_mixer_base_mode*/2, /*live_enable_skin_merge*/0);
INSERT INTO `m_live_visible_definition` VALUES (/*live_m_id*/10089, /*safe_swing_bone*/"", /*live_mixer_base_mode*/2, /*live_enable_skin_merge*/0);
INSERT INTO `m_live_visible_definition` VALUES (/*live_m_id*/11001, /*safe_swing_bone*/"", /*live_mixer_base_mode*/1, /*live_enable_skin_merge*/0);
INSERT INTO `m_live_visible_definition` VALUES (/*live_m_id*/11002, /*safe_swing_bone*/"", /*live_mixer_base_mode*/1, /*live_enable_skin_merge*/0);
INSERT INTO `m_live_visible_definition` VALUES (/*live_m_id*/11003, /*safe_swing_bone*/"", /*live_mixer_base_mode*/2, /*live_enable_skin_merge*/0);
INSERT INTO `m_live_visible_definition` VALUES (/*live_m_id*/11004, /*safe_swing_bone*/"", /*live_mixer_base_mode*/1, /*live_enable_skin_merge*/0);
INSERT INTO `m_live_visible_definition` VALUES (/*live_m_id*/11005, /*safe_swing_bone*/"", /*live_mixer_base_mode*/1, /*live_enable_skin_merge*/0);
INSERT INTO `m_live_visible_definition` VALUES (/*live_m_id*/11006, /*safe_swing_bone*/"", /*live_mixer_base_mode*/1, /*live_enable_skin_merge*/0);
INSERT INTO `m_live_visible_definition` VALUES (/*live_m_id*/11007, /*safe_swing_bone*/"", /*live_mixer_base_mode*/1, /*live_enable_skin_merge*/0);
INSERT INTO `m_live_visible_definition` VALUES (/*live_m_id*/11008, /*safe_swing_bone*/"", /*live_mixer_base_mode*/2, /*live_enable_skin_merge*/0);
INSERT INTO `m_live_visible_definition` VALUES (/*live_m_id*/11009, /*safe_swing_bone*/"", /*live_mixer_base_mode*/2, /*live_enable_skin_merge*/0);
INSERT INTO `m_live_visible_definition` VALUES (/*live_m_id*/11010, /*safe_swing_bone*/"", /*live_mixer_base_mode*/2, /*live_enable_skin_merge*/0);
INSERT INTO `m_live_visible_definition` VALUES (/*live_m_id*/11011, /*safe_swing_bone*/"", /*live_mixer_base_mode*/2, /*live_enable_skin_merge*/0);
INSERT INTO `m_live_visible_definition` VALUES (/*live_m_id*/11012, /*safe_swing_bone*/"", /*live_mixer_base_mode*/2, /*live_enable_skin_merge*/0);
INSERT INTO `m_live_visible_definition` VALUES (/*live_m_id*/11013, /*safe_swing_bone*/0, /*live_mixer_base_mode*/2, /*live_enable_skin_merge*/1);
INSERT INTO `m_live_visible_definition` VALUES (/*live_m_id*/11014, /*safe_swing_bone*/"", /*live_mixer_base_mode*/1, /*live_enable_skin_merge*/0);
INSERT INTO `m_live_visible_definition` VALUES (/*live_m_id*/11015, /*safe_swing_bone*/"", /*live_mixer_base_mode*/2, /*live_enable_skin_merge*/0);
INSERT INTO `m_live_visible_definition` VALUES (/*live_m_id*/11017, /*safe_swing_bone*/"", /*live_mixer_base_mode*/2, /*live_enable_skin_merge*/0);
INSERT INTO `m_live_visible_definition` VALUES (/*live_m_id*/11030, /*safe_swing_bone*/"", /*live_mixer_base_mode*/2, /*live_enable_skin_merge*/0);
INSERT INTO `m_live_visible_definition` VALUES (/*live_m_id*/11042, /*safe_swing_bone*/"", /*live_mixer_base_mode*/2, /*live_enable_skin_merge*/0);
INSERT INTO `m_live_visible_definition` VALUES (/*live_m_id*/11044, /*safe_swing_bone*/"", /*live_mixer_base_mode*/2, /*live_enable_skin_merge*/0);
INSERT INTO `m_live_visible_definition` VALUES (/*live_m_id*/11046, /*safe_swing_bone*/"", /*live_mixer_base_mode*/2, /*live_enable_skin_merge*/0);
INSERT INTO `m_live_visible_definition` VALUES (/*live_m_id*/11049, /*safe_swing_bone*/"", /*live_mixer_base_mode*/2, /*live_enable_skin_merge*/0);
INSERT INTO `m_live_visible_definition` VALUES (/*live_m_id*/11072, /*safe_swing_bone*/"", /*live_mixer_base_mode*/2, /*live_enable_skin_merge*/0);
INSERT INTO `m_live_visible_definition` VALUES (/*live_m_id*/11078, /*safe_swing_bone*/"", /*live_mixer_base_mode*/2, /*live_enable_skin_merge*/0);
INSERT INTO `m_live_visible_definition` VALUES (/*live_m_id*/11079, /*safe_swing_bone*/"", /*live_mixer_base_mode*/2, /*live_enable_skin_merge*/0);
INSERT INTO `m_live_visible_definition` VALUES (/*live_m_id*/12001, /*safe_swing_bone*/"", /*live_mixer_base_mode*/1, /*live_enable_skin_merge*/0);
INSERT INTO `m_live_visible_definition` VALUES (/*live_m_id*/12002, /*safe_swing_bone*/"", /*live_mixer_base_mode*/1, /*live_enable_skin_merge*/0);
INSERT INTO `m_live_visible_definition` VALUES (/*live_m_id*/12003, /*safe_swing_bone*/"", /*live_mixer_base_mode*/1, /*live_enable_skin_merge*/0);
INSERT INTO `m_live_visible_definition` VALUES (/*live_m_id*/12004, /*safe_swing_bone*/"", /*live_mixer_base_mode*/1, /*live_enable_skin_merge*/0);
INSERT INTO `m_live_visible_definition` VALUES (/*live_m_id*/12005, /*safe_swing_bone*/"", /*live_mixer_base_mode*/1, /*live_enable_skin_merge*/0);
INSERT INTO `m_live_visible_definition` VALUES (/*live_m_id*/12006, /*safe_swing_bone*/"", /*live_mixer_base_mode*/1, /*live_enable_skin_merge*/0);
INSERT INTO `m_live_visible_definition` VALUES (/*live_m_id*/12007, /*safe_swing_bone*/1, /*live_mixer_base_mode*/1, /*live_enable_skin_merge*/0);
INSERT INTO `m_live_visible_definition` VALUES (/*live_m_id*/12008, /*safe_swing_bone*/1, /*live_mixer_base_mode*/1, /*live_enable_skin_merge*/1);
INSERT INTO `m_live_visible_definition` VALUES (/*live_m_id*/12009, /*safe_swing_bone*/"", /*live_mixer_base_mode*/1, /*live_enable_skin_merge*/0);
INSERT INTO `m_live_visible_definition` VALUES (/*live_m_id*/12010, /*safe_swing_bone*/"", /*live_mixer_base_mode*/1, /*live_enable_skin_merge*/0);
INSERT INTO `m_live_visible_definition` VALUES (/*live_m_id*/12021, /*safe_swing_bone*/"", /*live_mixer_base_mode*/2, /*live_enable_skin_merge*/0);
INSERT INTO `m_live_visible_definition` VALUES (/*live_m_id*/12022, /*safe_swing_bone*/"", /*live_mixer_base_mode*/2, /*live_enable_skin_merge*/0);
INSERT INTO `m_live_visible_definition` VALUES (/*live_m_id*/12023, /*safe_swing_bone*/"", /*live_mixer_base_mode*/2, /*live_enable_skin_merge*/0);
INSERT INTO `m_live_visible_definition` VALUES (/*live_m_id*/12024, /*safe_swing_bone*/"", /*live_mixer_base_mode*/2, /*live_enable_skin_merge*/0);
INSERT INTO `m_live_visible_definition` VALUES (/*live_m_id*/12025, /*safe_swing_bone*/"", /*live_mixer_base_mode*/2, /*live_enable_skin_merge*/0);
INSERT INTO `m_live_visible_definition` VALUES (/*live_m_id*/12026, /*safe_swing_bone*/"", /*live_mixer_base_mode*/2, /*live_enable_skin_merge*/0);
INSERT INTO `m_live_visible_definition` VALUES (/*live_m_id*/12027, /*safe_swing_bone*/"", /*live_mixer_base_mode*/2, /*live_enable_skin_merge*/0);
INSERT INTO `m_live_visible_definition` VALUES (/*live_m_id*/12028, /*safe_swing_bone*/"", /*live_mixer_base_mode*/2, /*live_enable_skin_merge*/0);
INSERT INTO `m_live_visible_definition` VALUES (/*live_m_id*/12029, /*safe_swing_bone*/"", /*live_mixer_base_mode*/2, /*live_enable_skin_merge*/0);
INSERT INTO `m_live_visible_definition` VALUES (/*live_m_id*/12030, /*safe_swing_bone*/"", /*live_mixer_base_mode*/2, /*live_enable_skin_merge*/0);
INSERT INTO `m_live_visible_definition` VALUES (/*live_m_id*/12034, /*safe_swing_bone*/0, /*live_mixer_base_mode*/2, /*live_enable_skin_merge*/1);
INSERT INTO `m_live_visible_definition` VALUES (/*live_m_id*/12037, /*safe_swing_bone*/"", /*live_mixer_base_mode*/2, /*live_enable_skin_merge*/0);
INSERT INTO `m_live_visible_definition` VALUES (/*live_m_id*/12038, /*safe_swing_bone*/"", /*live_mixer_base_mode*/2, /*live_enable_skin_merge*/0);
INSERT INTO `m_live_visible_definition` VALUES (/*live_m_id*/12056, /*safe_swing_bone*/1, /*live_mixer_base_mode*/2, /*live_enable_skin_merge*/0);
INSERT INTO `m_live_visible_definition` VALUES (/*live_m_id*/12058, /*safe_swing_bone*/"", /*live_mixer_base_mode*/2, /*live_enable_skin_merge*/0);
INSERT INTO `m_live_visible_definition` VALUES (/*live_m_id*/12059, /*safe_swing_bone*/"", /*live_mixer_base_mode*/2, /*live_enable_skin_merge*/0);
