CREATE TABLE m_love_ranking_condition_design(
  ranking_condition_type INTEGER NOT NULL,
  category INTEGER NOT NULL,
  display_index INTEGER NOT NULL,
  image_asset_path TEXT,
  text TEXT,
  simple_text TEXT NOT NULL,
  text_color INTEGER,
  text_outline_color INTEGER,
  is_default INTEGER NOT NULL,
  PRIMARY KEY (ranking_condition_type)
);
INSERT INTO `m_love_ranking_condition_design` VALUES (/*ranking_condition_type*/1, /*category*/1, /*display_index*/0, /*image_asset_path*/"", /*text*/"k.m_filter_condition_pattern_love_ranking_all", /*simple_text*/"k.m_filter_condition_pattern_love_ranking_all", /*text_color*/1229539839, /*text_outline_color*/"", /*is_default*/1);
INSERT INTO `m_love_ranking_condition_design` VALUES (/*ranking_condition_type*/2, /*category*/1, /*display_index*/1, /*image_asset_path*/"-J", /*text*/"", /*simple_text*/"k.m_dic_group_name_muse", /*text_color*/"", /*text_outline_color*/"", /*is_default*/0);
INSERT INTO `m_love_ranking_condition_design` VALUES (/*ranking_condition_type*/3, /*category*/1, /*display_index*/2, /*image_asset_path*/"7z", /*text*/"", /*simple_text*/"k.m_dic_group_name_aqours", /*text_color*/"", /*text_outline_color*/"", /*is_default*/0);
INSERT INTO `m_love_ranking_condition_design` VALUES (/*ranking_condition_type*/4, /*category*/1, /*display_index*/3, /*image_asset_path*/"Iq", /*text*/"", /*simple_text*/"k.m_filter_condition_pattern_love_ranking_group_short_name_niji", /*text_color*/"", /*text_outline_color*/"", /*is_default*/0);
INSERT INTO `m_love_ranking_condition_design` VALUES (/*ranking_condition_type*/5, /*category*/2, /*display_index*/0, /*image_asset_path*/"", /*text*/"k.m_filter_condition_pattern_love_ranking_member1", /*simple_text*/"k.m_dic_member_name_1", /*text_color*/"", /*text_outline_color*/"", /*is_default*/0);
INSERT INTO `m_love_ranking_condition_design` VALUES (/*ranking_condition_type*/6, /*category*/2, /*display_index*/1, /*image_asset_path*/"", /*text*/"k.m_filter_condition_pattern_love_ranking_member2", /*simple_text*/"k.m_dic_member_name_2", /*text_color*/"", /*text_outline_color*/"", /*is_default*/0);
INSERT INTO `m_love_ranking_condition_design` VALUES (/*ranking_condition_type*/7, /*category*/2, /*display_index*/2, /*image_asset_path*/"", /*text*/"k.m_filter_condition_pattern_love_ranking_member3", /*simple_text*/"k.m_dic_member_name_3", /*text_color*/"", /*text_outline_color*/"", /*is_default*/0);
INSERT INTO `m_love_ranking_condition_design` VALUES (/*ranking_condition_type*/8, /*category*/2, /*display_index*/3, /*image_asset_path*/"", /*text*/"k.m_filter_condition_pattern_love_ranking_member4", /*simple_text*/"k.m_dic_member_name_4", /*text_color*/"", /*text_outline_color*/"", /*is_default*/0);
INSERT INTO `m_love_ranking_condition_design` VALUES (/*ranking_condition_type*/9, /*category*/2, /*display_index*/4, /*image_asset_path*/"", /*text*/"k.m_filter_condition_pattern_love_ranking_member5", /*simple_text*/"k.m_dic_member_name_5", /*text_color*/"", /*text_outline_color*/"", /*is_default*/0);
INSERT INTO `m_love_ranking_condition_design` VALUES (/*ranking_condition_type*/10, /*category*/2, /*display_index*/5, /*image_asset_path*/"", /*text*/"k.m_filter_condition_pattern_love_ranking_member6", /*simple_text*/"k.m_dic_member_name_6", /*text_color*/"", /*text_outline_color*/"", /*is_default*/0);
INSERT INTO `m_love_ranking_condition_design` VALUES (/*ranking_condition_type*/11, /*category*/2, /*display_index*/6, /*image_asset_path*/"", /*text*/"k.m_filter_condition_pattern_love_ranking_member7", /*simple_text*/"k.m_dic_member_name_7", /*text_color*/"", /*text_outline_color*/"", /*is_default*/0);
INSERT INTO `m_love_ranking_condition_design` VALUES (/*ranking_condition_type*/12, /*category*/2, /*display_index*/7, /*image_asset_path*/"", /*text*/"k.m_filter_condition_pattern_love_ranking_member8", /*simple_text*/"k.m_dic_member_name_8", /*text_color*/"", /*text_outline_color*/"", /*is_default*/0);
INSERT INTO `m_love_ranking_condition_design` VALUES (/*ranking_condition_type*/13, /*category*/2, /*display_index*/8, /*image_asset_path*/"", /*text*/"k.m_filter_condition_pattern_love_ranking_member9", /*simple_text*/"k.m_dic_member_name_9", /*text_color*/"", /*text_outline_color*/"", /*is_default*/0);
INSERT INTO `m_love_ranking_condition_design` VALUES (/*ranking_condition_type*/14, /*category*/2, /*display_index*/9, /*image_asset_path*/"", /*text*/"k.m_filter_condition_pattern_love_ranking_member101", /*simple_text*/"k.m_dic_member_name_101", /*text_color*/"", /*text_outline_color*/"", /*is_default*/0);
INSERT INTO `m_love_ranking_condition_design` VALUES (/*ranking_condition_type*/15, /*category*/2, /*display_index*/10, /*image_asset_path*/"", /*text*/"k.m_filter_condition_pattern_love_ranking_member102", /*simple_text*/"k.m_dic_member_name_102", /*text_color*/"", /*text_outline_color*/"", /*is_default*/0);
INSERT INTO `m_love_ranking_condition_design` VALUES (/*ranking_condition_type*/16, /*category*/2, /*display_index*/11, /*image_asset_path*/"", /*text*/"k.m_filter_condition_pattern_love_ranking_member103", /*simple_text*/"k.m_dic_member_name_103", /*text_color*/"", /*text_outline_color*/"", /*is_default*/0);
INSERT INTO `m_love_ranking_condition_design` VALUES (/*ranking_condition_type*/17, /*category*/2, /*display_index*/12, /*image_asset_path*/"", /*text*/"k.m_filter_condition_pattern_love_ranking_member104", /*simple_text*/"k.m_dic_member_name_104", /*text_color*/"", /*text_outline_color*/"", /*is_default*/0);
INSERT INTO `m_love_ranking_condition_design` VALUES (/*ranking_condition_type*/18, /*category*/2, /*display_index*/13, /*image_asset_path*/"", /*text*/"k.m_filter_condition_pattern_love_ranking_member105", /*simple_text*/"k.m_dic_member_name_105", /*text_color*/"", /*text_outline_color*/"", /*is_default*/0);
INSERT INTO `m_love_ranking_condition_design` VALUES (/*ranking_condition_type*/19, /*category*/2, /*display_index*/14, /*image_asset_path*/"", /*text*/"k.m_filter_condition_pattern_love_ranking_member106", /*simple_text*/"k.m_dic_member_name_106", /*text_color*/"", /*text_outline_color*/"", /*is_default*/0);
INSERT INTO `m_love_ranking_condition_design` VALUES (/*ranking_condition_type*/20, /*category*/2, /*display_index*/15, /*image_asset_path*/"", /*text*/"k.m_filter_condition_pattern_love_ranking_member107", /*simple_text*/"k.m_dic_member_name_107", /*text_color*/"", /*text_outline_color*/"", /*is_default*/0);
INSERT INTO `m_love_ranking_condition_design` VALUES (/*ranking_condition_type*/21, /*category*/2, /*display_index*/16, /*image_asset_path*/"", /*text*/"k.m_filter_condition_pattern_love_ranking_member108", /*simple_text*/"k.m_dic_member_name_108", /*text_color*/"", /*text_outline_color*/"", /*is_default*/0);
INSERT INTO `m_love_ranking_condition_design` VALUES (/*ranking_condition_type*/22, /*category*/2, /*display_index*/17, /*image_asset_path*/"", /*text*/"k.m_filter_condition_pattern_love_ranking_member109", /*simple_text*/"k.m_dic_member_name_109", /*text_color*/"", /*text_outline_color*/"", /*is_default*/0);
INSERT INTO `m_love_ranking_condition_design` VALUES (/*ranking_condition_type*/23, /*category*/2, /*display_index*/18, /*image_asset_path*/"", /*text*/"k.m_filter_condition_pattern_love_ranking_member201", /*simple_text*/"k.m_dic_member_name_201", /*text_color*/"", /*text_outline_color*/"", /*is_default*/0);
INSERT INTO `m_love_ranking_condition_design` VALUES (/*ranking_condition_type*/24, /*category*/2, /*display_index*/19, /*image_asset_path*/"", /*text*/"k.m_filter_condition_pattern_love_ranking_member202", /*simple_text*/"k.m_dic_member_name_202", /*text_color*/"", /*text_outline_color*/"", /*is_default*/0);
INSERT INTO `m_love_ranking_condition_design` VALUES (/*ranking_condition_type*/25, /*category*/2, /*display_index*/20, /*image_asset_path*/"", /*text*/"k.m_filter_condition_pattern_love_ranking_member203", /*simple_text*/"k.m_dic_member_name_203", /*text_color*/"", /*text_outline_color*/"", /*is_default*/0);
INSERT INTO `m_love_ranking_condition_design` VALUES (/*ranking_condition_type*/26, /*category*/2, /*display_index*/21, /*image_asset_path*/"", /*text*/"k.m_filter_condition_pattern_love_ranking_member204", /*simple_text*/"k.m_dic_member_name_204", /*text_color*/"", /*text_outline_color*/"", /*is_default*/0);
INSERT INTO `m_love_ranking_condition_design` VALUES (/*ranking_condition_type*/27, /*category*/2, /*display_index*/22, /*image_asset_path*/"", /*text*/"k.m_filter_condition_pattern_love_ranking_member205", /*simple_text*/"k.m_dic_member_name_205", /*text_color*/"", /*text_outline_color*/"", /*is_default*/0);
INSERT INTO `m_love_ranking_condition_design` VALUES (/*ranking_condition_type*/28, /*category*/2, /*display_index*/23, /*image_asset_path*/"", /*text*/"k.m_filter_condition_pattern_love_ranking_member206", /*simple_text*/"k.m_dic_member_name_206", /*text_color*/"", /*text_outline_color*/"", /*is_default*/0);
INSERT INTO `m_love_ranking_condition_design` VALUES (/*ranking_condition_type*/29, /*category*/2, /*display_index*/24, /*image_asset_path*/"", /*text*/"k.m_filter_condition_pattern_love_ranking_member207", /*simple_text*/"k.m_dic_member_name_207", /*text_color*/"", /*text_outline_color*/"", /*is_default*/0);
INSERT INTO `m_love_ranking_condition_design` VALUES (/*ranking_condition_type*/30, /*category*/2, /*display_index*/25, /*image_asset_path*/"", /*text*/"k.m_filter_condition_pattern_love_ranking_member208", /*simple_text*/"k.m_dic_member_name_208", /*text_color*/"", /*text_outline_color*/"", /*is_default*/0);
INSERT INTO `m_love_ranking_condition_design` VALUES (/*ranking_condition_type*/31, /*category*/2, /*display_index*/26, /*image_asset_path*/"", /*text*/"k.m_filter_condition_pattern_love_ranking_member209", /*simple_text*/"k.m_dic_member_name_209", /*text_color*/"", /*text_outline_color*/"", /*is_default*/0);
