CREATE TABLE m_member_guild(
  member_master_id INTEGER NOT NULL,
  name TEXT NOT NULL,
  logo_asset_path TEXT NOT NULL,
  top_background_asset_path TEXT NOT NULL,
  top_graffiti_asset_path TEXT NOT NULL,
  top_desk_asset_path TEXT NOT NULL,
  top_desk_logo_asset_path TEXT,
  text TEXT NOT NULL,
  ranking_open_text TEXT NOT NULL,
  ranking_end_text TEXT NOT NULL,
  trade_m_id INTEGER NOT NULL,
  start_at INTEGER NOT NULL,
  PRIMARY KEY (member_master_id),
  FOREIGN KEY (member_master_id) REFERENCES m_member(id),
  FOREIGN KEY (trade_m_id) REFERENCES m_trade(id)
);
INSERT INTO `m_member_guild` VALUES (/*member_master_id*/1, /*name*/"k.member_guild_name_001", /*logo_asset_path*/"dmc", /*top_background_asset_path*/"p4w", /*top_graffiti_asset_path*/"9e[", /*top_desk_asset_path*/"c9,", /*top_desk_logo_asset_path*/"", /*text*/"k.member_guild_board_001", /*ranking_open_text*/"k.member_guild_board_01_001", /*ranking_end_text*/"k.member_guild_board_02_001", /*trade_m_id*/50001, /*start_at*/1617008400);
INSERT INTO `m_member_guild` VALUES (/*member_master_id*/2, /*name*/"k.member_guild_name_002", /*logo_asset_path*/"ELL", /*top_background_asset_path*/"p4w", /*top_graffiti_asset_path*/":.9", /*top_desk_asset_path*/"c9,", /*top_desk_logo_asset_path*/"", /*text*/"k.member_guild_board_002", /*ranking_open_text*/"k.member_guild_board_01_002", /*ranking_end_text*/"k.member_guild_board_02_002", /*trade_m_id*/50002, /*start_at*/1617008400);
INSERT INTO `m_member_guild` VALUES (/*member_master_id*/3, /*name*/"k.member_guild_name_003", /*logo_asset_path*/"<J5", /*top_background_asset_path*/"p4w", /*top_graffiti_asset_path*/"yF#", /*top_desk_asset_path*/"c9,", /*top_desk_logo_asset_path*/"", /*text*/"k.member_guild_board_003", /*ranking_open_text*/"k.member_guild_board_01_003", /*ranking_end_text*/"k.member_guild_board_02_003", /*trade_m_id*/50003, /*start_at*/1617008400);
INSERT INTO `m_member_guild` VALUES (/*member_master_id*/4, /*name*/"k.member_guild_name_004", /*logo_asset_path*/"s<z", /*top_background_asset_path*/"p4w", /*top_graffiti_asset_path*/">qk", /*top_desk_asset_path*/"c9,", /*top_desk_logo_asset_path*/"", /*text*/"k.member_guild_board_004", /*ranking_open_text*/"k.member_guild_board_01_004", /*ranking_end_text*/"k.member_guild_board_02_004", /*trade_m_id*/50004, /*start_at*/1617008400);
INSERT INTO `m_member_guild` VALUES (/*member_master_id*/5, /*name*/"k.member_guild_name_005", /*logo_asset_path*/">zJ", /*top_background_asset_path*/"p4w", /*top_graffiti_asset_path*/"=kP", /*top_desk_asset_path*/"c9,", /*top_desk_logo_asset_path*/"", /*text*/"k.member_guild_board_005", /*ranking_open_text*/"k.member_guild_board_01_005", /*ranking_end_text*/"k.member_guild_board_02_005", /*trade_m_id*/50005, /*start_at*/1617008400);
INSERT INTO `m_member_guild` VALUES (/*member_master_id*/6, /*name*/"k.member_guild_name_006", /*logo_asset_path*/"/OH", /*top_background_asset_path*/"p4w", /*top_graffiti_asset_path*/"t+*", /*top_desk_asset_path*/"c9,", /*top_desk_logo_asset_path*/"", /*text*/"k.member_guild_board_006", /*ranking_open_text*/"k.member_guild_board_01_006", /*ranking_end_text*/"k.member_guild_board_02_006", /*trade_m_id*/50006, /*start_at*/1617008400);
INSERT INTO `m_member_guild` VALUES (/*member_master_id*/7, /*name*/"k.member_guild_name_007", /*logo_asset_path*/"J]l", /*top_background_asset_path*/"p4w", /*top_graffiti_asset_path*/"-@H", /*top_desk_asset_path*/"c9,", /*top_desk_logo_asset_path*/"", /*text*/"k.member_guild_board_007", /*ranking_open_text*/"k.member_guild_board_01_007", /*ranking_end_text*/"k.member_guild_board_02_007", /*trade_m_id*/50007, /*start_at*/1617008400);
INSERT INTO `m_member_guild` VALUES (/*member_master_id*/8, /*name*/"k.member_guild_name_008", /*logo_asset_path*/"1Q&", /*top_background_asset_path*/"p4w", /*top_graffiti_asset_path*/"``G", /*top_desk_asset_path*/"c9,", /*top_desk_logo_asset_path*/"", /*text*/"k.member_guild_board_008", /*ranking_open_text*/"k.member_guild_board_01_008", /*ranking_end_text*/"k.member_guild_board_02_008", /*trade_m_id*/50008, /*start_at*/1617008400);
INSERT INTO `m_member_guild` VALUES (/*member_master_id*/9, /*name*/"k.member_guild_name_009", /*logo_asset_path*/"0%\"", /*top_background_asset_path*/"p4w", /*top_graffiti_asset_path*/"}}p", /*top_desk_asset_path*/"c9,", /*top_desk_logo_asset_path*/"", /*text*/"k.member_guild_board_009", /*ranking_open_text*/"k.member_guild_board_01_009", /*ranking_end_text*/"k.member_guild_board_02_009", /*trade_m_id*/50009, /*start_at*/1617008400);
INSERT INTO `m_member_guild` VALUES (/*member_master_id*/101, /*name*/"k.member_guild_name_101", /*logo_asset_path*/"[Kf", /*top_background_asset_path*/"]=`", /*top_graffiti_asset_path*/"h;h", /*top_desk_asset_path*/"4^R", /*top_desk_logo_asset_path*/"", /*text*/"k.member_guild_board_101", /*ranking_open_text*/"k.member_guild_board_01_101", /*ranking_end_text*/"k.member_guild_board_02_101", /*trade_m_id*/50101, /*start_at*/1617008400);
INSERT INTO `m_member_guild` VALUES (/*member_master_id*/102, /*name*/"k.member_guild_name_102", /*logo_asset_path*/"BS:", /*top_background_asset_path*/"]=`", /*top_graffiti_asset_path*/"1F=", /*top_desk_asset_path*/"4^R", /*top_desk_logo_asset_path*/"", /*text*/"k.member_guild_board_102", /*ranking_open_text*/"k.member_guild_board_01_102", /*ranking_end_text*/"k.member_guild_board_02_102", /*trade_m_id*/50102, /*start_at*/1617008400);
INSERT INTO `m_member_guild` VALUES (/*member_master_id*/103, /*name*/"k.member_guild_name_103", /*logo_asset_path*/"9=g", /*top_background_asset_path*/"]=`", /*top_graffiti_asset_path*/":m.", /*top_desk_asset_path*/"4^R", /*top_desk_logo_asset_path*/"", /*text*/"k.member_guild_board_103", /*ranking_open_text*/"k.member_guild_board_01_103", /*ranking_end_text*/"k.member_guild_board_02_103", /*trade_m_id*/50103, /*start_at*/1617008400);
INSERT INTO `m_member_guild` VALUES (/*member_master_id*/104, /*name*/"k.member_guild_name_104", /*logo_asset_path*/">8Y", /*top_background_asset_path*/"]=`", /*top_graffiti_asset_path*/"q/Q", /*top_desk_asset_path*/"4^R", /*top_desk_logo_asset_path*/"", /*text*/"k.member_guild_board_104", /*ranking_open_text*/"k.member_guild_board_01_104", /*ranking_end_text*/"k.member_guild_board_02_104", /*trade_m_id*/50104, /*start_at*/1617008400);
INSERT INTO `m_member_guild` VALUES (/*member_master_id*/105, /*name*/"k.member_guild_name_105", /*logo_asset_path*/"5XM", /*top_background_asset_path*/"]=`", /*top_graffiti_asset_path*/",+D", /*top_desk_asset_path*/"4^R", /*top_desk_logo_asset_path*/"", /*text*/"k.member_guild_board_105", /*ranking_open_text*/"k.member_guild_board_01_105", /*ranking_end_text*/"k.member_guild_board_02_105", /*trade_m_id*/50105, /*start_at*/1617008400);
INSERT INTO `m_member_guild` VALUES (/*member_master_id*/106, /*name*/"k.member_guild_name_106", /*logo_asset_path*/">Iw", /*top_background_asset_path*/"]=`", /*top_graffiti_asset_path*/"C?b", /*top_desk_asset_path*/"4^R", /*top_desk_logo_asset_path*/"", /*text*/"k.member_guild_board_106", /*ranking_open_text*/"k.member_guild_board_01_106", /*ranking_end_text*/"k.member_guild_board_02_106", /*trade_m_id*/50106, /*start_at*/1617008400);
INSERT INTO `m_member_guild` VALUES (/*member_master_id*/107, /*name*/"k.member_guild_name_107", /*logo_asset_path*/"GP@", /*top_background_asset_path*/"]=`", /*top_graffiti_asset_path*/"<:w", /*top_desk_asset_path*/"4^R", /*top_desk_logo_asset_path*/"", /*text*/"k.member_guild_board_107", /*ranking_open_text*/"k.member_guild_board_01_107", /*ranking_end_text*/"k.member_guild_board_02_107", /*trade_m_id*/50107, /*start_at*/1617008400);
INSERT INTO `m_member_guild` VALUES (/*member_master_id*/108, /*name*/"k.member_guild_name_108", /*logo_asset_path*/"|MM", /*top_background_asset_path*/"]=`", /*top_graffiti_asset_path*/"]Sy", /*top_desk_asset_path*/"4^R", /*top_desk_logo_asset_path*/"", /*text*/"k.member_guild_board_108", /*ranking_open_text*/"k.member_guild_board_01_108", /*ranking_end_text*/"k.member_guild_board_02_108", /*trade_m_id*/50108, /*start_at*/1617008400);
INSERT INTO `m_member_guild` VALUES (/*member_master_id*/109, /*name*/"k.member_guild_name_109", /*logo_asset_path*/"-vS", /*top_background_asset_path*/"]=`", /*top_graffiti_asset_path*/"d7+", /*top_desk_asset_path*/"4^R", /*top_desk_logo_asset_path*/"", /*text*/"k.member_guild_board_109", /*ranking_open_text*/"k.member_guild_board_01_109", /*ranking_end_text*/"k.member_guild_board_02_109", /*trade_m_id*/50109, /*start_at*/1617008400);
INSERT INTO `m_member_guild` VALUES (/*member_master_id*/201, /*name*/"k.member_guild_name_201", /*logo_asset_path*/"jE7", /*top_background_asset_path*/"8qE", /*top_graffiti_asset_path*/"eh=", /*top_desk_asset_path*/"aCU", /*top_desk_logo_asset_path*/"GY", /*text*/"k.member_guild_board_201", /*ranking_open_text*/"k.member_guild_board_01_201", /*ranking_end_text*/"k.member_guild_board_02_201", /*trade_m_id*/50201, /*start_at*/1617008400);
INSERT INTO `m_member_guild` VALUES (/*member_master_id*/202, /*name*/"k.member_guild_name_202", /*logo_asset_path*/"?Fl", /*top_background_asset_path*/"8qE", /*top_graffiti_asset_path*/"@@l", /*top_desk_asset_path*/"aCU", /*top_desk_logo_asset_path*/"GY", /*text*/"k.member_guild_board_202", /*ranking_open_text*/"k.member_guild_board_01_202", /*ranking_end_text*/"k.member_guild_board_02_202", /*trade_m_id*/50202, /*start_at*/1617008400);
INSERT INTO `m_member_guild` VALUES (/*member_master_id*/203, /*name*/"k.member_guild_name_203", /*logo_asset_path*/"VZ4", /*top_background_asset_path*/"8qE", /*top_graffiti_asset_path*/"7``", /*top_desk_asset_path*/"aCU", /*top_desk_logo_asset_path*/"GY", /*text*/"k.member_guild_board_203", /*ranking_open_text*/"k.member_guild_board_01_203", /*ranking_end_text*/"k.member_guild_board_02_203", /*trade_m_id*/50203, /*start_at*/1617008400);
INSERT INTO `m_member_guild` VALUES (/*member_master_id*/204, /*name*/"k.member_guild_name_204", /*logo_asset_path*/";+-", /*top_background_asset_path*/"8qE", /*top_graffiti_asset_path*/"`MD", /*top_desk_asset_path*/"aCU", /*top_desk_logo_asset_path*/"GY", /*text*/"k.member_guild_board_204", /*ranking_open_text*/"k.member_guild_board_01_204", /*ranking_end_text*/"k.member_guild_board_02_204", /*trade_m_id*/50204, /*start_at*/1617008400);
INSERT INTO `m_member_guild` VALUES (/*member_master_id*/205, /*name*/"k.member_guild_name_205", /*logo_asset_path*/"DR|", /*top_background_asset_path*/"8qE", /*top_graffiti_asset_path*/"_#+", /*top_desk_asset_path*/"aCU", /*top_desk_logo_asset_path*/"GY", /*text*/"k.member_guild_board_205", /*ranking_open_text*/"k.member_guild_board_01_205", /*ranking_end_text*/"k.member_guild_board_02_205", /*trade_m_id*/50205, /*start_at*/1617008400);
INSERT INTO `m_member_guild` VALUES (/*member_master_id*/206, /*name*/"k.member_guild_name_206", /*logo_asset_path*/"qe\", /*top_background_asset_path*/"8qE", /*top_graffiti_asset_path*/"R93", /*top_desk_asset_path*/"aCU", /*top_desk_logo_asset_path*/"GY", /*text*/"k.member_guild_board_206", /*ranking_open_text*/"k.member_guild_board_01_206", /*ranking_end_text*/"k.member_guild_board_02_206", /*trade_m_id*/50206, /*start_at*/1617008400);
INSERT INTO `m_member_guild` VALUES (/*member_master_id*/207, /*name*/"k.member_guild_name_207", /*logo_asset_path*/"lsF", /*top_background_asset_path*/"8qE", /*top_graffiti_asset_path*/"3vy", /*top_desk_asset_path*/"aCU", /*top_desk_logo_asset_path*/"GY", /*text*/"k.member_guild_board_207", /*ranking_open_text*/"k.member_guild_board_01_207", /*ranking_end_text*/"k.member_guild_board_02_207", /*trade_m_id*/50207, /*start_at*/1617008400);
INSERT INTO `m_member_guild` VALUES (/*member_master_id*/208, /*name*/"k.member_guild_name_208", /*logo_asset_path*/"Cum", /*top_background_asset_path*/"8qE", /*top_graffiti_asset_path*/"dS9", /*top_desk_asset_path*/"aCU", /*top_desk_logo_asset_path*/"GY", /*text*/"k.member_guild_board_208", /*ranking_open_text*/"k.member_guild_board_01_208", /*ranking_end_text*/"k.member_guild_board_02_208", /*trade_m_id*/50208, /*start_at*/1617008400);
INSERT INTO `m_member_guild` VALUES (/*member_master_id*/209, /*name*/"k.member_guild_name_209", /*logo_asset_path*/"L>_", /*top_background_asset_path*/"8qE", /*top_graffiti_asset_path*/"S3i", /*top_desk_asset_path*/"aCU", /*top_desk_logo_asset_path*/"GY", /*text*/"k.member_guild_board_209", /*ranking_open_text*/"k.member_guild_board_01_209", /*ranking_end_text*/"k.member_guild_board_02_209", /*trade_m_id*/50209, /*start_at*/1617008400);
INSERT INTO `m_member_guild` VALUES (/*member_master_id*/210, /*name*/"k.member_guild_name_210", /*logo_asset_path*/"?bz", /*top_background_asset_path*/"8qE", /*top_graffiti_asset_path*/",Fx", /*top_desk_asset_path*/"aCU", /*top_desk_logo_asset_path*/"GY", /*text*/"k.member_guild_board_210", /*ranking_open_text*/"k.member_guild_board_01_210", /*ranking_end_text*/"k.member_guild_board_02_210", /*trade_m_id*/50210, /*start_at*/1617008400);
