CREATE TABLE m_member_guild_ranking_reward_outside(
  id INTEGER NOT NULL,
  member_master_id INTEGER NOT NULL,
  upper_rank INTEGER NOT NULL,
  lower_rank INTEGER,
  rank_grade INTEGER NOT NULL,
  content_type INTEGER NOT NULL,
  content_id INTEGER NOT NULL,
  content_amount INTEGER NOT NULL,
  PRIMARY KEY (id, member_master_id, upper_rank, content_type, content_id),
  FOREIGN KEY (member_master_id) REFERENCES m_member(id)
);
INSERT INTO `m_member_guild_ranking_reward_outside` VALUES (/*id*/1, /*member_master_id*/1, /*upper_rank*/1, /*lower_rank*/1, /*rank_grade*/1, /*content_type*/21, /*content_id*/50001, /*content_amount*/100);
INSERT INTO `m_member_guild_ranking_reward_outside` VALUES (/*id*/1, /*member_master_id*/1, /*upper_rank*/2, /*lower_rank*/3, /*rank_grade*/2, /*content_type*/21, /*content_id*/50001, /*content_amount*/50);
INSERT INTO `m_member_guild_ranking_reward_outside` VALUES (/*id*/1, /*member_master_id*/1, /*upper_rank*/4, /*lower_rank*/5, /*rank_grade*/2, /*content_type*/21, /*content_id*/50001, /*content_amount*/30);
INSERT INTO `m_member_guild_ranking_reward_outside` VALUES (/*id*/1, /*member_master_id*/1, /*upper_rank*/6, /*lower_rank*/"", /*rank_grade*/3, /*content_type*/21, /*content_id*/50001, /*content_amount*/10);
INSERT INTO `m_member_guild_ranking_reward_outside` VALUES (/*id*/1, /*member_master_id*/2, /*upper_rank*/1, /*lower_rank*/1, /*rank_grade*/1, /*content_type*/21, /*content_id*/50002, /*content_amount*/100);
INSERT INTO `m_member_guild_ranking_reward_outside` VALUES (/*id*/1, /*member_master_id*/2, /*upper_rank*/2, /*lower_rank*/3, /*rank_grade*/2, /*content_type*/21, /*content_id*/50002, /*content_amount*/50);
INSERT INTO `m_member_guild_ranking_reward_outside` VALUES (/*id*/1, /*member_master_id*/2, /*upper_rank*/4, /*lower_rank*/5, /*rank_grade*/2, /*content_type*/21, /*content_id*/50002, /*content_amount*/30);
INSERT INTO `m_member_guild_ranking_reward_outside` VALUES (/*id*/1, /*member_master_id*/2, /*upper_rank*/6, /*lower_rank*/"", /*rank_grade*/3, /*content_type*/21, /*content_id*/50002, /*content_amount*/10);
INSERT INTO `m_member_guild_ranking_reward_outside` VALUES (/*id*/1, /*member_master_id*/3, /*upper_rank*/1, /*lower_rank*/1, /*rank_grade*/1, /*content_type*/21, /*content_id*/50003, /*content_amount*/100);
INSERT INTO `m_member_guild_ranking_reward_outside` VALUES (/*id*/1, /*member_master_id*/3, /*upper_rank*/2, /*lower_rank*/3, /*rank_grade*/2, /*content_type*/21, /*content_id*/50003, /*content_amount*/50);
INSERT INTO `m_member_guild_ranking_reward_outside` VALUES (/*id*/1, /*member_master_id*/3, /*upper_rank*/4, /*lower_rank*/5, /*rank_grade*/2, /*content_type*/21, /*content_id*/50003, /*content_amount*/30);
INSERT INTO `m_member_guild_ranking_reward_outside` VALUES (/*id*/1, /*member_master_id*/3, /*upper_rank*/6, /*lower_rank*/"", /*rank_grade*/3, /*content_type*/21, /*content_id*/50003, /*content_amount*/10);
INSERT INTO `m_member_guild_ranking_reward_outside` VALUES (/*id*/1, /*member_master_id*/4, /*upper_rank*/1, /*lower_rank*/1, /*rank_grade*/1, /*content_type*/21, /*content_id*/50004, /*content_amount*/100);
INSERT INTO `m_member_guild_ranking_reward_outside` VALUES (/*id*/1, /*member_master_id*/4, /*upper_rank*/2, /*lower_rank*/3, /*rank_grade*/2, /*content_type*/21, /*content_id*/50004, /*content_amount*/50);
INSERT INTO `m_member_guild_ranking_reward_outside` VALUES (/*id*/1, /*member_master_id*/4, /*upper_rank*/4, /*lower_rank*/5, /*rank_grade*/2, /*content_type*/21, /*content_id*/50004, /*content_amount*/30);
INSERT INTO `m_member_guild_ranking_reward_outside` VALUES (/*id*/1, /*member_master_id*/4, /*upper_rank*/6, /*lower_rank*/"", /*rank_grade*/3, /*content_type*/21, /*content_id*/50004, /*content_amount*/10);
INSERT INTO `m_member_guild_ranking_reward_outside` VALUES (/*id*/1, /*member_master_id*/5, /*upper_rank*/1, /*lower_rank*/1, /*rank_grade*/1, /*content_type*/21, /*content_id*/50005, /*content_amount*/100);
INSERT INTO `m_member_guild_ranking_reward_outside` VALUES (/*id*/1, /*member_master_id*/5, /*upper_rank*/2, /*lower_rank*/3, /*rank_grade*/2, /*content_type*/21, /*content_id*/50005, /*content_amount*/50);
INSERT INTO `m_member_guild_ranking_reward_outside` VALUES (/*id*/1, /*member_master_id*/5, /*upper_rank*/4, /*lower_rank*/5, /*rank_grade*/2, /*content_type*/21, /*content_id*/50005, /*content_amount*/30);
INSERT INTO `m_member_guild_ranking_reward_outside` VALUES (/*id*/1, /*member_master_id*/5, /*upper_rank*/6, /*lower_rank*/"", /*rank_grade*/3, /*content_type*/21, /*content_id*/50005, /*content_amount*/10);
INSERT INTO `m_member_guild_ranking_reward_outside` VALUES (/*id*/1, /*member_master_id*/6, /*upper_rank*/1, /*lower_rank*/1, /*rank_grade*/1, /*content_type*/21, /*content_id*/50006, /*content_amount*/100);
INSERT INTO `m_member_guild_ranking_reward_outside` VALUES (/*id*/1, /*member_master_id*/6, /*upper_rank*/2, /*lower_rank*/3, /*rank_grade*/2, /*content_type*/21, /*content_id*/50006, /*content_amount*/50);
INSERT INTO `m_member_guild_ranking_reward_outside` VALUES (/*id*/1, /*member_master_id*/6, /*upper_rank*/4, /*lower_rank*/5, /*rank_grade*/2, /*content_type*/21, /*content_id*/50006, /*content_amount*/30);
INSERT INTO `m_member_guild_ranking_reward_outside` VALUES (/*id*/1, /*member_master_id*/6, /*upper_rank*/6, /*lower_rank*/"", /*rank_grade*/3, /*content_type*/21, /*content_id*/50006, /*content_amount*/10);
INSERT INTO `m_member_guild_ranking_reward_outside` VALUES (/*id*/1, /*member_master_id*/7, /*upper_rank*/1, /*lower_rank*/1, /*rank_grade*/1, /*content_type*/21, /*content_id*/50007, /*content_amount*/100);
INSERT INTO `m_member_guild_ranking_reward_outside` VALUES (/*id*/1, /*member_master_id*/7, /*upper_rank*/2, /*lower_rank*/3, /*rank_grade*/2, /*content_type*/21, /*content_id*/50007, /*content_amount*/50);
INSERT INTO `m_member_guild_ranking_reward_outside` VALUES (/*id*/1, /*member_master_id*/7, /*upper_rank*/4, /*lower_rank*/5, /*rank_grade*/2, /*content_type*/21, /*content_id*/50007, /*content_amount*/30);
INSERT INTO `m_member_guild_ranking_reward_outside` VALUES (/*id*/1, /*member_master_id*/7, /*upper_rank*/6, /*lower_rank*/"", /*rank_grade*/3, /*content_type*/21, /*content_id*/50007, /*content_amount*/10);
INSERT INTO `m_member_guild_ranking_reward_outside` VALUES (/*id*/1, /*member_master_id*/8, /*upper_rank*/1, /*lower_rank*/1, /*rank_grade*/1, /*content_type*/21, /*content_id*/50008, /*content_amount*/100);
INSERT INTO `m_member_guild_ranking_reward_outside` VALUES (/*id*/1, /*member_master_id*/8, /*upper_rank*/2, /*lower_rank*/3, /*rank_grade*/2, /*content_type*/21, /*content_id*/50008, /*content_amount*/50);
INSERT INTO `m_member_guild_ranking_reward_outside` VALUES (/*id*/1, /*member_master_id*/8, /*upper_rank*/4, /*lower_rank*/5, /*rank_grade*/2, /*content_type*/21, /*content_id*/50008, /*content_amount*/30);
INSERT INTO `m_member_guild_ranking_reward_outside` VALUES (/*id*/1, /*member_master_id*/8, /*upper_rank*/6, /*lower_rank*/"", /*rank_grade*/3, /*content_type*/21, /*content_id*/50008, /*content_amount*/10);
INSERT INTO `m_member_guild_ranking_reward_outside` VALUES (/*id*/1, /*member_master_id*/9, /*upper_rank*/1, /*lower_rank*/1, /*rank_grade*/1, /*content_type*/21, /*content_id*/50009, /*content_amount*/100);
INSERT INTO `m_member_guild_ranking_reward_outside` VALUES (/*id*/1, /*member_master_id*/9, /*upper_rank*/2, /*lower_rank*/3, /*rank_grade*/2, /*content_type*/21, /*content_id*/50009, /*content_amount*/50);
INSERT INTO `m_member_guild_ranking_reward_outside` VALUES (/*id*/1, /*member_master_id*/9, /*upper_rank*/4, /*lower_rank*/5, /*rank_grade*/2, /*content_type*/21, /*content_id*/50009, /*content_amount*/30);
INSERT INTO `m_member_guild_ranking_reward_outside` VALUES (/*id*/1, /*member_master_id*/9, /*upper_rank*/6, /*lower_rank*/"", /*rank_grade*/3, /*content_type*/21, /*content_id*/50009, /*content_amount*/10);
INSERT INTO `m_member_guild_ranking_reward_outside` VALUES (/*id*/1, /*member_master_id*/101, /*upper_rank*/1, /*lower_rank*/1, /*rank_grade*/1, /*content_type*/21, /*content_id*/50101, /*content_amount*/100);
INSERT INTO `m_member_guild_ranking_reward_outside` VALUES (/*id*/1, /*member_master_id*/101, /*upper_rank*/2, /*lower_rank*/3, /*rank_grade*/2, /*content_type*/21, /*content_id*/50101, /*content_amount*/50);
INSERT INTO `m_member_guild_ranking_reward_outside` VALUES (/*id*/1, /*member_master_id*/101, /*upper_rank*/4, /*lower_rank*/5, /*rank_grade*/2, /*content_type*/21, /*content_id*/50101, /*content_amount*/30);
INSERT INTO `m_member_guild_ranking_reward_outside` VALUES (/*id*/1, /*member_master_id*/101, /*upper_rank*/6, /*lower_rank*/"", /*rank_grade*/3, /*content_type*/21, /*content_id*/50101, /*content_amount*/10);
INSERT INTO `m_member_guild_ranking_reward_outside` VALUES (/*id*/1, /*member_master_id*/102, /*upper_rank*/1, /*lower_rank*/1, /*rank_grade*/1, /*content_type*/21, /*content_id*/50102, /*content_amount*/100);
INSERT INTO `m_member_guild_ranking_reward_outside` VALUES (/*id*/1, /*member_master_id*/102, /*upper_rank*/2, /*lower_rank*/3, /*rank_grade*/2, /*content_type*/21, /*content_id*/50102, /*content_amount*/50);
INSERT INTO `m_member_guild_ranking_reward_outside` VALUES (/*id*/1, /*member_master_id*/102, /*upper_rank*/4, /*lower_rank*/5, /*rank_grade*/2, /*content_type*/21, /*content_id*/50102, /*content_amount*/30);
INSERT INTO `m_member_guild_ranking_reward_outside` VALUES (/*id*/1, /*member_master_id*/102, /*upper_rank*/6, /*lower_rank*/"", /*rank_grade*/3, /*content_type*/21, /*content_id*/50102, /*content_amount*/10);
INSERT INTO `m_member_guild_ranking_reward_outside` VALUES (/*id*/1, /*member_master_id*/103, /*upper_rank*/1, /*lower_rank*/1, /*rank_grade*/1, /*content_type*/21, /*content_id*/50103, /*content_amount*/100);
INSERT INTO `m_member_guild_ranking_reward_outside` VALUES (/*id*/1, /*member_master_id*/103, /*upper_rank*/2, /*lower_rank*/3, /*rank_grade*/2, /*content_type*/21, /*content_id*/50103, /*content_amount*/50);
INSERT INTO `m_member_guild_ranking_reward_outside` VALUES (/*id*/1, /*member_master_id*/103, /*upper_rank*/4, /*lower_rank*/5, /*rank_grade*/2, /*content_type*/21, /*content_id*/50103, /*content_amount*/30);
INSERT INTO `m_member_guild_ranking_reward_outside` VALUES (/*id*/1, /*member_master_id*/103, /*upper_rank*/6, /*lower_rank*/"", /*rank_grade*/3, /*content_type*/21, /*content_id*/50103, /*content_amount*/10);
INSERT INTO `m_member_guild_ranking_reward_outside` VALUES (/*id*/1, /*member_master_id*/104, /*upper_rank*/1, /*lower_rank*/1, /*rank_grade*/1, /*content_type*/21, /*content_id*/50104, /*content_amount*/100);
INSERT INTO `m_member_guild_ranking_reward_outside` VALUES (/*id*/1, /*member_master_id*/104, /*upper_rank*/2, /*lower_rank*/3, /*rank_grade*/2, /*content_type*/21, /*content_id*/50104, /*content_amount*/50);
INSERT INTO `m_member_guild_ranking_reward_outside` VALUES (/*id*/1, /*member_master_id*/104, /*upper_rank*/4, /*lower_rank*/5, /*rank_grade*/2, /*content_type*/21, /*content_id*/50104, /*content_amount*/30);
INSERT INTO `m_member_guild_ranking_reward_outside` VALUES (/*id*/1, /*member_master_id*/104, /*upper_rank*/6, /*lower_rank*/"", /*rank_grade*/3, /*content_type*/21, /*content_id*/50104, /*content_amount*/10);
INSERT INTO `m_member_guild_ranking_reward_outside` VALUES (/*id*/1, /*member_master_id*/105, /*upper_rank*/1, /*lower_rank*/1, /*rank_grade*/1, /*content_type*/21, /*content_id*/50105, /*content_amount*/100);
INSERT INTO `m_member_guild_ranking_reward_outside` VALUES (/*id*/1, /*member_master_id*/105, /*upper_rank*/2, /*lower_rank*/3, /*rank_grade*/2, /*content_type*/21, /*content_id*/50105, /*content_amount*/50);
INSERT INTO `m_member_guild_ranking_reward_outside` VALUES (/*id*/1, /*member_master_id*/105, /*upper_rank*/4, /*lower_rank*/5, /*rank_grade*/2, /*content_type*/21, /*content_id*/50105, /*content_amount*/30);
INSERT INTO `m_member_guild_ranking_reward_outside` VALUES (/*id*/1, /*member_master_id*/105, /*upper_rank*/6, /*lower_rank*/"", /*rank_grade*/3, /*content_type*/21, /*content_id*/50105, /*content_amount*/10);
INSERT INTO `m_member_guild_ranking_reward_outside` VALUES (/*id*/1, /*member_master_id*/106, /*upper_rank*/1, /*lower_rank*/1, /*rank_grade*/1, /*content_type*/21, /*content_id*/50106, /*content_amount*/100);
INSERT INTO `m_member_guild_ranking_reward_outside` VALUES (/*id*/1, /*member_master_id*/106, /*upper_rank*/2, /*lower_rank*/3, /*rank_grade*/2, /*content_type*/21, /*content_id*/50106, /*content_amount*/50);
INSERT INTO `m_member_guild_ranking_reward_outside` VALUES (/*id*/1, /*member_master_id*/106, /*upper_rank*/4, /*lower_rank*/5, /*rank_grade*/2, /*content_type*/21, /*content_id*/50106, /*content_amount*/30);
INSERT INTO `m_member_guild_ranking_reward_outside` VALUES (/*id*/1, /*member_master_id*/106, /*upper_rank*/6, /*lower_rank*/"", /*rank_grade*/3, /*content_type*/21, /*content_id*/50106, /*content_amount*/10);
INSERT INTO `m_member_guild_ranking_reward_outside` VALUES (/*id*/1, /*member_master_id*/107, /*upper_rank*/1, /*lower_rank*/1, /*rank_grade*/1, /*content_type*/21, /*content_id*/50107, /*content_amount*/100);
INSERT INTO `m_member_guild_ranking_reward_outside` VALUES (/*id*/1, /*member_master_id*/107, /*upper_rank*/2, /*lower_rank*/3, /*rank_grade*/2, /*content_type*/21, /*content_id*/50107, /*content_amount*/50);
INSERT INTO `m_member_guild_ranking_reward_outside` VALUES (/*id*/1, /*member_master_id*/107, /*upper_rank*/4, /*lower_rank*/5, /*rank_grade*/2, /*content_type*/21, /*content_id*/50107, /*content_amount*/30);
INSERT INTO `m_member_guild_ranking_reward_outside` VALUES (/*id*/1, /*member_master_id*/107, /*upper_rank*/6, /*lower_rank*/"", /*rank_grade*/3, /*content_type*/21, /*content_id*/50107, /*content_amount*/10);
INSERT INTO `m_member_guild_ranking_reward_outside` VALUES (/*id*/1, /*member_master_id*/108, /*upper_rank*/1, /*lower_rank*/1, /*rank_grade*/1, /*content_type*/21, /*content_id*/50108, /*content_amount*/100);
INSERT INTO `m_member_guild_ranking_reward_outside` VALUES (/*id*/1, /*member_master_id*/108, /*upper_rank*/2, /*lower_rank*/3, /*rank_grade*/2, /*content_type*/21, /*content_id*/50108, /*content_amount*/50);
INSERT INTO `m_member_guild_ranking_reward_outside` VALUES (/*id*/1, /*member_master_id*/108, /*upper_rank*/4, /*lower_rank*/5, /*rank_grade*/2, /*content_type*/21, /*content_id*/50108, /*content_amount*/30);
INSERT INTO `m_member_guild_ranking_reward_outside` VALUES (/*id*/1, /*member_master_id*/108, /*upper_rank*/6, /*lower_rank*/"", /*rank_grade*/3, /*content_type*/21, /*content_id*/50108, /*content_amount*/10);
INSERT INTO `m_member_guild_ranking_reward_outside` VALUES (/*id*/1, /*member_master_id*/109, /*upper_rank*/1, /*lower_rank*/1, /*rank_grade*/1, /*content_type*/21, /*content_id*/50109, /*content_amount*/100);
INSERT INTO `m_member_guild_ranking_reward_outside` VALUES (/*id*/1, /*member_master_id*/109, /*upper_rank*/2, /*lower_rank*/3, /*rank_grade*/2, /*content_type*/21, /*content_id*/50109, /*content_amount*/50);
INSERT INTO `m_member_guild_ranking_reward_outside` VALUES (/*id*/1, /*member_master_id*/109, /*upper_rank*/4, /*lower_rank*/5, /*rank_grade*/2, /*content_type*/21, /*content_id*/50109, /*content_amount*/30);
INSERT INTO `m_member_guild_ranking_reward_outside` VALUES (/*id*/1, /*member_master_id*/109, /*upper_rank*/6, /*lower_rank*/"", /*rank_grade*/3, /*content_type*/21, /*content_id*/50109, /*content_amount*/10);
INSERT INTO `m_member_guild_ranking_reward_outside` VALUES (/*id*/1, /*member_master_id*/201, /*upper_rank*/1, /*lower_rank*/1, /*rank_grade*/1, /*content_type*/21, /*content_id*/50201, /*content_amount*/100);
INSERT INTO `m_member_guild_ranking_reward_outside` VALUES (/*id*/1, /*member_master_id*/201, /*upper_rank*/2, /*lower_rank*/3, /*rank_grade*/2, /*content_type*/21, /*content_id*/50201, /*content_amount*/50);
INSERT INTO `m_member_guild_ranking_reward_outside` VALUES (/*id*/1, /*member_master_id*/201, /*upper_rank*/4, /*lower_rank*/5, /*rank_grade*/2, /*content_type*/21, /*content_id*/50201, /*content_amount*/30);
INSERT INTO `m_member_guild_ranking_reward_outside` VALUES (/*id*/1, /*member_master_id*/201, /*upper_rank*/6, /*lower_rank*/"", /*rank_grade*/3, /*content_type*/21, /*content_id*/50201, /*content_amount*/10);
INSERT INTO `m_member_guild_ranking_reward_outside` VALUES (/*id*/1, /*member_master_id*/202, /*upper_rank*/1, /*lower_rank*/1, /*rank_grade*/1, /*content_type*/21, /*content_id*/50202, /*content_amount*/100);
INSERT INTO `m_member_guild_ranking_reward_outside` VALUES (/*id*/1, /*member_master_id*/202, /*upper_rank*/2, /*lower_rank*/3, /*rank_grade*/2, /*content_type*/21, /*content_id*/50202, /*content_amount*/50);
INSERT INTO `m_member_guild_ranking_reward_outside` VALUES (/*id*/1, /*member_master_id*/202, /*upper_rank*/4, /*lower_rank*/5, /*rank_grade*/2, /*content_type*/21, /*content_id*/50202, /*content_amount*/30);
INSERT INTO `m_member_guild_ranking_reward_outside` VALUES (/*id*/1, /*member_master_id*/202, /*upper_rank*/6, /*lower_rank*/"", /*rank_grade*/3, /*content_type*/21, /*content_id*/50202, /*content_amount*/10);
INSERT INTO `m_member_guild_ranking_reward_outside` VALUES (/*id*/1, /*member_master_id*/203, /*upper_rank*/1, /*lower_rank*/1, /*rank_grade*/1, /*content_type*/21, /*content_id*/50203, /*content_amount*/100);
INSERT INTO `m_member_guild_ranking_reward_outside` VALUES (/*id*/1, /*member_master_id*/203, /*upper_rank*/2, /*lower_rank*/3, /*rank_grade*/2, /*content_type*/21, /*content_id*/50203, /*content_amount*/50);
INSERT INTO `m_member_guild_ranking_reward_outside` VALUES (/*id*/1, /*member_master_id*/203, /*upper_rank*/4, /*lower_rank*/5, /*rank_grade*/2, /*content_type*/21, /*content_id*/50203, /*content_amount*/30);
INSERT INTO `m_member_guild_ranking_reward_outside` VALUES (/*id*/1, /*member_master_id*/203, /*upper_rank*/6, /*lower_rank*/"", /*rank_grade*/3, /*content_type*/21, /*content_id*/50203, /*content_amount*/10);
INSERT INTO `m_member_guild_ranking_reward_outside` VALUES (/*id*/1, /*member_master_id*/204, /*upper_rank*/1, /*lower_rank*/1, /*rank_grade*/1, /*content_type*/21, /*content_id*/50204, /*content_amount*/100);
INSERT INTO `m_member_guild_ranking_reward_outside` VALUES (/*id*/1, /*member_master_id*/204, /*upper_rank*/2, /*lower_rank*/3, /*rank_grade*/2, /*content_type*/21, /*content_id*/50204, /*content_amount*/50);
INSERT INTO `m_member_guild_ranking_reward_outside` VALUES (/*id*/1, /*member_master_id*/204, /*upper_rank*/4, /*lower_rank*/5, /*rank_grade*/2, /*content_type*/21, /*content_id*/50204, /*content_amount*/30);
INSERT INTO `m_member_guild_ranking_reward_outside` VALUES (/*id*/1, /*member_master_id*/204, /*upper_rank*/6, /*lower_rank*/"", /*rank_grade*/3, /*content_type*/21, /*content_id*/50204, /*content_amount*/10);
INSERT INTO `m_member_guild_ranking_reward_outside` VALUES (/*id*/1, /*member_master_id*/205, /*upper_rank*/1, /*lower_rank*/1, /*rank_grade*/1, /*content_type*/21, /*content_id*/50205, /*content_amount*/100);
INSERT INTO `m_member_guild_ranking_reward_outside` VALUES (/*id*/1, /*member_master_id*/205, /*upper_rank*/2, /*lower_rank*/3, /*rank_grade*/2, /*content_type*/21, /*content_id*/50205, /*content_amount*/50);
INSERT INTO `m_member_guild_ranking_reward_outside` VALUES (/*id*/1, /*member_master_id*/205, /*upper_rank*/4, /*lower_rank*/5, /*rank_grade*/2, /*content_type*/21, /*content_id*/50205, /*content_amount*/30);
INSERT INTO `m_member_guild_ranking_reward_outside` VALUES (/*id*/1, /*member_master_id*/205, /*upper_rank*/6, /*lower_rank*/"", /*rank_grade*/3, /*content_type*/21, /*content_id*/50205, /*content_amount*/10);
INSERT INTO `m_member_guild_ranking_reward_outside` VALUES (/*id*/1, /*member_master_id*/206, /*upper_rank*/1, /*lower_rank*/1, /*rank_grade*/1, /*content_type*/21, /*content_id*/50206, /*content_amount*/100);
INSERT INTO `m_member_guild_ranking_reward_outside` VALUES (/*id*/1, /*member_master_id*/206, /*upper_rank*/2, /*lower_rank*/3, /*rank_grade*/2, /*content_type*/21, /*content_id*/50206, /*content_amount*/50);
INSERT INTO `m_member_guild_ranking_reward_outside` VALUES (/*id*/1, /*member_master_id*/206, /*upper_rank*/4, /*lower_rank*/5, /*rank_grade*/2, /*content_type*/21, /*content_id*/50206, /*content_amount*/30);
INSERT INTO `m_member_guild_ranking_reward_outside` VALUES (/*id*/1, /*member_master_id*/206, /*upper_rank*/6, /*lower_rank*/"", /*rank_grade*/3, /*content_type*/21, /*content_id*/50206, /*content_amount*/10);
INSERT INTO `m_member_guild_ranking_reward_outside` VALUES (/*id*/1, /*member_master_id*/207, /*upper_rank*/1, /*lower_rank*/1, /*rank_grade*/1, /*content_type*/21, /*content_id*/50207, /*content_amount*/100);
INSERT INTO `m_member_guild_ranking_reward_outside` VALUES (/*id*/1, /*member_master_id*/207, /*upper_rank*/2, /*lower_rank*/3, /*rank_grade*/2, /*content_type*/21, /*content_id*/50207, /*content_amount*/50);
INSERT INTO `m_member_guild_ranking_reward_outside` VALUES (/*id*/1, /*member_master_id*/207, /*upper_rank*/4, /*lower_rank*/5, /*rank_grade*/2, /*content_type*/21, /*content_id*/50207, /*content_amount*/30);
INSERT INTO `m_member_guild_ranking_reward_outside` VALUES (/*id*/1, /*member_master_id*/207, /*upper_rank*/6, /*lower_rank*/"", /*rank_grade*/3, /*content_type*/21, /*content_id*/50207, /*content_amount*/10);
INSERT INTO `m_member_guild_ranking_reward_outside` VALUES (/*id*/1, /*member_master_id*/208, /*upper_rank*/1, /*lower_rank*/1, /*rank_grade*/1, /*content_type*/21, /*content_id*/50208, /*content_amount*/100);
INSERT INTO `m_member_guild_ranking_reward_outside` VALUES (/*id*/1, /*member_master_id*/208, /*upper_rank*/2, /*lower_rank*/3, /*rank_grade*/2, /*content_type*/21, /*content_id*/50208, /*content_amount*/50);
INSERT INTO `m_member_guild_ranking_reward_outside` VALUES (/*id*/1, /*member_master_id*/208, /*upper_rank*/4, /*lower_rank*/5, /*rank_grade*/2, /*content_type*/21, /*content_id*/50208, /*content_amount*/30);
INSERT INTO `m_member_guild_ranking_reward_outside` VALUES (/*id*/1, /*member_master_id*/208, /*upper_rank*/6, /*lower_rank*/"", /*rank_grade*/3, /*content_type*/21, /*content_id*/50208, /*content_amount*/10);
INSERT INTO `m_member_guild_ranking_reward_outside` VALUES (/*id*/1, /*member_master_id*/209, /*upper_rank*/1, /*lower_rank*/1, /*rank_grade*/1, /*content_type*/21, /*content_id*/50209, /*content_amount*/100);
INSERT INTO `m_member_guild_ranking_reward_outside` VALUES (/*id*/1, /*member_master_id*/209, /*upper_rank*/2, /*lower_rank*/3, /*rank_grade*/2, /*content_type*/21, /*content_id*/50209, /*content_amount*/50);
INSERT INTO `m_member_guild_ranking_reward_outside` VALUES (/*id*/1, /*member_master_id*/209, /*upper_rank*/4, /*lower_rank*/5, /*rank_grade*/2, /*content_type*/21, /*content_id*/50209, /*content_amount*/30);
INSERT INTO `m_member_guild_ranking_reward_outside` VALUES (/*id*/1, /*member_master_id*/209, /*upper_rank*/6, /*lower_rank*/"", /*rank_grade*/3, /*content_type*/21, /*content_id*/50209, /*content_amount*/10);
INSERT INTO `m_member_guild_ranking_reward_outside` VALUES (/*id*/1, /*member_master_id*/210, /*upper_rank*/1, /*lower_rank*/1, /*rank_grade*/1, /*content_type*/21, /*content_id*/50210, /*content_amount*/100);
INSERT INTO `m_member_guild_ranking_reward_outside` VALUES (/*id*/1, /*member_master_id*/210, /*upper_rank*/2, /*lower_rank*/3, /*rank_grade*/2, /*content_type*/21, /*content_id*/50210, /*content_amount*/50);
INSERT INTO `m_member_guild_ranking_reward_outside` VALUES (/*id*/1, /*member_master_id*/210, /*upper_rank*/4, /*lower_rank*/5, /*rank_grade*/2, /*content_type*/21, /*content_id*/50210, /*content_amount*/30);
INSERT INTO `m_member_guild_ranking_reward_outside` VALUES (/*id*/1, /*member_master_id*/210, /*upper_rank*/6, /*lower_rank*/"", /*rank_grade*/3, /*content_type*/21, /*content_id*/50210, /*content_amount*/10);
