CREATE TABLE m_member_love_panel_effect_type_setting(
  member_love_panel_effect_type INTEGER NOT NULL,
  name TEXT NOT NULL,
  cell_name TEXT NOT NULL,
  list_value_text_prefix TEXT,
  icon_color_top INTEGER NOT NULL,
  icon_color_bottom INTEGER NOT NULL,
  text_color INTEGER NOT NULL,
  is_percent INTEGER NOT NULL,
  is_parameter INTEGER NOT NULL,
  unit TEXT NOT NULL,
  list_unit_zero TEXT NOT NULL,
  list_panel_text TEXT,
  list_sum_text TEXT,
  card_rarity INTEGER,
  is_squad INTEGER NOT NULL,
  display_order INTEGER NOT NULL,
  PRIMARY KEY (member_love_panel_effect_type)
);
INSERT INTO `m_member_love_panel_effect_type_setting` VALUES (/*member_love_panel_effect_type*/1, /*name*/"k.m_member_love_panel_effect_type_setting_appeal", /*cell_name*/"k.m_member_love_panel_effect_type_setting_appeal_cell_name", /*list_value_text_prefix*/"", /*icon_color_top*/-159339777, /*icon_color_bottom*/-159339777, /*text_color*/-159339777, /*is_percent*/1, /*is_parameter*/1, /*unit*/"k.m_member_love_panel_effect_type_setting_unit_percent", /*list_unit_zero*/"k.m_member_love_panel_effect_type_setting_unit_zero", /*list_panel_text*/"", /*list_sum_text*/"", /*card_rarity*/"", /*is_squad*/0, /*display_order*/1);
INSERT INTO `m_member_love_panel_effect_type_setting` VALUES (/*member_love_panel_effect_type*/2, /*name*/"k.m_member_love_panel_effect_type_setting_stamina", /*cell_name*/"k.m_member_love_panel_effect_type_setting_stamina_cell_name", /*list_value_text_prefix*/"", /*icon_color_top*/1724674815, /*icon_color_bottom*/1724674815, /*text_color*/1724674815, /*is_percent*/1, /*is_parameter*/1, /*unit*/"k.m_member_love_panel_effect_type_setting_unit_percent", /*list_unit_zero*/"k.m_member_love_panel_effect_type_setting_unit_zero", /*list_panel_text*/"", /*list_sum_text*/"", /*card_rarity*/"", /*is_squad*/0, /*display_order*/2);
INSERT INTO `m_member_love_panel_effect_type_setting` VALUES (/*member_love_panel_effect_type*/3, /*name*/"k.m_member_love_panel_effect_type_setting_technique", /*cell_name*/"k.m_member_love_panel_effect_type_setting_technique_cell_name", /*list_value_text_prefix*/"", /*icon_color_top*/-87734017, /*icon_color_bottom*/-87734017, /*text_color*/-357487873, /*is_percent*/1, /*is_parameter*/1, /*unit*/"k.m_member_love_panel_effect_type_setting_unit_percent", /*list_unit_zero*/"k.m_member_love_panel_effect_type_setting_unit_zero", /*list_panel_text*/"", /*list_sum_text*/"", /*card_rarity*/"", /*is_squad*/0, /*display_order*/3);
INSERT INTO `m_member_love_panel_effect_type_setting` VALUES (/*member_love_panel_effect_type*/4, /*name*/"k.m_member_love_panel_effect_type_setting_critical_rate", /*cell_name*/"k.m_member_love_panel_effect_type_setting_critical_rate_cell_name", /*list_value_text_prefix*/"k.m_member_love_panel_effect_type_setting_critical_rate_list_value_text_prefix", /*icon_color_top*/1941239807, /*icon_color_bottom*/1941239807, /*text_color*/1100542719, /*is_percent*/1, /*is_parameter*/0, /*unit*/"k.m_member_love_panel_effect_type_setting_unit_percent", /*list_unit_zero*/"k.m_member_love_panel_effect_type_setting_unit_zero", /*list_panel_text*/"", /*list_sum_text*/"k.m_member_love_panel_effect_type_setting_critical_rate_list_sum_text", /*card_rarity*/"", /*is_squad*/0, /*display_order*/4);
INSERT INTO `m_member_love_panel_effect_type_setting` VALUES (/*member_love_panel_effect_type*/5, /*name*/"k.m_member_love_panel_effect_type_setting_critical_value", /*cell_name*/"k.m_member_love_panel_effect_type_setting_critical_value_cell_name", /*list_value_text_prefix*/"k.m_member_love_panel_effect_type_setting_critical_value_list_value_text_prefix", /*icon_color_top*/1100542719, /*icon_color_bottom*/1100542719, /*text_color*/730062591, /*is_percent*/1, /*is_parameter*/0, /*unit*/"k.m_member_love_panel_effect_type_setting_unit_percent", /*list_unit_zero*/"k.m_member_love_panel_effect_type_setting_unit_zero", /*list_panel_text*/"", /*list_sum_text*/"k.m_member_love_panel_effect_type_setting_critical_value_list_sum_text", /*card_rarity*/"", /*is_squad*/0, /*display_order*/5);
INSERT INTO `m_member_love_panel_effect_type_setting` VALUES (/*member_love_panel_effect_type*/6, /*name*/"k.m_member_love_panel_effect_type_setting_sp_gauge", /*cell_name*/"k.m_member_love_panel_effect_type_setting_sp_gauge_cell_name", /*list_value_text_prefix*/"", /*icon_color_top*/-2099714305, /*icon_color_bottom*/-2099714305, /*text_color*/1354550783, /*is_percent*/1, /*is_parameter*/0, /*unit*/"k.m_member_love_panel_effect_type_setting_unit_percent", /*list_unit_zero*/"k.m_member_love_panel_effect_type_setting_unit_zero", /*list_panel_text*/"", /*list_sum_text*/"", /*card_rarity*/"", /*is_squad*/0, /*display_order*/6);
INSERT INTO `m_member_love_panel_effect_type_setting` VALUES (/*member_love_panel_effect_type*/7, /*name*/"k.m_member_love_panel_effect_type_setting_sp_boost", /*cell_name*/"k.m_member_love_panel_effect_type_setting_sp_boost_cell_name", /*list_value_text_prefix*/"", /*icon_color_top*/-393139457, /*icon_color_bottom*/-393139457, /*text_color*/-393139457, /*is_percent*/1, /*is_parameter*/0, /*unit*/"k.m_member_love_panel_effect_type_setting_unit_percent", /*list_unit_zero*/"k.m_member_love_panel_effect_type_setting_unit_zero", /*list_panel_text*/"", /*list_sum_text*/"", /*card_rarity*/"", /*is_squad*/0, /*display_order*/7);
INSERT INTO `m_member_love_panel_effect_type_setting` VALUES (/*member_love_panel_effect_type*/8, /*name*/"k.m_member_love_panel_effect_type_setting_boost_type", /*cell_name*/"k.m_member_love_panel_effect_type_setting_boost_type_cell_name", /*list_value_text_prefix*/"", /*icon_color_top*/-817873409, /*icon_color_bottom*/-817873409, /*text_color*/-817873409, /*is_percent*/1, /*is_parameter*/0, /*unit*/"k.m_member_love_panel_effect_type_setting_unit_percent", /*list_unit_zero*/"k.m_member_love_panel_effect_type_setting_unit_zero", /*list_panel_text*/"", /*list_sum_text*/"", /*card_rarity*/"", /*is_squad*/1, /*display_order*/8);
INSERT INTO `m_member_love_panel_effect_type_setting` VALUES (/*member_love_panel_effect_type*/9, /*name*/"k.m_member_love_panel_effect_type_setting_charge_type", /*cell_name*/"k.m_member_love_panel_effect_type_setting_charge_type_cell_name", /*list_value_text_prefix*/"", /*icon_color_top*/596232447, /*icon_color_bottom*/596232447, /*text_color*/596232703, /*is_percent*/1, /*is_parameter*/0, /*unit*/"k.m_member_love_panel_effect_type_setting_unit_percent", /*list_unit_zero*/"k.m_member_love_panel_effect_type_setting_unit_zero", /*list_panel_text*/"", /*list_sum_text*/"", /*card_rarity*/"", /*is_squad*/1, /*display_order*/9);
INSERT INTO `m_member_love_panel_effect_type_setting` VALUES (/*member_love_panel_effect_type*/10, /*name*/"k.m_member_love_panel_effect_type_setting_heal_type", /*cell_name*/"k.m_member_love_panel_effect_type_setting_heal_type_cell_name", /*list_value_text_prefix*/"", /*icon_color_top*/1050762239, /*icon_color_bottom*/1050762239, /*text_color*/1050762239, /*is_percent*/1, /*is_parameter*/0, /*unit*/"k.m_member_love_panel_effect_type_setting_unit_percent", /*list_unit_zero*/"k.m_member_love_panel_effect_type_setting_unit_zero", /*list_panel_text*/"", /*list_sum_text*/"", /*card_rarity*/"", /*is_squad*/1, /*display_order*/10);
INSERT INTO `m_member_love_panel_effect_type_setting` VALUES (/*member_love_panel_effect_type*/11, /*name*/"k.m_member_love_panel_effect_type_setting_support_type", /*cell_name*/"k.m_member_love_panel_effect_type_setting_support_type_cell_name", /*list_value_text_prefix*/"", /*icon_color_top*/-457817345, /*icon_color_bottom*/-457817345, /*text_color*/-558875137, /*is_percent*/1, /*is_parameter*/0, /*unit*/"k.m_member_love_panel_effect_type_setting_unit_percent", /*list_unit_zero*/"k.m_member_love_panel_effect_type_setting_unit_zero", /*list_panel_text*/"", /*list_sum_text*/"", /*card_rarity*/"", /*is_squad*/1, /*display_order*/11);
INSERT INTO `m_member_love_panel_effect_type_setting` VALUES (/*member_love_panel_effect_type*/12, /*name*/"k.m_member_love_panel_effect_type_setting_card_attribute", /*cell_name*/"k.m_member_love_panel_effect_type_setting_card_attribute_cell_name", /*list_value_text_prefix*/"", /*icon_color_top*/-44409345, /*icon_color_bottom*/-44409345, /*text_color*/-44409345, /*is_percent*/1, /*is_parameter*/0, /*unit*/"k.m_member_love_panel_effect_type_setting_unit_percent", /*list_unit_zero*/"k.m_member_love_panel_effect_type_setting_unit_zero", /*list_panel_text*/"", /*list_sum_text*/"", /*card_rarity*/"", /*is_squad*/0, /*display_order*/12);
INSERT INTO `m_member_love_panel_effect_type_setting` VALUES (/*member_love_panel_effect_type*/13, /*name*/"k.m_member_love_panel_effect_type_setting_r_level", /*cell_name*/"k.m_member_love_panel_effect_type_setting_r_level_cell_name", /*list_value_text_prefix*/"", /*icon_color_top*/-1178410241, /*icon_color_bottom*/-1178410241, /*text_color*/-1952854529, /*is_percent*/0, /*is_parameter*/0, /*unit*/"k.m_member_love_panel_effect_type_setting_unit", /*list_unit_zero*/"k.m_member_love_panel_effect_type_setting_unit_zero", /*list_panel_text*/"k.m_member_love_panel_effect_type_setting_u_level_list_panel_text", /*list_sum_text*/"", /*card_rarity*/10, /*is_squad*/0, /*display_order*/15);
INSERT INTO `m_member_love_panel_effect_type_setting` VALUES (/*member_love_panel_effect_type*/14, /*name*/"k.m_member_love_panel_effect_type_setting_sr_level", /*cell_name*/"k.m_member_love_panel_effect_type_setting_sr_level_cell_name", /*list_value_text_prefix*/"", /*icon_color_top*/-271106817, /*icon_color_bottom*/-271106817, /*text_color*/-1062660865, /*is_percent*/0, /*is_parameter*/0, /*unit*/"k.m_member_love_panel_effect_type_setting_unit", /*list_unit_zero*/"k.m_member_love_panel_effect_type_setting_unit_zero", /*list_panel_text*/"k.m_member_love_panel_effect_type_setting_sr_level_list_panel_text", /*list_sum_text*/"", /*card_rarity*/20, /*is_squad*/0, /*display_order*/14);
INSERT INTO `m_member_love_panel_effect_type_setting` VALUES (/*member_love_panel_effect_type*/15, /*name*/"k.m_member_love_panel_effect_type_setting_ur_level", /*cell_name*/"k.m_member_love_panel_effect_type_setting_ur_level_cell_name", /*list_value_text_prefix*/"", /*icon_color_top*/-1091240193, /*icon_color_bottom*/-793054209, /*text_color*/-914105345, /*is_percent*/0, /*is_parameter*/0, /*unit*/"k.m_member_love_panel_effect_type_setting_unit", /*list_unit_zero*/"k.m_member_love_panel_effect_type_setting_unit_zero", /*list_panel_text*/"k.m_member_love_panel_effect_type_setting_ur_level_list_panel_text", /*list_sum_text*/"", /*card_rarity*/30, /*is_squad*/0, /*display_order*/13);
