CREATE TABLE m_present_route_type_setting(
  route_type INTEGER NOT NULL,
  description_default TEXT NOT NULL,
  description_base_1 TEXT,
  description_base_2 TEXT,
  description_base_3 TEXT,
  description_base_4 TEXT,
  description_base_5 TEXT,
  PRIMARY KEY (route_type)
);
INSERT INTO `m_present_route_type_setting` VALUES (/*route_type*/1, /*description_default*/"k.m_present_route_setting_description_gacha_default", /*description_base_1*/"k.m_present_route_setting_description_gacha_base_1", /*description_base_2*/"", /*description_base_3*/"", /*description_base_4*/"", /*description_base_5*/"");
INSERT INTO `m_present_route_type_setting` VALUES (/*route_type*/2, /*description_default*/"k.m_present_route_setting_description_admin_present_default", /*description_base_1*/"k.m_present_route_setting_description_admin_present_1", /*description_base_2*/"k.m_present_route_setting_description_admin_present_2", /*description_base_3*/"", /*description_base_4*/"", /*description_base_5*/"");
INSERT INTO `m_present_route_type_setting` VALUES (/*route_type*/3, /*description_default*/"k.m_present_route_setting_description_login_bonus_default", /*description_base_1*/"k.m_present_route_setting_description_login_bonus_base_1", /*description_base_2*/"k.m_present_route_setting_description_login_bonus_base_2", /*description_base_3*/"", /*description_base_4*/"", /*description_base_5*/"");
INSERT INTO `m_present_route_type_setting` VALUES (/*route_type*/4, /*description_default*/"k.m_present_route_setting_description_special_login_bonus_default", /*description_base_1*/"", /*description_base_2*/"", /*description_base_3*/"", /*description_base_4*/"", /*description_base_5*/"");
INSERT INTO `m_present_route_type_setting` VALUES (/*route_type*/5, /*description_default*/"k.m_present_route_setting_description_gift_box_default", /*description_base_1*/"", /*description_base_2*/"k.m_present_route_setting_description_gift_box_2", /*description_base_3*/"", /*description_base_4*/"", /*description_base_5*/"");
INSERT INTO `m_present_route_type_setting` VALUES (/*route_type*/6, /*description_default*/"k.m_present_route_setting_description_event_marathon_point_reward_default", /*description_base_1*/"", /*description_base_2*/"", /*description_base_3*/"", /*description_base_4*/"", /*description_base_5*/"");
INSERT INTO `m_present_route_type_setting` VALUES (/*route_type*/7, /*description_default*/"k.m_present_route_setting_description_item_full_default", /*description_base_1*/"", /*description_base_2*/"", /*description_base_3*/"", /*description_base_4*/"", /*description_base_5*/"");
INSERT INTO `m_present_route_type_setting` VALUES (/*route_type*/8, /*description_default*/"k.m_present_route_setting_description_love_level_up_default", /*description_base_1*/"k.m_present_route_setting_description_love_level_up_1", /*description_base_2*/"", /*description_base_3*/"", /*description_base_4*/"", /*description_base_5*/"");
INSERT INTO `m_present_route_type_setting` VALUES (/*route_type*/9, /*description_default*/"k.m_present_route_setting_description_retry_gacha_default", /*description_base_1*/"", /*description_base_2*/"", /*description_base_3*/"", /*description_base_4*/"", /*description_base_5*/"");
INSERT INTO `m_present_route_type_setting` VALUES (/*route_type*/10, /*description_default*/"k.m_present_route_setting_description_shop_exchange_default", /*description_base_1*/"", /*description_base_2*/"", /*description_base_3*/"", /*description_base_4*/"", /*description_base_5*/"");
INSERT INTO `m_present_route_type_setting` VALUES (/*route_type*/11, /*description_default*/"k.m_present_route_setting_description_shop_event_exchange_default", /*description_base_1*/"", /*description_base_2*/"", /*description_base_3*/"", /*description_base_4*/"", /*description_base_5*/"");
INSERT INTO `m_present_route_type_setting` VALUES (/*route_type*/12, /*description_default*/"k.m_present_route_setting_description_gps_present_default", /*description_base_1*/"k.m_present_route_setting_description_gps_present_base_1", /*description_base_2*/"", /*description_base_3*/"", /*description_base_4*/"", /*description_base_5*/"");
INSERT INTO `m_present_route_type_setting` VALUES (/*route_type*/13, /*description_default*/"k.m_present_route_setting_description_school_idol_festiva_id_reward", /*description_base_1*/"", /*description_base_2*/"", /*description_base_3*/"", /*description_base_4*/"", /*description_base_5*/"");
INSERT INTO `m_present_route_type_setting` VALUES (/*route_type*/14, /*description_default*/"k.m_serial_code_setting_description_serial_code_default", /*description_base_1*/"k.m_serial_code_setting_description_serial_code_1", /*description_base_2*/"", /*description_base_3*/"", /*description_base_4*/"", /*description_base_5*/"");
INSERT INTO `m_present_route_type_setting` VALUES (/*route_type*/15, /*description_default*/"k.m_present_route_setting_description_event_marathon_ranking_reward_default", /*description_base_1*/"", /*description_base_2*/"k.m_present_route_setting_description_event_marathon_ranking_reward_2", /*description_base_3*/"", /*description_base_4*/"", /*description_base_5*/"");
INSERT INTO `m_present_route_type_setting` VALUES (/*route_type*/16, /*description_default*/"k.m_present_route_setting_description_mission_default", /*description_base_1*/"", /*description_base_2*/"", /*description_base_3*/"", /*description_base_4*/"", /*description_base_5*/"");
INSERT INTO `m_present_route_type_setting` VALUES (/*route_type*/17, /*description_default*/"k.m_present_route_setting_description_tutorial_default", /*description_base_1*/"", /*description_base_2*/"", /*description_base_3*/"", /*description_base_4*/"", /*description_base_5*/"");
INSERT INTO `m_present_route_type_setting` VALUES (/*route_type*/18, /*description_default*/"k.m_present_route_setting_description_story_main_default", /*description_base_1*/"", /*description_base_2*/"k.m_present_route_setting_description_story_main_2", /*description_base_3*/"", /*description_base_4*/"", /*description_base_5*/"");
INSERT INTO `m_present_route_type_setting` VALUES (/*route_type*/19, /*description_default*/"k.m_present_route_setting_description_shop_item_full_default", /*description_base_1*/"k.m_present_route_setting_description_shop_item_full_1", /*description_base_2*/"", /*description_base_3*/"", /*description_base_4*/"", /*description_base_5*/"");
INSERT INTO `m_present_route_type_setting` VALUES (/*route_type*/20, /*description_default*/"k.m_present_route_setting_description_live_accessory_item_full_default", /*description_base_1*/"", /*description_base_2*/"", /*description_base_3*/"", /*description_base_4*/"", /*description_base_5*/"");
INSERT INTO `m_present_route_type_setting` VALUES (/*route_type*/21, /*description_default*/"k.m_present_route_setting_description_event_mining_point_ranking_reward_default", /*description_base_1*/"", /*description_base_2*/"k.m_present_route_setting_description_event_mining_point_ranking_reward_2", /*description_base_3*/"", /*description_base_4*/"", /*description_base_5*/"");
INSERT INTO `m_present_route_type_setting` VALUES (/*route_type*/22, /*description_default*/"k.m_present_route_setting_description_event_mining_voltage_ranking_reward_default", /*description_base_1*/"", /*description_base_2*/"k.m_present_route_setting_description_event_mining_voltage_ranking_reward_2", /*description_base_3*/"", /*description_base_4*/"", /*description_base_5*/"");
INSERT INTO `m_present_route_type_setting` VALUES (/*route_type*/23, /*description_default*/"k.m_present_route_setting_description_event_coop_point_reward_default", /*description_base_1*/"", /*description_base_2*/"", /*description_base_3*/"", /*description_base_4*/"", /*description_base_5*/"");
INSERT INTO `m_present_route_type_setting` VALUES (/*route_type*/24, /*description_default*/"k.m_present_route_setting_description_trade_default", /*description_base_1*/"", /*description_base_2*/"", /*description_base_3*/"", /*description_base_4*/"", /*description_base_5*/"");
INSERT INTO `m_present_route_type_setting` VALUES (/*route_type*/25, /*description_default*/"k.m_present_route_setting_description_event_coop_global_reward_default", /*description_base_1*/"", /*description_base_2*/"", /*description_base_3*/"", /*description_base_4*/"", /*description_base_5*/"");
INSERT INTO `m_present_route_type_setting` VALUES (/*route_type*/26, /*description_default*/"k.m_present_route_setting_description_event_coop_period_total_ranking_reward_default", /*description_base_1*/"k.m_present_route_setting_description_event_coop_period_total_ranking_reward_1", /*description_base_2*/"k.m_present_route_setting_description_event_coop_period_total_ranking_reward_2", /*description_base_3*/"", /*description_base_4*/"", /*description_base_5*/"");
INSERT INTO `m_present_route_type_setting` VALUES (/*route_type*/27, /*description_default*/"k.m_present_route_setting_description_event_coop_daily_ranking_reward_default", /*description_base_1*/"k.m_present_route_setting_description_event_coop_daily_ranking_reward_reward_1", /*description_base_2*/"k.m_present_route_setting_description_event_coop_daily_ranking_reward_reward_2", /*description_base_3*/"", /*description_base_4*/"", /*description_base_5*/"");
INSERT INTO `m_present_route_type_setting` VALUES (/*route_type*/28, /*description_default*/"k.m_present_route_setting_description_tower_clear_reward_default", /*description_base_1*/"", /*description_base_2*/"", /*description_base_3*/"k.m_present_route_setting_description_tower_clear_reward_3", /*description_base_4*/"", /*description_base_5*/"");
INSERT INTO `m_present_route_type_setting` VALUES (/*route_type*/29, /*description_default*/"k.m_present_route_setting_description_tower_progress_reward_default", /*description_base_1*/"", /*description_base_2*/"", /*description_base_3*/"k.m_present_route_setting_description_tower_progress_reward_3", /*description_base_4*/"", /*description_base_5*/"");
INSERT INTO `m_present_route_type_setting` VALUES (/*route_type*/30, /*description_default*/"k.m_present_route_setting_description_story_member_default", /*description_base_1*/"", /*description_base_2*/"k.m_present_route_setting_description_story_member_2", /*description_base_3*/"", /*description_base_4*/"", /*description_base_5*/"");
INSERT INTO `m_present_route_type_setting` VALUES (/*route_type*/31, /*description_default*/"k.m_present_route_setting_description_subscription_daily_reward_default", /*description_base_1*/"", /*description_base_2*/"", /*description_base_3*/"", /*description_base_4*/"", /*description_base_5*/"");
INSERT INTO `m_present_route_type_setting` VALUES (/*route_type*/32, /*description_default*/"k.m_present_route_setting_description_subscription_continue_reward_default", /*description_base_1*/"k.m_present_route_setting_description_subscription_continue_reward_1", /*description_base_2*/"k.m_present_route_setting_description_subscription_continue_reward_2", /*description_base_3*/"", /*description_base_4*/"", /*description_base_5*/"");
INSERT INTO `m_present_route_type_setting` VALUES (/*route_type*/33, /*description_default*/"k.m_present_route_setting_description_story_linkage_default", /*description_base_1*/"k.m_present_route_setting_description_story_linkage_1", /*description_base_2*/"k.m_present_route_setting_description_story_linkage_2", /*description_base_3*/"", /*description_base_4*/"", /*description_base_5*/"");
INSERT INTO `m_present_route_type_setting` VALUES (/*route_type*/34, /*description_default*/"k.m_present_route_setting_description_story_linkage_addtional_default", /*description_base_1*/"k.m_present_route_setting_description_story_linkage_addtional_1", /*description_base_2*/"k.m_present_route_setting_description_story_linkage_addtional_2", /*description_base_3*/"", /*description_base_4*/"", /*description_base_5*/"");
INSERT INTO `m_present_route_type_setting` VALUES (/*route_type*/99, /*description_default*/"k.m_present_route_setting_description_debug_default", /*description_base_1*/"k.m_present_route_setting_description_debug_1", /*description_base_2*/"k.m_present_route_setting_description_debug_2", /*description_base_3*/"", /*description_base_4*/"", /*description_base_5*/"");
