CREATE TABLE m_skill_target(
  id INTEGER NOT NULL,
  only_owner INTEGER NOT NULL,
  excluding_owner INTEGER NOT NULL,
  random_choose_count INTEGER NOT NULL,
  target_attribute_group_id INTEGER,
  target_member_group_id INTEGER,
  target_unit_group_id INTEGER,
  target_school_group_id INTEGER,
  target_school_grade_group_id INTEGER,
  target_role_group_id INTEGER,
  checking_owner_party INTEGER NOT NULL,
  checking_owner_school INTEGER NOT NULL,
  checking_owner_grade INTEGER NOT NULL,
  checking_owner_unit INTEGER NOT NULL,
  checking_owner_attribute INTEGER NOT NULL,
  checking_owner_role INTEGER NOT NULL,
  target_party_type_id INTEGER,
  PRIMARY KEY (id)
);
INSERT INTO `m_skill_target` VALUES (/*id*/1, /*only_owner*/0, /*excluding_owner*/0, /*random_choose_count*/9, /*target_attribute_group_id*/"", /*target_member_group_id*/"", /*target_unit_group_id*/"", /*target_school_group_id*/"", /*target_school_grade_group_id*/"", /*target_role_group_id*/"", /*checking_owner_party*/0, /*checking_owner_school*/0, /*checking_owner_grade*/0, /*checking_owner_unit*/0, /*checking_owner_attribute*/0, /*checking_owner_role*/0, /*target_party_type_id*/"");
INSERT INTO `m_skill_target` VALUES (/*id*/2, /*only_owner*/0, /*excluding_owner*/0, /*random_choose_count*/9, /*target_attribute_group_id*/"", /*target_member_group_id*/1, /*target_unit_group_id*/"", /*target_school_group_id*/"", /*target_school_grade_group_id*/"", /*target_role_group_id*/"", /*checking_owner_party*/0, /*checking_owner_school*/0, /*checking_owner_grade*/0, /*checking_owner_unit*/0, /*checking_owner_attribute*/0, /*checking_owner_role*/0, /*target_party_type_id*/"");
INSERT INTO `m_skill_target` VALUES (/*id*/3, /*only_owner*/0, /*excluding_owner*/0, /*random_choose_count*/9, /*target_attribute_group_id*/"", /*target_member_group_id*/2, /*target_unit_group_id*/"", /*target_school_group_id*/"", /*target_school_grade_group_id*/"", /*target_role_group_id*/"", /*checking_owner_party*/0, /*checking_owner_school*/0, /*checking_owner_grade*/0, /*checking_owner_unit*/0, /*checking_owner_attribute*/0, /*checking_owner_role*/0, /*target_party_type_id*/"");
INSERT INTO `m_skill_target` VALUES (/*id*/4, /*only_owner*/0, /*excluding_owner*/0, /*random_choose_count*/9, /*target_attribute_group_id*/"", /*target_member_group_id*/3, /*target_unit_group_id*/"", /*target_school_group_id*/"", /*target_school_grade_group_id*/"", /*target_role_group_id*/"", /*checking_owner_party*/0, /*checking_owner_school*/0, /*checking_owner_grade*/0, /*checking_owner_unit*/0, /*checking_owner_attribute*/0, /*checking_owner_role*/0, /*target_party_type_id*/"");
INSERT INTO `m_skill_target` VALUES (/*id*/5, /*only_owner*/0, /*excluding_owner*/0, /*random_choose_count*/9, /*target_attribute_group_id*/"", /*target_member_group_id*/4, /*target_unit_group_id*/"", /*target_school_group_id*/"", /*target_school_grade_group_id*/"", /*target_role_group_id*/"", /*checking_owner_party*/0, /*checking_owner_school*/0, /*checking_owner_grade*/0, /*checking_owner_unit*/0, /*checking_owner_attribute*/0, /*checking_owner_role*/0, /*target_party_type_id*/"");
INSERT INTO `m_skill_target` VALUES (/*id*/6, /*only_owner*/0, /*excluding_owner*/0, /*random_choose_count*/9, /*target_attribute_group_id*/"", /*target_member_group_id*/5, /*target_unit_group_id*/"", /*target_school_group_id*/"", /*target_school_grade_group_id*/"", /*target_role_group_id*/"", /*checking_owner_party*/0, /*checking_owner_school*/0, /*checking_owner_grade*/0, /*checking_owner_unit*/0, /*checking_owner_attribute*/0, /*checking_owner_role*/0, /*target_party_type_id*/"");
INSERT INTO `m_skill_target` VALUES (/*id*/7, /*only_owner*/0, /*excluding_owner*/0, /*random_choose_count*/9, /*target_attribute_group_id*/"", /*target_member_group_id*/6, /*target_unit_group_id*/"", /*target_school_group_id*/"", /*target_school_grade_group_id*/"", /*target_role_group_id*/"", /*checking_owner_party*/0, /*checking_owner_school*/0, /*checking_owner_grade*/0, /*checking_owner_unit*/0, /*checking_owner_attribute*/0, /*checking_owner_role*/0, /*target_party_type_id*/"");
INSERT INTO `m_skill_target` VALUES (/*id*/8, /*only_owner*/0, /*excluding_owner*/0, /*random_choose_count*/9, /*target_attribute_group_id*/"", /*target_member_group_id*/7, /*target_unit_group_id*/"", /*target_school_group_id*/"", /*target_school_grade_group_id*/"", /*target_role_group_id*/"", /*checking_owner_party*/0, /*checking_owner_school*/0, /*checking_owner_grade*/0, /*checking_owner_unit*/0, /*checking_owner_attribute*/0, /*checking_owner_role*/0, /*target_party_type_id*/"");
INSERT INTO `m_skill_target` VALUES (/*id*/9, /*only_owner*/0, /*excluding_owner*/0, /*random_choose_count*/9, /*target_attribute_group_id*/"", /*target_member_group_id*/8, /*target_unit_group_id*/"", /*target_school_group_id*/"", /*target_school_grade_group_id*/"", /*target_role_group_id*/"", /*checking_owner_party*/0, /*checking_owner_school*/0, /*checking_owner_grade*/0, /*checking_owner_unit*/0, /*checking_owner_attribute*/0, /*checking_owner_role*/0, /*target_party_type_id*/"");
INSERT INTO `m_skill_target` VALUES (/*id*/10, /*only_owner*/0, /*excluding_owner*/0, /*random_choose_count*/9, /*target_attribute_group_id*/"", /*target_member_group_id*/9, /*target_unit_group_id*/"", /*target_school_group_id*/"", /*target_school_grade_group_id*/"", /*target_role_group_id*/"", /*checking_owner_party*/0, /*checking_owner_school*/0, /*checking_owner_grade*/0, /*checking_owner_unit*/0, /*checking_owner_attribute*/0, /*checking_owner_role*/0, /*target_party_type_id*/"");
INSERT INTO `m_skill_target` VALUES (/*id*/11, /*only_owner*/0, /*excluding_owner*/0, /*random_choose_count*/9, /*target_attribute_group_id*/"", /*target_member_group_id*/10, /*target_unit_group_id*/"", /*target_school_group_id*/"", /*target_school_grade_group_id*/"", /*target_role_group_id*/"", /*checking_owner_party*/0, /*checking_owner_school*/0, /*checking_owner_grade*/0, /*checking_owner_unit*/0, /*checking_owner_attribute*/0, /*checking_owner_role*/0, /*target_party_type_id*/"");
INSERT INTO `m_skill_target` VALUES (/*id*/12, /*only_owner*/0, /*excluding_owner*/0, /*random_choose_count*/9, /*target_attribute_group_id*/"", /*target_member_group_id*/11, /*target_unit_group_id*/"", /*target_school_group_id*/"", /*target_school_grade_group_id*/"", /*target_role_group_id*/"", /*checking_owner_party*/0, /*checking_owner_school*/0, /*checking_owner_grade*/0, /*checking_owner_unit*/0, /*checking_owner_attribute*/0, /*checking_owner_role*/0, /*target_party_type_id*/"");
INSERT INTO `m_skill_target` VALUES (/*id*/13, /*only_owner*/0, /*excluding_owner*/0, /*random_choose_count*/9, /*target_attribute_group_id*/"", /*target_member_group_id*/12, /*target_unit_group_id*/"", /*target_school_group_id*/"", /*target_school_grade_group_id*/"", /*target_role_group_id*/"", /*checking_owner_party*/0, /*checking_owner_school*/0, /*checking_owner_grade*/0, /*checking_owner_unit*/0, /*checking_owner_attribute*/0, /*checking_owner_role*/0, /*target_party_type_id*/"");
INSERT INTO `m_skill_target` VALUES (/*id*/14, /*only_owner*/0, /*excluding_owner*/0, /*random_choose_count*/9, /*target_attribute_group_id*/"", /*target_member_group_id*/13, /*target_unit_group_id*/"", /*target_school_group_id*/"", /*target_school_grade_group_id*/"", /*target_role_group_id*/"", /*checking_owner_party*/0, /*checking_owner_school*/0, /*checking_owner_grade*/0, /*checking_owner_unit*/0, /*checking_owner_attribute*/0, /*checking_owner_role*/0, /*target_party_type_id*/"");
INSERT INTO `m_skill_target` VALUES (/*id*/15, /*only_owner*/0, /*excluding_owner*/0, /*random_choose_count*/9, /*target_attribute_group_id*/"", /*target_member_group_id*/14, /*target_unit_group_id*/"", /*target_school_group_id*/"", /*target_school_grade_group_id*/"", /*target_role_group_id*/"", /*checking_owner_party*/0, /*checking_owner_school*/0, /*checking_owner_grade*/0, /*checking_owner_unit*/0, /*checking_owner_attribute*/0, /*checking_owner_role*/0, /*target_party_type_id*/"");
INSERT INTO `m_skill_target` VALUES (/*id*/16, /*only_owner*/0, /*excluding_owner*/0, /*random_choose_count*/9, /*target_attribute_group_id*/"", /*target_member_group_id*/15, /*target_unit_group_id*/"", /*target_school_group_id*/"", /*target_school_grade_group_id*/"", /*target_role_group_id*/"", /*checking_owner_party*/0, /*checking_owner_school*/0, /*checking_owner_grade*/0, /*checking_owner_unit*/0, /*checking_owner_attribute*/0, /*checking_owner_role*/0, /*target_party_type_id*/"");
INSERT INTO `m_skill_target` VALUES (/*id*/17, /*only_owner*/0, /*excluding_owner*/0, /*random_choose_count*/9, /*target_attribute_group_id*/"", /*target_member_group_id*/16, /*target_unit_group_id*/"", /*target_school_group_id*/"", /*target_school_grade_group_id*/"", /*target_role_group_id*/"", /*checking_owner_party*/0, /*checking_owner_school*/0, /*checking_owner_grade*/0, /*checking_owner_unit*/0, /*checking_owner_attribute*/0, /*checking_owner_role*/0, /*target_party_type_id*/"");
INSERT INTO `m_skill_target` VALUES (/*id*/18, /*only_owner*/0, /*excluding_owner*/0, /*random_choose_count*/9, /*target_attribute_group_id*/"", /*target_member_group_id*/17, /*target_unit_group_id*/"", /*target_school_group_id*/"", /*target_school_grade_group_id*/"", /*target_role_group_id*/"", /*checking_owner_party*/0, /*checking_owner_school*/0, /*checking_owner_grade*/0, /*checking_owner_unit*/0, /*checking_owner_attribute*/0, /*checking_owner_role*/0, /*target_party_type_id*/"");
INSERT INTO `m_skill_target` VALUES (/*id*/19, /*only_owner*/0, /*excluding_owner*/0, /*random_choose_count*/9, /*target_attribute_group_id*/"", /*target_member_group_id*/18, /*target_unit_group_id*/"", /*target_school_group_id*/"", /*target_school_grade_group_id*/"", /*target_role_group_id*/"", /*checking_owner_party*/0, /*checking_owner_school*/0, /*checking_owner_grade*/0, /*checking_owner_unit*/0, /*checking_owner_attribute*/0, /*checking_owner_role*/0, /*target_party_type_id*/"");
INSERT INTO `m_skill_target` VALUES (/*id*/20, /*only_owner*/0, /*excluding_owner*/0, /*random_choose_count*/9, /*target_attribute_group_id*/"", /*target_member_group_id*/19, /*target_unit_group_id*/"", /*target_school_group_id*/"", /*target_school_grade_group_id*/"", /*target_role_group_id*/"", /*checking_owner_party*/0, /*checking_owner_school*/0, /*checking_owner_grade*/0, /*checking_owner_unit*/0, /*checking_owner_attribute*/0, /*checking_owner_role*/0, /*target_party_type_id*/"");
INSERT INTO `m_skill_target` VALUES (/*id*/21, /*only_owner*/0, /*excluding_owner*/0, /*random_choose_count*/9, /*target_attribute_group_id*/"", /*target_member_group_id*/20, /*target_unit_group_id*/"", /*target_school_group_id*/"", /*target_school_grade_group_id*/"", /*target_role_group_id*/"", /*checking_owner_party*/0, /*checking_owner_school*/0, /*checking_owner_grade*/0, /*checking_owner_unit*/0, /*checking_owner_attribute*/0, /*checking_owner_role*/0, /*target_party_type_id*/"");
INSERT INTO `m_skill_target` VALUES (/*id*/22, /*only_owner*/0, /*excluding_owner*/0, /*random_choose_count*/9, /*target_attribute_group_id*/"", /*target_member_group_id*/21, /*target_unit_group_id*/"", /*target_school_group_id*/"", /*target_school_grade_group_id*/"", /*target_role_group_id*/"", /*checking_owner_party*/0, /*checking_owner_school*/0, /*checking_owner_grade*/0, /*checking_owner_unit*/0, /*checking_owner_attribute*/0, /*checking_owner_role*/0, /*target_party_type_id*/"");
INSERT INTO `m_skill_target` VALUES (/*id*/23, /*only_owner*/0, /*excluding_owner*/0, /*random_choose_count*/9, /*target_attribute_group_id*/"", /*target_member_group_id*/22, /*target_unit_group_id*/"", /*target_school_group_id*/"", /*target_school_grade_group_id*/"", /*target_role_group_id*/"", /*checking_owner_party*/0, /*checking_owner_school*/0, /*checking_owner_grade*/0, /*checking_owner_unit*/0, /*checking_owner_attribute*/0, /*checking_owner_role*/0, /*target_party_type_id*/"");
INSERT INTO `m_skill_target` VALUES (/*id*/24, /*only_owner*/0, /*excluding_owner*/0, /*random_choose_count*/9, /*target_attribute_group_id*/"", /*target_member_group_id*/23, /*target_unit_group_id*/"", /*target_school_group_id*/"", /*target_school_grade_group_id*/"", /*target_role_group_id*/"", /*checking_owner_party*/0, /*checking_owner_school*/0, /*checking_owner_grade*/0, /*checking_owner_unit*/0, /*checking_owner_attribute*/0, /*checking_owner_role*/0, /*target_party_type_id*/"");
INSERT INTO `m_skill_target` VALUES (/*id*/25, /*only_owner*/0, /*excluding_owner*/0, /*random_choose_count*/9, /*target_attribute_group_id*/"", /*target_member_group_id*/24, /*target_unit_group_id*/"", /*target_school_group_id*/"", /*target_school_grade_group_id*/"", /*target_role_group_id*/"", /*checking_owner_party*/0, /*checking_owner_school*/0, /*checking_owner_grade*/0, /*checking_owner_unit*/0, /*checking_owner_attribute*/0, /*checking_owner_role*/0, /*target_party_type_id*/"");
INSERT INTO `m_skill_target` VALUES (/*id*/26, /*only_owner*/0, /*excluding_owner*/0, /*random_choose_count*/9, /*target_attribute_group_id*/"", /*target_member_group_id*/25, /*target_unit_group_id*/"", /*target_school_group_id*/"", /*target_school_grade_group_id*/"", /*target_role_group_id*/"", /*checking_owner_party*/0, /*checking_owner_school*/0, /*checking_owner_grade*/0, /*checking_owner_unit*/0, /*checking_owner_attribute*/0, /*checking_owner_role*/0, /*target_party_type_id*/"");
INSERT INTO `m_skill_target` VALUES (/*id*/27, /*only_owner*/0, /*excluding_owner*/0, /*random_choose_count*/9, /*target_attribute_group_id*/"", /*target_member_group_id*/26, /*target_unit_group_id*/"", /*target_school_group_id*/"", /*target_school_grade_group_id*/"", /*target_role_group_id*/"", /*checking_owner_party*/0, /*checking_owner_school*/0, /*checking_owner_grade*/0, /*checking_owner_unit*/0, /*checking_owner_attribute*/0, /*checking_owner_role*/0, /*target_party_type_id*/"");
INSERT INTO `m_skill_target` VALUES (/*id*/28, /*only_owner*/0, /*excluding_owner*/0, /*random_choose_count*/9, /*target_attribute_group_id*/"", /*target_member_group_id*/27, /*target_unit_group_id*/"", /*target_school_group_id*/"", /*target_school_grade_group_id*/"", /*target_role_group_id*/"", /*checking_owner_party*/0, /*checking_owner_school*/0, /*checking_owner_grade*/0, /*checking_owner_unit*/0, /*checking_owner_attribute*/0, /*checking_owner_role*/0, /*target_party_type_id*/"");
INSERT INTO `m_skill_target` VALUES (/*id*/29, /*only_owner*/0, /*excluding_owner*/0, /*random_choose_count*/9, /*target_attribute_group_id*/"", /*target_member_group_id*/"", /*target_unit_group_id*/"", /*target_school_group_id*/1, /*target_school_grade_group_id*/"", /*target_role_group_id*/"", /*checking_owner_party*/0, /*checking_owner_school*/0, /*checking_owner_grade*/0, /*checking_owner_unit*/0, /*checking_owner_attribute*/0, /*checking_owner_role*/0, /*target_party_type_id*/"");
INSERT INTO `m_skill_target` VALUES (/*id*/30, /*only_owner*/0, /*excluding_owner*/0, /*random_choose_count*/9, /*target_attribute_group_id*/"", /*target_member_group_id*/"", /*target_unit_group_id*/"", /*target_school_group_id*/2, /*target_school_grade_group_id*/"", /*target_role_group_id*/"", /*checking_owner_party*/0, /*checking_owner_school*/0, /*checking_owner_grade*/0, /*checking_owner_unit*/0, /*checking_owner_attribute*/0, /*checking_owner_role*/0, /*target_party_type_id*/"");
INSERT INTO `m_skill_target` VALUES (/*id*/31, /*only_owner*/0, /*excluding_owner*/0, /*random_choose_count*/9, /*target_attribute_group_id*/"", /*target_member_group_id*/"", /*target_unit_group_id*/"", /*target_school_group_id*/3, /*target_school_grade_group_id*/"", /*target_role_group_id*/"", /*checking_owner_party*/0, /*checking_owner_school*/0, /*checking_owner_grade*/0, /*checking_owner_unit*/0, /*checking_owner_attribute*/0, /*checking_owner_role*/0, /*target_party_type_id*/"");
INSERT INTO `m_skill_target` VALUES (/*id*/32, /*only_owner*/0, /*excluding_owner*/0, /*random_choose_count*/9, /*target_attribute_group_id*/"", /*target_member_group_id*/"", /*target_unit_group_id*/1, /*target_school_group_id*/"", /*target_school_grade_group_id*/"", /*target_role_group_id*/"", /*checking_owner_party*/0, /*checking_owner_school*/0, /*checking_owner_grade*/0, /*checking_owner_unit*/0, /*checking_owner_attribute*/0, /*checking_owner_role*/0, /*target_party_type_id*/"");
INSERT INTO `m_skill_target` VALUES (/*id*/33, /*only_owner*/0, /*excluding_owner*/0, /*random_choose_count*/9, /*target_attribute_group_id*/"", /*target_member_group_id*/"", /*target_unit_group_id*/2, /*target_school_group_id*/"", /*target_school_grade_group_id*/"", /*target_role_group_id*/"", /*checking_owner_party*/0, /*checking_owner_school*/0, /*checking_owner_grade*/0, /*checking_owner_unit*/0, /*checking_owner_attribute*/0, /*checking_owner_role*/0, /*target_party_type_id*/"");
INSERT INTO `m_skill_target` VALUES (/*id*/34, /*only_owner*/0, /*excluding_owner*/0, /*random_choose_count*/9, /*target_attribute_group_id*/"", /*target_member_group_id*/"", /*target_unit_group_id*/3, /*target_school_group_id*/"", /*target_school_grade_group_id*/"", /*target_role_group_id*/"", /*checking_owner_party*/0, /*checking_owner_school*/0, /*checking_owner_grade*/0, /*checking_owner_unit*/0, /*checking_owner_attribute*/0, /*checking_owner_role*/0, /*target_party_type_id*/"");
INSERT INTO `m_skill_target` VALUES (/*id*/35, /*only_owner*/0, /*excluding_owner*/0, /*random_choose_count*/9, /*target_attribute_group_id*/"", /*target_member_group_id*/"", /*target_unit_group_id*/4, /*target_school_group_id*/"", /*target_school_grade_group_id*/"", /*target_role_group_id*/"", /*checking_owner_party*/0, /*checking_owner_school*/0, /*checking_owner_grade*/0, /*checking_owner_unit*/0, /*checking_owner_attribute*/0, /*checking_owner_role*/0, /*target_party_type_id*/"");
INSERT INTO `m_skill_target` VALUES (/*id*/36, /*only_owner*/0, /*excluding_owner*/0, /*random_choose_count*/9, /*target_attribute_group_id*/"", /*target_member_group_id*/"", /*target_unit_group_id*/5, /*target_school_group_id*/"", /*target_school_grade_group_id*/"", /*target_role_group_id*/"", /*checking_owner_party*/0, /*checking_owner_school*/0, /*checking_owner_grade*/0, /*checking_owner_unit*/0, /*checking_owner_attribute*/0, /*checking_owner_role*/0, /*target_party_type_id*/"");
INSERT INTO `m_skill_target` VALUES (/*id*/37, /*only_owner*/0, /*excluding_owner*/0, /*random_choose_count*/9, /*target_attribute_group_id*/"", /*target_member_group_id*/"", /*target_unit_group_id*/6, /*target_school_group_id*/"", /*target_school_grade_group_id*/"", /*target_role_group_id*/"", /*checking_owner_party*/0, /*checking_owner_school*/0, /*checking_owner_grade*/0, /*checking_owner_unit*/0, /*checking_owner_attribute*/0, /*checking_owner_role*/0, /*target_party_type_id*/"");
INSERT INTO `m_skill_target` VALUES (/*id*/38, /*only_owner*/0, /*excluding_owner*/0, /*random_choose_count*/9, /*target_attribute_group_id*/"", /*target_member_group_id*/"", /*target_unit_group_id*/"", /*target_school_group_id*/"", /*target_school_grade_group_id*/"", /*target_role_group_id*/1, /*checking_owner_party*/0, /*checking_owner_school*/0, /*checking_owner_grade*/0, /*checking_owner_unit*/0, /*checking_owner_attribute*/0, /*checking_owner_role*/0, /*target_party_type_id*/"");
INSERT INTO `m_skill_target` VALUES (/*id*/39, /*only_owner*/0, /*excluding_owner*/0, /*random_choose_count*/9, /*target_attribute_group_id*/"", /*target_member_group_id*/"", /*target_unit_group_id*/"", /*target_school_group_id*/"", /*target_school_grade_group_id*/"", /*target_role_group_id*/2, /*checking_owner_party*/0, /*checking_owner_school*/0, /*checking_owner_grade*/0, /*checking_owner_unit*/0, /*checking_owner_attribute*/0, /*checking_owner_role*/0, /*target_party_type_id*/"");
INSERT INTO `m_skill_target` VALUES (/*id*/40, /*only_owner*/0, /*excluding_owner*/0, /*random_choose_count*/9, /*target_attribute_group_id*/"", /*target_member_group_id*/"", /*target_unit_group_id*/"", /*target_school_group_id*/"", /*target_school_grade_group_id*/"", /*target_role_group_id*/3, /*checking_owner_party*/0, /*checking_owner_school*/0, /*checking_owner_grade*/0, /*checking_owner_unit*/0, /*checking_owner_attribute*/0, /*checking_owner_role*/0, /*target_party_type_id*/"");
INSERT INTO `m_skill_target` VALUES (/*id*/41, /*only_owner*/0, /*excluding_owner*/0, /*random_choose_count*/9, /*target_attribute_group_id*/"", /*target_member_group_id*/"", /*target_unit_group_id*/"", /*target_school_group_id*/"", /*target_school_grade_group_id*/"", /*target_role_group_id*/4, /*checking_owner_party*/0, /*checking_owner_school*/0, /*checking_owner_grade*/0, /*checking_owner_unit*/0, /*checking_owner_attribute*/0, /*checking_owner_role*/0, /*target_party_type_id*/"");
INSERT INTO `m_skill_target` VALUES (/*id*/42, /*only_owner*/0, /*excluding_owner*/0, /*random_choose_count*/1, /*target_attribute_group_id*/"", /*target_member_group_id*/"", /*target_unit_group_id*/"", /*target_school_group_id*/"", /*target_school_grade_group_id*/"", /*target_role_group_id*/"", /*checking_owner_party*/0, /*checking_owner_school*/0, /*checking_owner_grade*/0, /*checking_owner_unit*/0, /*checking_owner_attribute*/0, /*checking_owner_role*/0, /*target_party_type_id*/"");
INSERT INTO `m_skill_target` VALUES (/*id*/43, /*only_owner*/0, /*excluding_owner*/0, /*random_choose_count*/2, /*target_attribute_group_id*/"", /*target_member_group_id*/"", /*target_unit_group_id*/"", /*target_school_group_id*/"", /*target_school_grade_group_id*/"", /*target_role_group_id*/"", /*checking_owner_party*/0, /*checking_owner_school*/0, /*checking_owner_grade*/0, /*checking_owner_unit*/0, /*checking_owner_attribute*/0, /*checking_owner_role*/0, /*target_party_type_id*/"");
INSERT INTO `m_skill_target` VALUES (/*id*/44, /*only_owner*/0, /*excluding_owner*/0, /*random_choose_count*/3, /*target_attribute_group_id*/"", /*target_member_group_id*/"", /*target_unit_group_id*/"", /*target_school_group_id*/"", /*target_school_grade_group_id*/"", /*target_role_group_id*/"", /*checking_owner_party*/0, /*checking_owner_school*/0, /*checking_owner_grade*/0, /*checking_owner_unit*/0, /*checking_owner_attribute*/0, /*checking_owner_role*/0, /*target_party_type_id*/"");
INSERT INTO `m_skill_target` VALUES (/*id*/45, /*only_owner*/0, /*excluding_owner*/0, /*random_choose_count*/4, /*target_attribute_group_id*/"", /*target_member_group_id*/"", /*target_unit_group_id*/"", /*target_school_group_id*/"", /*target_school_grade_group_id*/"", /*target_role_group_id*/"", /*checking_owner_party*/0, /*checking_owner_school*/0, /*checking_owner_grade*/0, /*checking_owner_unit*/0, /*checking_owner_attribute*/0, /*checking_owner_role*/0, /*target_party_type_id*/"");
INSERT INTO `m_skill_target` VALUES (/*id*/46, /*only_owner*/0, /*excluding_owner*/0, /*random_choose_count*/5, /*target_attribute_group_id*/"", /*target_member_group_id*/"", /*target_unit_group_id*/"", /*target_school_group_id*/"", /*target_school_grade_group_id*/"", /*target_role_group_id*/"", /*checking_owner_party*/0, /*checking_owner_school*/0, /*checking_owner_grade*/0, /*checking_owner_unit*/0, /*checking_owner_attribute*/0, /*checking_owner_role*/0, /*target_party_type_id*/"");
INSERT INTO `m_skill_target` VALUES (/*id*/47, /*only_owner*/0, /*excluding_owner*/0, /*random_choose_count*/6, /*target_attribute_group_id*/"", /*target_member_group_id*/"", /*target_unit_group_id*/"", /*target_school_group_id*/"", /*target_school_grade_group_id*/"", /*target_role_group_id*/"", /*checking_owner_party*/0, /*checking_owner_school*/0, /*checking_owner_grade*/0, /*checking_owner_unit*/0, /*checking_owner_attribute*/0, /*checking_owner_role*/0, /*target_party_type_id*/"");
INSERT INTO `m_skill_target` VALUES (/*id*/48, /*only_owner*/0, /*excluding_owner*/0, /*random_choose_count*/7, /*target_attribute_group_id*/"", /*target_member_group_id*/"", /*target_unit_group_id*/"", /*target_school_group_id*/"", /*target_school_grade_group_id*/"", /*target_role_group_id*/"", /*checking_owner_party*/0, /*checking_owner_school*/0, /*checking_owner_grade*/0, /*checking_owner_unit*/0, /*checking_owner_attribute*/0, /*checking_owner_role*/0, /*target_party_type_id*/"");
INSERT INTO `m_skill_target` VALUES (/*id*/49, /*only_owner*/0, /*excluding_owner*/0, /*random_choose_count*/8, /*target_attribute_group_id*/"", /*target_member_group_id*/"", /*target_unit_group_id*/"", /*target_school_group_id*/"", /*target_school_grade_group_id*/"", /*target_role_group_id*/"", /*checking_owner_party*/0, /*checking_owner_school*/0, /*checking_owner_grade*/0, /*checking_owner_unit*/0, /*checking_owner_attribute*/0, /*checking_owner_role*/0, /*target_party_type_id*/"");
INSERT INTO `m_skill_target` VALUES (/*id*/50, /*only_owner*/0, /*excluding_owner*/1, /*random_choose_count*/8, /*target_attribute_group_id*/"", /*target_member_group_id*/"", /*target_unit_group_id*/"", /*target_school_group_id*/"", /*target_school_grade_group_id*/"", /*target_role_group_id*/"", /*checking_owner_party*/0, /*checking_owner_school*/0, /*checking_owner_grade*/0, /*checking_owner_unit*/0, /*checking_owner_attribute*/0, /*checking_owner_role*/0, /*target_party_type_id*/"");
INSERT INTO `m_skill_target` VALUES (/*id*/51, /*only_owner*/0, /*excluding_owner*/1, /*random_choose_count*/2, /*target_attribute_group_id*/"", /*target_member_group_id*/"", /*target_unit_group_id*/"", /*target_school_group_id*/"", /*target_school_grade_group_id*/"", /*target_role_group_id*/"", /*checking_owner_party*/1, /*checking_owner_school*/0, /*checking_owner_grade*/0, /*checking_owner_unit*/0, /*checking_owner_attribute*/0, /*checking_owner_role*/0, /*target_party_type_id*/"");
INSERT INTO `m_skill_target` VALUES (/*id*/52, /*only_owner*/0, /*excluding_owner*/0, /*random_choose_count*/9, /*target_attribute_group_id*/"", /*target_member_group_id*/"", /*target_unit_group_id*/"", /*target_school_group_id*/"", /*target_school_grade_group_id*/"", /*target_role_group_id*/"", /*checking_owner_party*/0, /*checking_owner_school*/0, /*checking_owner_grade*/0, /*checking_owner_unit*/0, /*checking_owner_attribute*/0, /*checking_owner_role*/0, /*target_party_type_id*/"");
INSERT INTO `m_skill_target` VALUES (/*id*/53, /*only_owner*/0, /*excluding_owner*/0, /*random_choose_count*/3, /*target_attribute_group_id*/"", /*target_member_group_id*/"", /*target_unit_group_id*/"", /*target_school_group_id*/"", /*target_school_grade_group_id*/"", /*target_role_group_id*/"", /*checking_owner_party*/1, /*checking_owner_school*/0, /*checking_owner_grade*/0, /*checking_owner_unit*/0, /*checking_owner_attribute*/0, /*checking_owner_role*/0, /*target_party_type_id*/"");
INSERT INTO `m_skill_target` VALUES (/*id*/54, /*only_owner*/0, /*excluding_owner*/0, /*random_choose_count*/9, /*target_attribute_group_id*/"", /*target_member_group_id*/"", /*target_unit_group_id*/"", /*target_school_group_id*/"", /*target_school_grade_group_id*/"", /*target_role_group_id*/"", /*checking_owner_party*/0, /*checking_owner_school*/1, /*checking_owner_grade*/0, /*checking_owner_unit*/0, /*checking_owner_attribute*/0, /*checking_owner_role*/0, /*target_party_type_id*/"");
INSERT INTO `m_skill_target` VALUES (/*id*/55, /*only_owner*/0, /*excluding_owner*/0, /*random_choose_count*/9, /*target_attribute_group_id*/"", /*target_member_group_id*/"", /*target_unit_group_id*/"", /*target_school_group_id*/"", /*target_school_grade_group_id*/"", /*target_role_group_id*/"", /*checking_owner_party*/0, /*checking_owner_school*/0, /*checking_owner_grade*/0, /*checking_owner_unit*/1, /*checking_owner_attribute*/0, /*checking_owner_role*/0, /*target_party_type_id*/"");
INSERT INTO `m_skill_target` VALUES (/*id*/56, /*only_owner*/0, /*excluding_owner*/0, /*random_choose_count*/9, /*target_attribute_group_id*/"", /*target_member_group_id*/"", /*target_unit_group_id*/"", /*target_school_group_id*/"", /*target_school_grade_group_id*/"", /*target_role_group_id*/"", /*checking_owner_party*/0, /*checking_owner_school*/0, /*checking_owner_grade*/0, /*checking_owner_unit*/0, /*checking_owner_attribute*/1, /*checking_owner_role*/0, /*target_party_type_id*/"");
INSERT INTO `m_skill_target` VALUES (/*id*/57, /*only_owner*/0, /*excluding_owner*/0, /*random_choose_count*/9, /*target_attribute_group_id*/"", /*target_member_group_id*/"", /*target_unit_group_id*/"", /*target_school_group_id*/"", /*target_school_grade_group_id*/"", /*target_role_group_id*/"", /*checking_owner_party*/0, /*checking_owner_school*/0, /*checking_owner_grade*/0, /*checking_owner_unit*/0, /*checking_owner_attribute*/0, /*checking_owner_role*/1, /*target_party_type_id*/"");
INSERT INTO `m_skill_target` VALUES (/*id*/58, /*only_owner*/0, /*excluding_owner*/0, /*random_choose_count*/9, /*target_attribute_group_id*/"", /*target_member_group_id*/"", /*target_unit_group_id*/"", /*target_school_group_id*/"", /*target_school_grade_group_id*/"", /*target_role_group_id*/"", /*checking_owner_party*/0, /*checking_owner_school*/0, /*checking_owner_grade*/0, /*checking_owner_unit*/0, /*checking_owner_attribute*/0, /*checking_owner_role*/0, /*target_party_type_id*/"");
INSERT INTO `m_skill_target` VALUES (/*id*/59, /*only_owner*/1, /*excluding_owner*/0, /*random_choose_count*/9, /*target_attribute_group_id*/"", /*target_member_group_id*/"", /*target_unit_group_id*/"", /*target_school_group_id*/"", /*target_school_grade_group_id*/"", /*target_role_group_id*/"", /*checking_owner_party*/0, /*checking_owner_school*/0, /*checking_owner_grade*/0, /*checking_owner_unit*/0, /*checking_owner_attribute*/0, /*checking_owner_role*/0, /*target_party_type_id*/"");
INSERT INTO `m_skill_target` VALUES (/*id*/60, /*only_owner*/0, /*excluding_owner*/0, /*random_choose_count*/9, /*target_attribute_group_id*/"", /*target_member_group_id*/"", /*target_unit_group_id*/"", /*target_school_group_id*/"", /*target_school_grade_group_id*/"", /*target_role_group_id*/"", /*checking_owner_party*/0, /*checking_owner_school*/0, /*checking_owner_grade*/1, /*checking_owner_unit*/0, /*checking_owner_attribute*/0, /*checking_owner_role*/0, /*target_party_type_id*/"");
INSERT INTO `m_skill_target` VALUES (/*id*/61, /*only_owner*/0, /*excluding_owner*/0, /*random_choose_count*/9, /*target_attribute_group_id*/1, /*target_member_group_id*/"", /*target_unit_group_id*/"", /*target_school_group_id*/"", /*target_school_grade_group_id*/"", /*target_role_group_id*/"", /*checking_owner_party*/0, /*checking_owner_school*/0, /*checking_owner_grade*/0, /*checking_owner_unit*/0, /*checking_owner_attribute*/0, /*checking_owner_role*/0, /*target_party_type_id*/"");
INSERT INTO `m_skill_target` VALUES (/*id*/62, /*only_owner*/0, /*excluding_owner*/0, /*random_choose_count*/9, /*target_attribute_group_id*/2, /*target_member_group_id*/"", /*target_unit_group_id*/"", /*target_school_group_id*/"", /*target_school_grade_group_id*/"", /*target_role_group_id*/"", /*checking_owner_party*/0, /*checking_owner_school*/0, /*checking_owner_grade*/0, /*checking_owner_unit*/0, /*checking_owner_attribute*/0, /*checking_owner_role*/0, /*target_party_type_id*/"");
INSERT INTO `m_skill_target` VALUES (/*id*/63, /*only_owner*/0, /*excluding_owner*/0, /*random_choose_count*/9, /*target_attribute_group_id*/3, /*target_member_group_id*/"", /*target_unit_group_id*/"", /*target_school_group_id*/"", /*target_school_grade_group_id*/"", /*target_role_group_id*/"", /*checking_owner_party*/0, /*checking_owner_school*/0, /*checking_owner_grade*/0, /*checking_owner_unit*/0, /*checking_owner_attribute*/0, /*checking_owner_role*/0, /*target_party_type_id*/"");
INSERT INTO `m_skill_target` VALUES (/*id*/64, /*only_owner*/0, /*excluding_owner*/0, /*random_choose_count*/9, /*target_attribute_group_id*/4, /*target_member_group_id*/"", /*target_unit_group_id*/"", /*target_school_group_id*/"", /*target_school_grade_group_id*/"", /*target_role_group_id*/"", /*checking_owner_party*/0, /*checking_owner_school*/0, /*checking_owner_grade*/0, /*checking_owner_unit*/0, /*checking_owner_attribute*/0, /*checking_owner_role*/0, /*target_party_type_id*/"");
INSERT INTO `m_skill_target` VALUES (/*id*/65, /*only_owner*/0, /*excluding_owner*/0, /*random_choose_count*/9, /*target_attribute_group_id*/5, /*target_member_group_id*/"", /*target_unit_group_id*/"", /*target_school_group_id*/"", /*target_school_grade_group_id*/"", /*target_role_group_id*/"", /*checking_owner_party*/0, /*checking_owner_school*/0, /*checking_owner_grade*/0, /*checking_owner_unit*/0, /*checking_owner_attribute*/0, /*checking_owner_role*/0, /*target_party_type_id*/"");
INSERT INTO `m_skill_target` VALUES (/*id*/66, /*only_owner*/0, /*excluding_owner*/0, /*random_choose_count*/9, /*target_attribute_group_id*/6, /*target_member_group_id*/"", /*target_unit_group_id*/"", /*target_school_group_id*/"", /*target_school_grade_group_id*/"", /*target_role_group_id*/"", /*checking_owner_party*/0, /*checking_owner_school*/0, /*checking_owner_grade*/0, /*checking_owner_unit*/0, /*checking_owner_attribute*/0, /*checking_owner_role*/0, /*target_party_type_id*/"");
INSERT INTO `m_skill_target` VALUES (/*id*/67, /*only_owner*/0, /*excluding_owner*/0, /*random_choose_count*/9, /*target_attribute_group_id*/7, /*target_member_group_id*/"", /*target_unit_group_id*/"", /*target_school_group_id*/"", /*target_school_grade_group_id*/"", /*target_role_group_id*/"", /*checking_owner_party*/0, /*checking_owner_school*/0, /*checking_owner_grade*/0, /*checking_owner_unit*/0, /*checking_owner_attribute*/0, /*checking_owner_role*/0, /*target_party_type_id*/"");
INSERT INTO `m_skill_target` VALUES (/*id*/68, /*only_owner*/0, /*excluding_owner*/0, /*random_choose_count*/9, /*target_attribute_group_id*/"", /*target_member_group_id*/"", /*target_unit_group_id*/"", /*target_school_group_id*/"", /*target_school_grade_group_id*/"", /*target_role_group_id*/5, /*checking_owner_party*/0, /*checking_owner_school*/0, /*checking_owner_grade*/0, /*checking_owner_unit*/0, /*checking_owner_attribute*/0, /*checking_owner_role*/0, /*target_party_type_id*/"");
INSERT INTO `m_skill_target` VALUES (/*id*/69, /*only_owner*/0, /*excluding_owner*/0, /*random_choose_count*/9, /*target_attribute_group_id*/"", /*target_member_group_id*/"", /*target_unit_group_id*/"", /*target_school_group_id*/"", /*target_school_grade_group_id*/1, /*target_role_group_id*/"", /*checking_owner_party*/0, /*checking_owner_school*/0, /*checking_owner_grade*/0, /*checking_owner_unit*/0, /*checking_owner_attribute*/0, /*checking_owner_role*/0, /*target_party_type_id*/"");
INSERT INTO `m_skill_target` VALUES (/*id*/70, /*only_owner*/0, /*excluding_owner*/0, /*random_choose_count*/9, /*target_attribute_group_id*/"", /*target_member_group_id*/"", /*target_unit_group_id*/"", /*target_school_group_id*/"", /*target_school_grade_group_id*/2, /*target_role_group_id*/"", /*checking_owner_party*/0, /*checking_owner_school*/0, /*checking_owner_grade*/0, /*checking_owner_unit*/0, /*checking_owner_attribute*/0, /*checking_owner_role*/0, /*target_party_type_id*/"");
INSERT INTO `m_skill_target` VALUES (/*id*/71, /*only_owner*/0, /*excluding_owner*/0, /*random_choose_count*/9, /*target_attribute_group_id*/"", /*target_member_group_id*/"", /*target_unit_group_id*/"", /*target_school_group_id*/"", /*target_school_grade_group_id*/3, /*target_role_group_id*/"", /*checking_owner_party*/0, /*checking_owner_school*/0, /*checking_owner_grade*/0, /*checking_owner_unit*/0, /*checking_owner_attribute*/0, /*checking_owner_role*/0, /*target_party_type_id*/"");
INSERT INTO `m_skill_target` VALUES (/*id*/72, /*only_owner*/0, /*excluding_owner*/0, /*random_choose_count*/9, /*target_attribute_group_id*/8, /*target_member_group_id*/"", /*target_unit_group_id*/"", /*target_school_group_id*/"", /*target_school_grade_group_id*/"", /*target_role_group_id*/"", /*checking_owner_party*/0, /*checking_owner_school*/0, /*checking_owner_grade*/0, /*checking_owner_unit*/0, /*checking_owner_attribute*/0, /*checking_owner_role*/0, /*target_party_type_id*/"");
INSERT INTO `m_skill_target` VALUES (/*id*/73, /*only_owner*/0, /*excluding_owner*/0, /*random_choose_count*/9, /*target_attribute_group_id*/9, /*target_member_group_id*/"", /*target_unit_group_id*/"", /*target_school_group_id*/"", /*target_school_grade_group_id*/"", /*target_role_group_id*/"", /*checking_owner_party*/0, /*checking_owner_school*/0, /*checking_owner_grade*/0, /*checking_owner_unit*/0, /*checking_owner_attribute*/0, /*checking_owner_role*/0, /*target_party_type_id*/"");
INSERT INTO `m_skill_target` VALUES (/*id*/74, /*only_owner*/0, /*excluding_owner*/0, /*random_choose_count*/9, /*target_attribute_group_id*/10, /*target_member_group_id*/"", /*target_unit_group_id*/"", /*target_school_group_id*/"", /*target_school_grade_group_id*/"", /*target_role_group_id*/"", /*checking_owner_party*/0, /*checking_owner_school*/0, /*checking_owner_grade*/0, /*checking_owner_unit*/0, /*checking_owner_attribute*/0, /*checking_owner_role*/0, /*target_party_type_id*/"");
INSERT INTO `m_skill_target` VALUES (/*id*/75, /*only_owner*/0, /*excluding_owner*/0, /*random_choose_count*/9, /*target_attribute_group_id*/11, /*target_member_group_id*/"", /*target_unit_group_id*/"", /*target_school_group_id*/"", /*target_school_grade_group_id*/"", /*target_role_group_id*/"", /*checking_owner_party*/0, /*checking_owner_school*/0, /*checking_owner_grade*/0, /*checking_owner_unit*/0, /*checking_owner_attribute*/0, /*checking_owner_role*/0, /*target_party_type_id*/"");
INSERT INTO `m_skill_target` VALUES (/*id*/76, /*only_owner*/0, /*excluding_owner*/0, /*random_choose_count*/9, /*target_attribute_group_id*/12, /*target_member_group_id*/"", /*target_unit_group_id*/"", /*target_school_group_id*/"", /*target_school_grade_group_id*/"", /*target_role_group_id*/"", /*checking_owner_party*/0, /*checking_owner_school*/0, /*checking_owner_grade*/0, /*checking_owner_unit*/0, /*checking_owner_attribute*/0, /*checking_owner_role*/0, /*target_party_type_id*/"");
INSERT INTO `m_skill_target` VALUES (/*id*/77, /*only_owner*/0, /*excluding_owner*/0, /*random_choose_count*/9, /*target_attribute_group_id*/"", /*target_member_group_id*/"", /*target_unit_group_id*/"", /*target_school_group_id*/"", /*target_school_grade_group_id*/"", /*target_role_group_id*/6, /*checking_owner_party*/0, /*checking_owner_school*/0, /*checking_owner_grade*/0, /*checking_owner_unit*/0, /*checking_owner_attribute*/0, /*checking_owner_role*/0, /*target_party_type_id*/"");
INSERT INTO `m_skill_target` VALUES (/*id*/78, /*only_owner*/0, /*excluding_owner*/0, /*random_choose_count*/9, /*target_attribute_group_id*/"", /*target_member_group_id*/"", /*target_unit_group_id*/"", /*target_school_group_id*/"", /*target_school_grade_group_id*/"", /*target_role_group_id*/7, /*checking_owner_party*/0, /*checking_owner_school*/0, /*checking_owner_grade*/0, /*checking_owner_unit*/0, /*checking_owner_attribute*/0, /*checking_owner_role*/0, /*target_party_type_id*/"");
INSERT INTO `m_skill_target` VALUES (/*id*/79, /*only_owner*/0, /*excluding_owner*/0, /*random_choose_count*/9, /*target_attribute_group_id*/"", /*target_member_group_id*/"", /*target_unit_group_id*/"", /*target_school_group_id*/"", /*target_school_grade_group_id*/"", /*target_role_group_id*/8, /*checking_owner_party*/0, /*checking_owner_school*/0, /*checking_owner_grade*/0, /*checking_owner_unit*/0, /*checking_owner_attribute*/0, /*checking_owner_role*/0, /*target_party_type_id*/"");
INSERT INTO `m_skill_target` VALUES (/*id*/80, /*only_owner*/0, /*excluding_owner*/0, /*random_choose_count*/9, /*target_attribute_group_id*/"", /*target_member_group_id*/"", /*target_unit_group_id*/"", /*target_school_group_id*/"", /*target_school_grade_group_id*/"", /*target_role_group_id*/"", /*checking_owner_party*/0, /*checking_owner_school*/0, /*checking_owner_grade*/0, /*checking_owner_unit*/0, /*checking_owner_attribute*/0, /*checking_owner_role*/0, /*target_party_type_id*/0);
INSERT INTO `m_skill_target` VALUES (/*id*/81, /*only_owner*/0, /*excluding_owner*/0, /*random_choose_count*/9, /*target_attribute_group_id*/"", /*target_member_group_id*/"", /*target_unit_group_id*/"", /*target_school_group_id*/"", /*target_school_grade_group_id*/"", /*target_role_group_id*/"", /*checking_owner_party*/0, /*checking_owner_school*/0, /*checking_owner_grade*/0, /*checking_owner_unit*/0, /*checking_owner_attribute*/0, /*checking_owner_role*/0, /*target_party_type_id*/1);
INSERT INTO `m_skill_target` VALUES (/*id*/82, /*only_owner*/0, /*excluding_owner*/0, /*random_choose_count*/9, /*target_attribute_group_id*/"", /*target_member_group_id*/"", /*target_unit_group_id*/"", /*target_school_group_id*/"", /*target_school_grade_group_id*/"", /*target_role_group_id*/"", /*checking_owner_party*/0, /*checking_owner_school*/0, /*checking_owner_grade*/0, /*checking_owner_unit*/0, /*checking_owner_attribute*/0, /*checking_owner_role*/0, /*target_party_type_id*/2);
INSERT INTO `m_skill_target` VALUES (/*id*/83, /*only_owner*/0, /*excluding_owner*/0, /*random_choose_count*/9, /*target_attribute_group_id*/"", /*target_member_group_id*/"", /*target_unit_group_id*/"", /*target_school_group_id*/"", /*target_school_grade_group_id*/"", /*target_role_group_id*/"", /*checking_owner_party*/0, /*checking_owner_school*/0, /*checking_owner_grade*/0, /*checking_owner_unit*/0, /*checking_owner_attribute*/0, /*checking_owner_role*/0, /*target_party_type_id*/3);
INSERT INTO `m_skill_target` VALUES (/*id*/84, /*only_owner*/0, /*excluding_owner*/0, /*random_choose_count*/9, /*target_attribute_group_id*/"", /*target_member_group_id*/"", /*target_unit_group_id*/"", /*target_school_group_id*/"", /*target_school_grade_group_id*/"", /*target_role_group_id*/"", /*checking_owner_party*/0, /*checking_owner_school*/0, /*checking_owner_grade*/0, /*checking_owner_unit*/0, /*checking_owner_attribute*/0, /*checking_owner_role*/0, /*target_party_type_id*/4);
INSERT INTO `m_skill_target` VALUES (/*id*/85, /*only_owner*/0, /*excluding_owner*/0, /*random_choose_count*/9, /*target_attribute_group_id*/"", /*target_member_group_id*/"", /*target_unit_group_id*/"", /*target_school_group_id*/"", /*target_school_grade_group_id*/"", /*target_role_group_id*/"", /*checking_owner_party*/0, /*checking_owner_school*/0, /*checking_owner_grade*/0, /*checking_owner_unit*/0, /*checking_owner_attribute*/0, /*checking_owner_role*/0, /*target_party_type_id*/5);
INSERT INTO `m_skill_target` VALUES (/*id*/86, /*only_owner*/0, /*excluding_owner*/0, /*random_choose_count*/9, /*target_attribute_group_id*/"", /*target_member_group_id*/"", /*target_unit_group_id*/"", /*target_school_group_id*/4, /*target_school_grade_group_id*/"", /*target_role_group_id*/"", /*checking_owner_party*/0, /*checking_owner_school*/0, /*checking_owner_grade*/0, /*checking_owner_unit*/0, /*checking_owner_attribute*/0, /*checking_owner_role*/0, /*target_party_type_id*/"");
INSERT INTO `m_skill_target` VALUES (/*id*/87, /*only_owner*/0, /*excluding_owner*/0, /*random_choose_count*/9, /*target_attribute_group_id*/"", /*target_member_group_id*/"", /*target_unit_group_id*/"", /*target_school_group_id*/"", /*target_school_grade_group_id*/"", /*target_role_group_id*/9, /*checking_owner_party*/0, /*checking_owner_school*/0, /*checking_owner_grade*/0, /*checking_owner_unit*/0, /*checking_owner_attribute*/0, /*checking_owner_role*/0, /*target_party_type_id*/"");
INSERT INTO `m_skill_target` VALUES (/*id*/88, /*only_owner*/0, /*excluding_owner*/0, /*random_choose_count*/9, /*target_attribute_group_id*/"", /*target_member_group_id*/"", /*target_unit_group_id*/"", /*target_school_group_id*/"", /*target_school_grade_group_id*/"", /*target_role_group_id*/10, /*checking_owner_party*/0, /*checking_owner_school*/0, /*checking_owner_grade*/0, /*checking_owner_unit*/0, /*checking_owner_attribute*/0, /*checking_owner_role*/0, /*target_party_type_id*/"");
INSERT INTO `m_skill_target` VALUES (/*id*/89, /*only_owner*/0, /*excluding_owner*/0, /*random_choose_count*/9, /*target_attribute_group_id*/"", /*target_member_group_id*/"", /*target_unit_group_id*/"", /*target_school_group_id*/"", /*target_school_grade_group_id*/"", /*target_role_group_id*/11, /*checking_owner_party*/0, /*checking_owner_school*/0, /*checking_owner_grade*/0, /*checking_owner_unit*/0, /*checking_owner_attribute*/0, /*checking_owner_role*/0, /*target_party_type_id*/"");
INSERT INTO `m_skill_target` VALUES (/*id*/90, /*only_owner*/0, /*excluding_owner*/0, /*random_choose_count*/9, /*target_attribute_group_id*/"", /*target_member_group_id*/"", /*target_unit_group_id*/"", /*target_school_group_id*/"", /*target_school_grade_group_id*/"", /*target_role_group_id*/12, /*checking_owner_party*/0, /*checking_owner_school*/0, /*checking_owner_grade*/0, /*checking_owner_unit*/0, /*checking_owner_attribute*/0, /*checking_owner_role*/0, /*target_party_type_id*/"");
INSERT INTO `m_skill_target` VALUES (/*id*/91, /*only_owner*/0, /*excluding_owner*/0, /*random_choose_count*/9, /*target_attribute_group_id*/"", /*target_member_group_id*/"", /*target_unit_group_id*/"", /*target_school_group_id*/"", /*target_school_grade_group_id*/"", /*target_role_group_id*/13, /*checking_owner_party*/0, /*checking_owner_school*/0, /*checking_owner_grade*/0, /*checking_owner_unit*/0, /*checking_owner_attribute*/0, /*checking_owner_role*/0, /*target_party_type_id*/"");
INSERT INTO `m_skill_target` VALUES (/*id*/92, /*only_owner*/0, /*excluding_owner*/0, /*random_choose_count*/9, /*target_attribute_group_id*/"", /*target_member_group_id*/"", /*target_unit_group_id*/"", /*target_school_group_id*/"", /*target_school_grade_group_id*/"", /*target_role_group_id*/14, /*checking_owner_party*/0, /*checking_owner_school*/0, /*checking_owner_grade*/0, /*checking_owner_unit*/0, /*checking_owner_attribute*/0, /*checking_owner_role*/0, /*target_party_type_id*/"");
INSERT INTO `m_skill_target` VALUES (/*id*/93, /*only_owner*/0, /*excluding_owner*/0, /*random_choose_count*/9, /*target_attribute_group_id*/"", /*target_member_group_id*/"", /*target_unit_group_id*/"", /*target_school_group_id*/"", /*target_school_grade_group_id*/"", /*target_role_group_id*/9, /*checking_owner_party*/0, /*checking_owner_school*/0, /*checking_owner_grade*/0, /*checking_owner_unit*/0, /*checking_owner_attribute*/0, /*checking_owner_role*/0, /*target_party_type_id*/"");
INSERT INTO `m_skill_target` VALUES (/*id*/94, /*only_owner*/0, /*excluding_owner*/0, /*random_choose_count*/9, /*target_attribute_group_id*/"", /*target_member_group_id*/"", /*target_unit_group_id*/"", /*target_school_group_id*/"", /*target_school_grade_group_id*/"", /*target_role_group_id*/10, /*checking_owner_party*/0, /*checking_owner_school*/0, /*checking_owner_grade*/0, /*checking_owner_unit*/0, /*checking_owner_attribute*/0, /*checking_owner_role*/0, /*target_party_type_id*/"");
INSERT INTO `m_skill_target` VALUES (/*id*/95, /*only_owner*/0, /*excluding_owner*/0, /*random_choose_count*/9, /*target_attribute_group_id*/"", /*target_member_group_id*/"", /*target_unit_group_id*/"", /*target_school_group_id*/"", /*target_school_grade_group_id*/"", /*target_role_group_id*/11, /*checking_owner_party*/0, /*checking_owner_school*/0, /*checking_owner_grade*/0, /*checking_owner_unit*/0, /*checking_owner_attribute*/0, /*checking_owner_role*/0, /*target_party_type_id*/"");
INSERT INTO `m_skill_target` VALUES (/*id*/96, /*only_owner*/0, /*excluding_owner*/0, /*random_choose_count*/9, /*target_attribute_group_id*/"", /*target_member_group_id*/"", /*target_unit_group_id*/"", /*target_school_group_id*/"", /*target_school_grade_group_id*/"", /*target_role_group_id*/12, /*checking_owner_party*/0, /*checking_owner_school*/0, /*checking_owner_grade*/0, /*checking_owner_unit*/0, /*checking_owner_attribute*/0, /*checking_owner_role*/0, /*target_party_type_id*/"");
INSERT INTO `m_skill_target` VALUES (/*id*/97, /*only_owner*/0, /*excluding_owner*/0, /*random_choose_count*/9, /*target_attribute_group_id*/"", /*target_member_group_id*/"", /*target_unit_group_id*/"", /*target_school_group_id*/"", /*target_school_grade_group_id*/"", /*target_role_group_id*/13, /*checking_owner_party*/0, /*checking_owner_school*/0, /*checking_owner_grade*/0, /*checking_owner_unit*/0, /*checking_owner_attribute*/0, /*checking_owner_role*/0, /*target_party_type_id*/"");
INSERT INTO `m_skill_target` VALUES (/*id*/98, /*only_owner*/0, /*excluding_owner*/0, /*random_choose_count*/9, /*target_attribute_group_id*/"", /*target_member_group_id*/"", /*target_unit_group_id*/"", /*target_school_group_id*/"", /*target_school_grade_group_id*/"", /*target_role_group_id*/14, /*checking_owner_party*/0, /*checking_owner_school*/0, /*checking_owner_grade*/0, /*checking_owner_unit*/0, /*checking_owner_attribute*/0, /*checking_owner_role*/0, /*target_party_type_id*/"");
