CREATE TABLE m_story_main_chapter(
  id INTEGER NOT NULL,
  story_main_part_master_id INTEGER NOT NULL,
  title TEXT NOT NULL,
  description TEXT NOT NULL,
  thumbnail_asset_path TEXT NOT NULL,
  background_asset_path TEXT NOT NULL,
  hard_background_asset_path TEXT,
  bgm_asset_path TEXT,
  PRIMARY KEY (id),
  FOREIGN KEY (story_main_part_master_id) REFERENCES m_story_main_part(id)
);
INSERT INTO `m_story_main_chapter` VALUES (/*id*/1, /*story_main_part_master_id*/1, /*title*/"m.story_main_chapter_title_1", /*description*/"m.story_main_chapter_description_1", /*thumbnail_asset_path*/"k~X", /*background_asset_path*/"/4", /*hard_background_asset_path*/"", /*bgm_asset_path*/"");
INSERT INTO `m_story_main_chapter` VALUES (/*id*/2, /*story_main_part_master_id*/1, /*title*/"m.story_main_chapter_title_2", /*description*/"m.story_main_chapter_description_2", /*thumbnail_asset_path*/"4MA", /*background_asset_path*/"LT", /*hard_background_asset_path*/"", /*bgm_asset_path*/"");
INSERT INTO `m_story_main_chapter` VALUES (/*id*/3, /*story_main_part_master_id*/1, /*title*/"m.story_main_chapter_title_3", /*description*/"m.story_main_chapter_description_3", /*thumbnail_asset_path*/"k?(", /*background_asset_path*/"u\", /*hard_background_asset_path*/"", /*bgm_asset_path*/"");
INSERT INTO `m_story_main_chapter` VALUES (/*id*/4, /*story_main_part_master_id*/1, /*title*/"m.story_main_chapter_title_4", /*description*/"m.story_main_chapter_description_4", /*thumbnail_asset_path*/"k=e", /*background_asset_path*/"Gd", /*hard_background_asset_path*/"", /*bgm_asset_path*/"");
INSERT INTO `m_story_main_chapter` VALUES (/*id*/5, /*story_main_part_master_id*/1, /*title*/"m.story_main_chapter_title_5", /*description*/"m.story_main_chapter_description_5", /*thumbnail_asset_path*/"sj;", /*background_asset_path*/"o@", /*hard_background_asset_path*/"", /*bgm_asset_path*/"");
INSERT INTO `m_story_main_chapter` VALUES (/*id*/6, /*story_main_part_master_id*/1, /*title*/"m.story_main_chapter_title_6", /*description*/"m.story_main_chapter_description_6", /*thumbnail_asset_path*/"B`x", /*background_asset_path*/"Bg", /*hard_background_asset_path*/"", /*bgm_asset_path*/"");
INSERT INTO `m_story_main_chapter` VALUES (/*id*/7, /*story_main_part_master_id*/1, /*title*/"m.story_main_chapter_title_7", /*description*/"m.story_main_chapter_description_7", /*thumbnail_asset_path*/"/ia", /*background_asset_path*/"S3", /*hard_background_asset_path*/"", /*bgm_asset_path*/"");
INSERT INTO `m_story_main_chapter` VALUES (/*id*/8, /*story_main_part_master_id*/1, /*title*/"m.story_main_chapter_title_8", /*description*/"m.story_main_chapter_description_8", /*thumbnail_asset_path*/"'n>", /*background_asset_path*/"wc", /*hard_background_asset_path*/"", /*bgm_asset_path*/"");
INSERT INTO `m_story_main_chapter` VALUES (/*id*/9, /*story_main_part_master_id*/1, /*title*/"m.story_main_chapter_title_9", /*description*/"m.story_main_chapter_description_9", /*thumbnail_asset_path*/"<.T", /*background_asset_path*/"'\", /*hard_background_asset_path*/"", /*bgm_asset_path*/"");
INSERT INTO `m_story_main_chapter` VALUES (/*id*/10, /*story_main_part_master_id*/1, /*title*/"m.story_main_chapter_title_10", /*description*/"m.story_main_chapter_description_10", /*thumbnail_asset_path*/"W(^", /*background_asset_path*/",a", /*hard_background_asset_path*/"", /*bgm_asset_path*/"");
INSERT INTO `m_story_main_chapter` VALUES (/*id*/11, /*story_main_part_master_id*/1, /*title*/"m.story_main_chapter_title_11", /*description*/"m.story_main_chapter_description_11", /*thumbnail_asset_path*/"(5:", /*background_asset_path*/"M)", /*hard_background_asset_path*/"", /*bgm_asset_path*/"");
INSERT INTO `m_story_main_chapter` VALUES (/*id*/12, /*story_main_part_master_id*/1, /*title*/"m.story_main_chapter_title_12", /*description*/"m.story_main_chapter_description_12", /*thumbnail_asset_path*/"UZA", /*background_asset_path*/">}U", /*hard_background_asset_path*/"", /*bgm_asset_path*/"");
INSERT INTO `m_story_main_chapter` VALUES (/*id*/13, /*story_main_part_master_id*/1, /*title*/"m.story_main_chapter_title_13", /*description*/"m.story_main_chapter_description_13", /*thumbnail_asset_path*/"N'y", /*background_asset_path*/"[n", /*hard_background_asset_path*/"", /*bgm_asset_path*/"");
INSERT INTO `m_story_main_chapter` VALUES (/*id*/14, /*story_main_part_master_id*/1, /*title*/"m.story_main_chapter_title_14", /*description*/"m.story_main_chapter_description_14", /*thumbnail_asset_path*/".rE", /*background_asset_path*/"Yz", /*hard_background_asset_path*/"", /*bgm_asset_path*/"");
INSERT INTO `m_story_main_chapter` VALUES (/*id*/15, /*story_main_part_master_id*/1, /*title*/"m.story_main_chapter_title_15", /*description*/"m.story_main_chapter_description_15", /*thumbnail_asset_path*/"UMJ", /*background_asset_path*/"LT", /*hard_background_asset_path*/"", /*bgm_asset_path*/"");
INSERT INTO `m_story_main_chapter` VALUES (/*id*/16, /*story_main_part_master_id*/1, /*title*/"m.story_main_chapter_title_16", /*description*/"m.story_main_chapter_description_16", /*thumbnail_asset_path*/"uli", /*background_asset_path*/"'\", /*hard_background_asset_path*/"", /*bgm_asset_path*/"");
INSERT INTO `m_story_main_chapter` VALUES (/*id*/17, /*story_main_part_master_id*/1, /*title*/"m.story_main_chapter_title_17", /*description*/"m.story_main_chapter_description_17", /*thumbnail_asset_path*/"/NU", /*background_asset_path*/"7z<", /*hard_background_asset_path*/"", /*bgm_asset_path*/"");
INSERT INTO `m_story_main_chapter` VALUES (/*id*/18, /*story_main_part_master_id*/99991, /*title*/"m.story_main_chapter_title_18", /*description*/"m.story_main_chapter_description_18", /*thumbnail_asset_path*/"*i7", /*background_asset_path*/"^]V", /*hard_background_asset_path*/"", /*bgm_asset_path*/"");
INSERT INTO `m_story_main_chapter` VALUES (/*id*/19, /*story_main_part_master_id*/99991, /*title*/"m.story_main_chapter_title_19", /*description*/"m.story_main_chapter_description_19", /*thumbnail_asset_path*/"P@l", /*background_asset_path*/"CBi", /*hard_background_asset_path*/"", /*bgm_asset_path*/"");
INSERT INTO `m_story_main_chapter` VALUES (/*id*/20, /*story_main_part_master_id*/2, /*title*/"m.story_main_chapter_title_20", /*description*/"m.story_main_chapter_description_20", /*thumbnail_asset_path*/"qi5", /*background_asset_path*/"Yz", /*hard_background_asset_path*/"Cn*", /*bgm_asset_path*/"");
INSERT INTO `m_story_main_chapter` VALUES (/*id*/21, /*story_main_part_master_id*/2, /*title*/"m.story_main_chapter_title_21", /*description*/"m.story_main_chapter_description_21", /*thumbnail_asset_path*/"j5!", /*background_asset_path*/",a", /*hard_background_asset_path*/"+.f", /*bgm_asset_path*/"");
INSERT INTO `m_story_main_chapter` VALUES (/*id*/22, /*story_main_part_master_id*/2, /*title*/"m.story_main_chapter_title_22", /*description*/"m.story_main_chapter_description_22", /*thumbnail_asset_path*/"t3>", /*background_asset_path*/"Yz", /*hard_background_asset_path*/"Cn*", /*bgm_asset_path*/"");
INSERT INTO `m_story_main_chapter` VALUES (/*id*/23, /*story_main_part_master_id*/2, /*title*/"m.story_main_chapter_title_23", /*description*/"m.story_main_chapter_description_23", /*thumbnail_asset_path*/"(^~", /*background_asset_path*/"VI", /*hard_background_asset_path*/"iKo", /*bgm_asset_path*/"");
INSERT INTO `m_story_main_chapter` VALUES (/*id*/24, /*story_main_part_master_id*/2, /*title*/"m.story_main_chapter_title_24", /*description*/"m.story_main_chapter_description_24", /*thumbnail_asset_path*/"qQR", /*background_asset_path*/"o\"", /*hard_background_asset_path*/"U#g", /*bgm_asset_path*/"");
INSERT INTO `m_story_main_chapter` VALUES (/*id*/25, /*story_main_part_master_id*/2, /*title*/"m.story_main_chapter_title_25", /*description*/"m.story_main_chapter_description_25", /*thumbnail_asset_path*/"We=", /*background_asset_path*/"x|", /*hard_background_asset_path*/"?bt", /*bgm_asset_path*/"");
INSERT INTO `m_story_main_chapter` VALUES (/*id*/26, /*story_main_part_master_id*/2, /*title*/"m.story_main_chapter_title_26", /*description*/"m.story_main_chapter_description_26", /*thumbnail_asset_path*/"GCl", /*background_asset_path*/"^]V", /*hard_background_asset_path*/"93H", /*bgm_asset_path*/"");
INSERT INTO `m_story_main_chapter` VALUES (/*id*/27, /*story_main_part_master_id*/2, /*title*/"m.story_main_chapter_title_27", /*description*/"m.story_main_chapter_description_27", /*thumbnail_asset_path*/"\vm", /*background_asset_path*/"Yz", /*hard_background_asset_path*/"Cn*", /*bgm_asset_path*/"");
INSERT INTO `m_story_main_chapter` VALUES (/*id*/28, /*story_main_part_master_id*/2, /*title*/"m.story_main_chapter_title_28", /*description*/"m.story_main_chapter_description_28", /*thumbnail_asset_path*/"k?R", /*background_asset_path*/"LT", /*hard_background_asset_path*/"J}", /*bgm_asset_path*/"");
INSERT INTO `m_story_main_chapter` VALUES (/*id*/29, /*story_main_part_master_id*/2, /*title*/"m.story_main_chapter_title_29", /*description*/"m.story_main_chapter_description_29", /*thumbnail_asset_path*/"`b5", /*background_asset_path*/"Yz", /*hard_background_asset_path*/"Cn*", /*bgm_asset_path*/"");
INSERT INTO `m_story_main_chapter` VALUES (/*id*/30, /*story_main_part_master_id*/2, /*title*/"m.story_main_chapter_title_30", /*description*/"m.story_main_chapter_description_30", /*thumbnail_asset_path*/"[u+", /*background_asset_path*/"Cb", /*hard_background_asset_path*/"oN", /*bgm_asset_path*/"");
INSERT INTO `m_story_main_chapter` VALUES (/*id*/31, /*story_main_part_master_id*/99992, /*title*/"m.story_main_chapter_title_31", /*description*/"m.story_main_chapter_description_31", /*thumbnail_asset_path*/"`gh", /*background_asset_path*/"h-", /*hard_background_asset_path*/"RHC", /*bgm_asset_path*/"");
INSERT INTO `m_story_main_chapter` VALUES (/*id*/32, /*story_main_part_master_id*/3, /*title*/"m.story_main_chapter_title_32", /*description*/"m.story_main_chapter_description_32", /*thumbnail_asset_path*/"_[;", /*background_asset_path*/"/4", /*hard_background_asset_path*/"%9", /*bgm_asset_path*/"");
INSERT INTO `m_story_main_chapter` VALUES (/*id*/33, /*story_main_part_master_id*/3, /*title*/"m.story_main_chapter_title_33", /*description*/"m.story_main_chapter_description_33", /*thumbnail_asset_path*/"pom", /*background_asset_path*/"Bg", /*hard_background_asset_path*/".l", /*bgm_asset_path*/"");
INSERT INTO `m_story_main_chapter` VALUES (/*id*/34, /*story_main_part_master_id*/3, /*title*/"m.story_main_chapter_title_34", /*description*/"m.story_main_chapter_description_34", /*thumbnail_asset_path*/"P!p", /*background_asset_path*/"<N", /*hard_background_asset_path*/"U,s", /*bgm_asset_path*/"");
INSERT INTO `m_story_main_chapter` VALUES (/*id*/35, /*story_main_part_master_id*/3, /*title*/"m.story_main_chapter_title_35", /*description*/"m.story_main_chapter_description_35", /*thumbnail_asset_path*/"`[p", /*background_asset_path*/"Gd", /*hard_background_asset_path*/"zJ", /*bgm_asset_path*/"");
INSERT INTO `m_story_main_chapter` VALUES (/*id*/36, /*story_main_part_master_id*/3, /*title*/"m.story_main_chapter_title_36", /*description*/"m.story_main_chapter_description_36", /*thumbnail_asset_path*/"wtW", /*background_asset_path*/"LT", /*hard_background_asset_path*/"J}", /*bgm_asset_path*/"");
INSERT INTO `m_story_main_chapter` VALUES (/*id*/37, /*story_main_part_master_id*/3, /*title*/"m.story_main_chapter_title_37", /*description*/"m.story_main_chapter_description_37", /*thumbnail_asset_path*/"n7z", /*background_asset_path*/"jz&", /*hard_background_asset_path*/")xJ", /*bgm_asset_path*/"");
INSERT INTO `m_story_main_chapter` VALUES (/*id*/38, /*story_main_part_master_id*/3, /*title*/"m.story_main_chapter_title_38", /*description*/"m.story_main_chapter_description_38", /*thumbnail_asset_path*/"'b`", /*background_asset_path*/"['", /*hard_background_asset_path*/"K}", /*bgm_asset_path*/"");
INSERT INTO `m_story_main_chapter` VALUES (/*id*/39, /*story_main_part_master_id*/3, /*title*/"m.story_main_chapter_title_39", /*description*/"m.story_main_chapter_description_39", /*thumbnail_asset_path*/"*yU", /*background_asset_path*/"Q@", /*hard_background_asset_path*/"(?", /*bgm_asset_path*/"");
INSERT INTO `m_story_main_chapter` VALUES (/*id*/40, /*story_main_part_master_id*/3, /*title*/"m.story_main_chapter_title_40", /*description*/"m.story_main_chapter_description_40", /*thumbnail_asset_path*/"`qV", /*background_asset_path*/"|N~", /*hard_background_asset_path*/"bIO", /*bgm_asset_path*/"");
INSERT INTO `m_story_main_chapter` VALUES (/*id*/41, /*story_main_part_master_id*/3, /*title*/"m.story_main_chapter_title_41", /*description*/"m.story_main_chapter_description_41", /*thumbnail_asset_path*/"7jv", /*background_asset_path*/"6}Q", /*hard_background_asset_path*/"}E1", /*bgm_asset_path*/"");
INSERT INTO `m_story_main_chapter` VALUES (/*id*/42, /*story_main_part_master_id*/99993, /*title*/"m.story_main_chapter_title_42", /*description*/"m.story_main_chapter_description_42", /*thumbnail_asset_path*/"\~^", /*background_asset_path*/"Bg", /*hard_background_asset_path*/".l", /*bgm_asset_path*/"");
INSERT INTO `m_story_main_chapter` VALUES (/*id*/43, /*story_main_part_master_id*/99993, /*title*/"m.story_main_chapter_title_43", /*description*/"m.story_main_chapter_description_43", /*thumbnail_asset_path*/"Gzw", /*background_asset_path*/"_#:", /*hard_background_asset_path*/"3',", /*bgm_asset_path*/"");
INSERT INTO `m_story_main_chapter` VALUES (/*id*/44, /*story_main_part_master_id*/4, /*title*/"m.story_main_chapter_title_44", /*description*/"m.story_main_chapter_description_44", /*thumbnail_asset_path*/"]ce", /*background_asset_path*/"[V$", /*hard_background_asset_path*/"", /*bgm_asset_path*/"");
INSERT INTO `m_story_main_chapter` VALUES (/*id*/45, /*story_main_part_master_id*/4, /*title*/"m.story_main_chapter_title_45", /*description*/"m.story_main_chapter_description_45", /*thumbnail_asset_path*/"_>E", /*background_asset_path*/">}U", /*hard_background_asset_path*/"", /*bgm_asset_path*/"");
