CREATE TABLE m_story_linkage_cell(
  id INTEGER NOT NULL,
  story_linkage_chapter_master_id INTEGER NOT NULL,
  display_order INTEGER NOT NULL,
  type INTEGER NOT NULL,
  title TEXT,
  summary TEXT,
  member_group INTEGER NOT NULL,
  thumbnail_asset_path TEXT,
  popup_thumbnail_asset_path TEXT,
  scenario_script_asset_path TEXT,
  live_difficulty_id INTEGER,
  end_at INTEGER,
  is_lock INTEGER NOT NULL,
  lock_text TEXT,
  label TEXT,
  show_progress_line INTEGER NOT NULL,
  additional_rewards_end_at INTEGER,
  reward_asort_name TEXT,
  PRIMARY KEY (id),
  FOREIGN KEY (story_linkage_chapter_master_id) REFERENCES m_story_linkage_chapter(id)
);
INSERT INTO `m_story_linkage_cell` VALUES (/*id*/9000001, /*story_linkage_chapter_master_id*/900001, /*display_order*/1, /*type*/1, /*title*/"m.story_linkage_title_900001_1", /*summary*/"m.story_linkage_summary_900001_1", /*member_group*/100, /*thumbnail_asset_path*/"D~!", /*popup_thumbnail_asset_path*/"k]]", /*scenario_script_asset_path*/"ES/9201/es_9201_01", /*live_difficulty_id*/"", /*end_at*/"", /*is_lock*/0, /*lock_text*/"", /*label*/"m.story_linkage_cell_additional_rewards", /*show_progress_line*/0, /*additional_rewards_end_at*/1614060000, /*reward_asort_name*/"m.story_linkage_cell_first_reward_name_900001_1");
INSERT INTO `m_story_linkage_cell` VALUES (/*id*/9000002, /*story_linkage_chapter_master_id*/900001, /*display_order*/2, /*type*/1, /*title*/"m.story_linkage_title_900001_2", /*summary*/"m.story_linkage_summary_900001_2", /*member_group*/100, /*thumbnail_asset_path*/"i!y", /*popup_thumbnail_asset_path*/"$.a", /*scenario_script_asset_path*/"ES/9201/es_9201_02", /*live_difficulty_id*/"", /*end_at*/"", /*is_lock*/0, /*lock_text*/"", /*label*/"m.story_linkage_cell_additional_rewards", /*show_progress_line*/0, /*additional_rewards_end_at*/1614664800, /*reward_asort_name*/"m.story_linkage_cell_first_reward_name_900001_2");
INSERT INTO `m_story_linkage_cell` VALUES (/*id*/9000003, /*story_linkage_chapter_master_id*/900001, /*display_order*/3, /*type*/1, /*title*/"m.story_linkage_title_900001_3", /*summary*/"m.story_linkage_summary_900001_3", /*member_group*/100, /*thumbnail_asset_path*/";S&", /*popup_thumbnail_asset_path*/"V$.", /*scenario_script_asset_path*/"ES/9201/es_9201_03", /*live_difficulty_id*/"", /*end_at*/"", /*is_lock*/0, /*lock_text*/"", /*label*/"m.story_linkage_cell_additional_rewards", /*show_progress_line*/0, /*additional_rewards_end_at*/1615269600, /*reward_asort_name*/"m.story_linkage_cell_first_reward_name_900001_3");
INSERT INTO `m_story_linkage_cell` VALUES (/*id*/9000004, /*story_linkage_chapter_master_id*/900001, /*display_order*/4, /*type*/1, /*title*/"m.story_linkage_title_900001_4", /*summary*/"m.story_linkage_summary_900001_4", /*member_group*/100, /*thumbnail_asset_path*/"\=^", /*popup_thumbnail_asset_path*/"UYN", /*scenario_script_asset_path*/"ES/9201/es_9201_04", /*live_difficulty_id*/"", /*end_at*/"", /*is_lock*/0, /*lock_text*/"", /*label*/"m.story_linkage_cell_additional_rewards", /*show_progress_line*/0, /*additional_rewards_end_at*/1615874400, /*reward_asort_name*/"m.story_linkage_cell_first_reward_name_900001_4");
INSERT INTO `m_story_linkage_cell` VALUES (/*id*/9000005, /*story_linkage_chapter_master_id*/900001, /*display_order*/5, /*type*/1, /*title*/"m.story_linkage_title_900001_5", /*summary*/"m.story_linkage_summary_900001_5", /*member_group*/100, /*thumbnail_asset_path*/"OIz", /*popup_thumbnail_asset_path*/"R8U", /*scenario_script_asset_path*/"ES/9201/es_9201_05", /*live_difficulty_id*/"", /*end_at*/"", /*is_lock*/0, /*lock_text*/"", /*label*/"m.story_linkage_cell_additional_rewards", /*show_progress_line*/0, /*additional_rewards_end_at*/1616479200, /*reward_asort_name*/"m.story_linkage_cell_first_reward_name_900001_5");
INSERT INTO `m_story_linkage_cell` VALUES (/*id*/9000006, /*story_linkage_chapter_master_id*/900001, /*display_order*/6, /*type*/1, /*title*/"m.story_linkage_title_900001_6", /*summary*/"m.story_linkage_summary_900001_6", /*member_group*/100, /*thumbnail_asset_path*/"0s{", /*popup_thumbnail_asset_path*/"SXk", /*scenario_script_asset_path*/"ES/9201/es_9201_06", /*live_difficulty_id*/"", /*end_at*/"", /*is_lock*/0, /*lock_text*/"", /*label*/"m.story_linkage_cell_additional_rewards", /*show_progress_line*/0, /*additional_rewards_end_at*/1617084000, /*reward_asort_name*/"m.story_linkage_cell_first_reward_name_900001_6");
INSERT INTO `m_story_linkage_cell` VALUES (/*id*/9000007, /*story_linkage_chapter_master_id*/900001, /*display_order*/7, /*type*/1, /*title*/"m.story_linkage_title_900001_7", /*summary*/"m.story_linkage_summary_900001_7", /*member_group*/100, /*thumbnail_asset_path*/"&a~", /*popup_thumbnail_asset_path*/"e.I", /*scenario_script_asset_path*/"ES/9201/es_9201_07", /*live_difficulty_id*/"", /*end_at*/"", /*is_lock*/0, /*lock_text*/"", /*label*/"m.story_linkage_cell_additional_rewards", /*show_progress_line*/0, /*additional_rewards_end_at*/1617688800, /*reward_asort_name*/"m.story_linkage_cell_first_reward_name_900001_7");
INSERT INTO `m_story_linkage_cell` VALUES (/*id*/9000008, /*story_linkage_chapter_master_id*/900001, /*display_order*/8, /*type*/1, /*title*/"m.story_linkage_title_900001_8", /*summary*/"m.story_linkage_summary_900001_8", /*member_group*/100, /*thumbnail_asset_path*/"l+Z", /*popup_thumbnail_asset_path*/"NgK", /*scenario_script_asset_path*/"ES/9201/es_9201_08", /*live_difficulty_id*/"", /*end_at*/"", /*is_lock*/0, /*lock_text*/"", /*label*/"m.story_linkage_cell_additional_rewards", /*show_progress_line*/0, /*additional_rewards_end_at*/1618293600, /*reward_asort_name*/"m.story_linkage_cell_first_reward_name_900001_8");
INSERT INTO `m_story_linkage_cell` VALUES (/*id*/9000009, /*story_linkage_chapter_master_id*/900001, /*display_order*/9, /*type*/1, /*title*/"m.story_linkage_title_900001_9", /*summary*/"m.story_linkage_summary_900001_9", /*member_group*/100, /*thumbnail_asset_path*/"/V_", /*popup_thumbnail_asset_path*/"xp&", /*scenario_script_asset_path*/"ES/9201/es_9201_09", /*live_difficulty_id*/"", /*end_at*/"", /*is_lock*/0, /*lock_text*/"", /*label*/"m.story_linkage_cell_additional_rewards", /*show_progress_line*/0, /*additional_rewards_end_at*/1618898400, /*reward_asort_name*/"m.story_linkage_cell_first_reward_name_900001_9");
INSERT INTO `m_story_linkage_cell` VALUES (/*id*/9000010, /*story_linkage_chapter_master_id*/900001, /*display_order*/10, /*type*/1, /*title*/"m.story_linkage_title_900001_10", /*summary*/"m.story_linkage_summary_900001_10", /*member_group*/100, /*thumbnail_asset_path*/"~x@", /*popup_thumbnail_asset_path*/"#H7", /*scenario_script_asset_path*/"ES/9201/es_9201_10", /*live_difficulty_id*/"", /*end_at*/"", /*is_lock*/0, /*lock_text*/"", /*label*/"m.story_linkage_cell_additional_rewards", /*show_progress_line*/0, /*additional_rewards_end_at*/1619503200, /*reward_asort_name*/"");
INSERT INTO `m_story_linkage_cell` VALUES (/*id*/9000011, /*story_linkage_chapter_master_id*/900001, /*display_order*/11, /*type*/1, /*title*/"m.story_linkage_title_900001_11", /*summary*/"m.story_linkage_summary_900001_11", /*member_group*/100, /*thumbnail_asset_path*/";dk", /*popup_thumbnail_asset_path*/"2ax", /*scenario_script_asset_path*/"ES/9201/es_9201_11", /*live_difficulty_id*/"", /*end_at*/"", /*is_lock*/0, /*lock_text*/"", /*label*/"m.story_linkage_cell_additional_rewards", /*show_progress_line*/0, /*additional_rewards_end_at*/1620108000, /*reward_asort_name*/"");
INSERT INTO `m_story_linkage_cell` VALUES (/*id*/9000012, /*story_linkage_chapter_master_id*/900001, /*display_order*/12, /*type*/1, /*title*/"m.story_linkage_title_900001_12", /*summary*/"m.story_linkage_summary_900001_12", /*member_group*/100, /*thumbnail_asset_path*/"XY.", /*popup_thumbnail_asset_path*/"z\"5", /*scenario_script_asset_path*/"ES/9201/es_9201_12", /*live_difficulty_id*/"", /*end_at*/"", /*is_lock*/0, /*lock_text*/"", /*label*/"m.story_linkage_cell_additional_rewards", /*show_progress_line*/0, /*additional_rewards_end_at*/1620712800, /*reward_asort_name*/"");
INSERT INTO `m_story_linkage_cell` VALUES (/*id*/9000013, /*story_linkage_chapter_master_id*/900001, /*display_order*/13, /*type*/1, /*title*/"m.story_linkage_title_900001_13", /*summary*/"m.story_linkage_summary_900001_13", /*member_group*/100, /*thumbnail_asset_path*/"g{r", /*popup_thumbnail_asset_path*/"N^l", /*scenario_script_asset_path*/"ES/9201/es_9201_13", /*live_difficulty_id*/"", /*end_at*/"", /*is_lock*/0, /*lock_text*/"", /*label*/"m.story_linkage_cell_additional_rewards", /*show_progress_line*/0, /*additional_rewards_end_at*/1621317600, /*reward_asort_name*/"");
INSERT INTO `m_story_linkage_cell` VALUES (/*id*/9000014, /*story_linkage_chapter_master_id*/900002, /*display_order*/14, /*type*/1, /*title*/"m.story_linkage_title_900002_1", /*summary*/"m.story_linkage_summary_900002_1", /*member_group*/100, /*thumbnail_asset_path*/"Q^j", /*popup_thumbnail_asset_path*/"@qD", /*scenario_script_asset_path*/"ES/9202/es_9202_01", /*live_difficulty_id*/"", /*end_at*/"", /*is_lock*/0, /*lock_text*/"", /*label*/"m.story_linkage_cell_additional_rewards", /*show_progress_line*/0, /*additional_rewards_end_at*/1649516400, /*reward_asort_name*/"m.story_linkage_cell_first_reward_name_900002_1");
INSERT INTO `m_story_linkage_cell` VALUES (/*id*/9000015, /*story_linkage_chapter_master_id*/900002, /*display_order*/15, /*type*/1, /*title*/"m.story_linkage_title_900002_2", /*summary*/"m.story_linkage_summary_900002_2", /*member_group*/100, /*thumbnail_asset_path*/"EE}", /*popup_thumbnail_asset_path*/"4D=", /*scenario_script_asset_path*/"ES/9202/es_9202_02", /*live_difficulty_id*/"", /*end_at*/"", /*is_lock*/0, /*lock_text*/"", /*label*/"m.story_linkage_cell_additional_rewards", /*show_progress_line*/0, /*additional_rewards_end_at*/1650121200, /*reward_asort_name*/"m.story_linkage_cell_first_reward_name_900002_2");
INSERT INTO `m_story_linkage_cell` VALUES (/*id*/9000016, /*story_linkage_chapter_master_id*/900002, /*display_order*/16, /*type*/1, /*title*/"m.story_linkage_title_900002_3", /*summary*/"m.story_linkage_summary_900002_3", /*member_group*/100, /*thumbnail_asset_path*/"0@^", /*popup_thumbnail_asset_path*/"9~i", /*scenario_script_asset_path*/"ES/9202/es_9202_03", /*live_difficulty_id*/"", /*end_at*/"", /*is_lock*/0, /*lock_text*/"", /*label*/"m.story_linkage_cell_additional_rewards", /*show_progress_line*/0, /*additional_rewards_end_at*/1650726000, /*reward_asort_name*/"m.story_linkage_cell_first_reward_name_900002_3");
INSERT INTO `m_story_linkage_cell` VALUES (/*id*/9000017, /*story_linkage_chapter_master_id*/900002, /*display_order*/17, /*type*/1, /*title*/"m.story_linkage_title_900002_4", /*summary*/"m.story_linkage_summary_900002_4", /*member_group*/100, /*thumbnail_asset_path*/">Hh", /*popup_thumbnail_asset_path*/"WbI", /*scenario_script_asset_path*/"ES/9202/es_9202_04", /*live_difficulty_id*/"", /*end_at*/"", /*is_lock*/0, /*lock_text*/"", /*label*/"m.story_linkage_cell_additional_rewards", /*show_progress_line*/0, /*additional_rewards_end_at*/1651330800, /*reward_asort_name*/"m.story_linkage_cell_first_reward_name_900002_4");
INSERT INTO `m_story_linkage_cell` VALUES (/*id*/9000018, /*story_linkage_chapter_master_id*/900002, /*display_order*/18, /*type*/1, /*title*/"m.story_linkage_title_900002_5", /*summary*/"m.story_linkage_summary_900002_5", /*member_group*/100, /*thumbnail_asset_path*/"9T:", /*popup_thumbnail_asset_path*/"jP>", /*scenario_script_asset_path*/"ES/9202/es_9202_05", /*live_difficulty_id*/"", /*end_at*/"", /*is_lock*/0, /*lock_text*/"", /*label*/"m.story_linkage_cell_additional_rewards", /*show_progress_line*/0, /*additional_rewards_end_at*/1651935600, /*reward_asort_name*/"m.story_linkage_cell_first_reward_name_900002_5");
INSERT INTO `m_story_linkage_cell` VALUES (/*id*/9000019, /*story_linkage_chapter_master_id*/900002, /*display_order*/19, /*type*/1, /*title*/"m.story_linkage_title_900002_6", /*summary*/"m.story_linkage_summary_900002_6", /*member_group*/100, /*thumbnail_asset_path*/"0f5", /*popup_thumbnail_asset_path*/"kqp", /*scenario_script_asset_path*/"ES/9202/es_9202_06", /*live_difficulty_id*/"", /*end_at*/"", /*is_lock*/0, /*lock_text*/"", /*label*/"m.story_linkage_cell_additional_rewards", /*show_progress_line*/0, /*additional_rewards_end_at*/1652540400, /*reward_asort_name*/"m.story_linkage_cell_first_reward_name_900002_6");
INSERT INTO `m_story_linkage_cell` VALUES (/*id*/9000020, /*story_linkage_chapter_master_id*/900002, /*display_order*/20, /*type*/1, /*title*/"m.story_linkage_title_900002_7", /*summary*/"m.story_linkage_summary_900002_7", /*member_group*/100, /*thumbnail_asset_path*/"3bM", /*popup_thumbnail_asset_path*/"XP{", /*scenario_script_asset_path*/"ES/9202/es_9202_07", /*live_difficulty_id*/"", /*end_at*/"", /*is_lock*/0, /*lock_text*/"", /*label*/"m.story_linkage_cell_additional_rewards", /*show_progress_line*/0, /*additional_rewards_end_at*/1653145200, /*reward_asort_name*/"m.story_linkage_cell_first_reward_name_900002_7");
INSERT INTO `m_story_linkage_cell` VALUES (/*id*/9000021, /*story_linkage_chapter_master_id*/900002, /*display_order*/21, /*type*/1, /*title*/"m.story_linkage_title_900002_8", /*summary*/"m.story_linkage_summary_900002_8", /*member_group*/100, /*thumbnail_asset_path*/"h[q", /*popup_thumbnail_asset_path*/"%k6", /*scenario_script_asset_path*/"ES/9202/es_9202_08", /*live_difficulty_id*/"", /*end_at*/"", /*is_lock*/0, /*lock_text*/"", /*label*/"m.story_linkage_cell_additional_rewards", /*show_progress_line*/0, /*additional_rewards_end_at*/1653750000, /*reward_asort_name*/"m.story_linkage_cell_first_reward_name_900002_8");
INSERT INTO `m_story_linkage_cell` VALUES (/*id*/9000022, /*story_linkage_chapter_master_id*/900002, /*display_order*/22, /*type*/1, /*title*/"m.story_linkage_title_900002_9", /*summary*/"m.story_linkage_summary_900002_9", /*member_group*/100, /*thumbnail_asset_path*/"BhX", /*popup_thumbnail_asset_path*/"5ow", /*scenario_script_asset_path*/"ES/9202/es_9202_09", /*live_difficulty_id*/"", /*end_at*/"", /*is_lock*/0, /*lock_text*/"", /*label*/"m.story_linkage_cell_additional_rewards", /*show_progress_line*/0, /*additional_rewards_end_at*/1654354800, /*reward_asort_name*/"m.story_linkage_cell_first_reward_name_900002_9");
INSERT INTO `m_story_linkage_cell` VALUES (/*id*/9000023, /*story_linkage_chapter_master_id*/900002, /*display_order*/23, /*type*/1, /*title*/"", /*summary*/"", /*member_group*/100, /*thumbnail_asset_path*/"", /*popup_thumbnail_asset_path*/"", /*scenario_script_asset_path*/"ES/9202/es_9202_09", /*live_difficulty_id*/"", /*end_at*/"", /*is_lock*/1, /*lock_text*/"k.story_linkage_cell_lock_text_900002_10", /*label*/"", /*show_progress_line*/0, /*additional_rewards_end_at*/"", /*reward_asort_name*/"");
