CREATE TABLE m_story_linkage_cell(
  id INTEGER NOT NULL,
  story_linkage_chapter_master_id INTEGER NOT NULL,
  display_order INTEGER NOT NULL,
  type INTEGER NOT NULL,
  title TEXT,
  summary TEXT,
  member_group INTEGER NOT NULL,
  thumbnail_asset_path TEXT,
  popup_thumbnail_asset_path TEXT,
  scenario_script_asset_path TEXT,
  live_difficulty_id INTEGER,
  end_at INTEGER,
  is_lock INTEGER NOT NULL,
  lock_text TEXT,
  label TEXT,
  show_progress_line INTEGER NOT NULL,
  additional_rewards_end_at INTEGER,
  reward_asort_name TEXT,
  PRIMARY KEY (id),
  FOREIGN KEY (story_linkage_chapter_master_id) REFERENCES m_story_linkage_chapter(id)
);
