CREATE TABLE m_tower_composition(
  tower_id INTEGER NOT NULL,
  floor_no INTEGER NOT NULL,
  name TEXT NOT NULL,
  thumbnail_asset_path TEXT,
  consume_performance INTEGER NOT NULL,
  tower_cell_type INTEGER NOT NULL,
  scenario_script_asset_path TEXT,
  live_difficulty_id INTEGER,
  target_voltage INTEGER,
  super_stage_asset_path TEXT,
  still_asset_path TEXT,
  music_id INTEGER,
  tower_clear_reward_id INTEGER,
  tower_progress_reward_id INTEGER,
  PRIMARY KEY (tower_id, floor_no)
);
INSERT INTO `m_tower_composition` VALUES (/*tower_id*/33001, /*floor_no*/1, /*name*/"m.event_tower_title_33001_000", /*thumbnail_asset_path*/"", /*consume_performance*/1, /*tower_cell_type*/2, /*scenario_script_asset_path*/"", /*live_difficulty_id*/52002001, /*target_voltage*/1090400, /*super_stage_asset_path*/"", /*still_asset_path*/"", /*music_id*/"", /*tower_clear_reward_id*/33001001, /*tower_progress_reward_id*/"");
INSERT INTO `m_tower_composition` VALUES (/*tower_id*/33001, /*floor_no*/2, /*name*/"m.event_tower_title_33001_000", /*thumbnail_asset_path*/"", /*consume_performance*/1, /*tower_cell_type*/2, /*scenario_script_asset_path*/"", /*live_difficulty_id*/52003001, /*target_voltage*/1117600, /*super_stage_asset_path*/"", /*still_asset_path*/"", /*music_id*/"", /*tower_clear_reward_id*/33001002, /*tower_progress_reward_id*/"");
INSERT INTO `m_tower_composition` VALUES (/*tower_id*/33001, /*floor_no*/3, /*name*/"m.event_tower_title_33001_000", /*thumbnail_asset_path*/"", /*consume_performance*/1, /*tower_cell_type*/2, /*scenario_script_asset_path*/"", /*live_difficulty_id*/50002001, /*target_voltage*/1654000, /*super_stage_asset_path*/"", /*still_asset_path*/"", /*music_id*/"", /*tower_clear_reward_id*/33001003, /*tower_progress_reward_id*/"");
INSERT INTO `m_tower_composition` VALUES (/*tower_id*/33001, /*floor_no*/4, /*name*/"m.event_tower_title_33001_000", /*thumbnail_asset_path*/"", /*consume_performance*/1, /*tower_cell_type*/2, /*scenario_script_asset_path*/"", /*live_difficulty_id*/50067001, /*target_voltage*/1707360, /*super_stage_asset_path*/"", /*still_asset_path*/"", /*music_id*/"", /*tower_clear_reward_id*/33001004, /*tower_progress_reward_id*/"");
INSERT INTO `m_tower_composition` VALUES (/*tower_id*/33001, /*floor_no*/5, /*name*/"m.event_tower_title_33001_000", /*thumbnail_asset_path*/"", /*consume_performance*/1, /*tower_cell_type*/2, /*scenario_script_asset_path*/"", /*live_difficulty_id*/50001001, /*target_voltage*/2246240, /*super_stage_asset_path*/"", /*still_asset_path*/"", /*music_id*/"", /*tower_clear_reward_id*/33001005, /*tower_progress_reward_id*/"");
INSERT INTO `m_tower_composition` VALUES (/*tower_id*/33001, /*floor_no*/6, /*name*/"m.event_tower_title_33001_000", /*thumbnail_asset_path*/"", /*consume_performance*/1, /*tower_cell_type*/2, /*scenario_script_asset_path*/"", /*live_difficulty_id*/51065001, /*target_voltage*/2400800, /*super_stage_asset_path*/"", /*still_asset_path*/"", /*music_id*/"", /*tower_clear_reward_id*/33001006, /*tower_progress_reward_id*/"");
INSERT INTO `m_tower_composition` VALUES (/*tower_id*/33001, /*floor_no*/7, /*name*/"m.event_tower_title_33001_000", /*thumbnail_asset_path*/"", /*consume_performance*/1, /*tower_cell_type*/2, /*scenario_script_asset_path*/"", /*live_difficulty_id*/52007001, /*target_voltage*/3387000, /*super_stage_asset_path*/"", /*still_asset_path*/"", /*music_id*/"", /*tower_clear_reward_id*/33001007, /*tower_progress_reward_id*/"");
INSERT INTO `m_tower_composition` VALUES (/*tower_id*/33001, /*floor_no*/8, /*name*/"m.event_tower_title_33001_000", /*thumbnail_asset_path*/"", /*consume_performance*/1, /*tower_cell_type*/2, /*scenario_script_asset_path*/"", /*live_difficulty_id*/52005001, /*target_voltage*/3538650, /*super_stage_asset_path*/"", /*still_asset_path*/"", /*music_id*/"", /*tower_clear_reward_id*/33001008, /*tower_progress_reward_id*/"");
INSERT INTO `m_tower_composition` VALUES (/*tower_id*/33001, /*floor_no*/9, /*name*/"m.event_tower_title_33001_000", /*thumbnail_asset_path*/"", /*consume_performance*/1, /*tower_cell_type*/2, /*scenario_script_asset_path*/"", /*live_difficulty_id*/52001001, /*target_voltage*/4630750, /*super_stage_asset_path*/"", /*still_asset_path*/"", /*music_id*/"", /*tower_clear_reward_id*/33001009, /*tower_progress_reward_id*/"");
INSERT INTO `m_tower_composition` VALUES (/*tower_id*/33001, /*floor_no*/10, /*name*/"m.event_tower_title_33001_000", /*thumbnail_asset_path*/"", /*consume_performance*/1, /*tower_cell_type*/5, /*scenario_script_asset_path*/"", /*live_difficulty_id*/50005001, /*target_voltage*/4915120, /*super_stage_asset_path*/"", /*still_asset_path*/"", /*music_id*/"", /*tower_clear_reward_id*/33001010, /*tower_progress_reward_id*/33001001);
INSERT INTO `m_tower_composition` VALUES (/*tower_id*/33001, /*floor_no*/11, /*name*/"m.event_tower_title_33001_000", /*thumbnail_asset_path*/"", /*consume_performance*/1, /*tower_cell_type*/2, /*scenario_script_asset_path*/"", /*live_difficulty_id*/50008001, /*target_voltage*/5950400, /*super_stage_asset_path*/"", /*still_asset_path*/"", /*music_id*/"", /*tower_clear_reward_id*/33001011, /*tower_progress_reward_id*/"");
INSERT INTO `m_tower_composition` VALUES (/*tower_id*/33001, /*floor_no*/12, /*name*/"m.event_tower_title_33001_000", /*thumbnail_asset_path*/"", /*consume_performance*/1, /*tower_cell_type*/2, /*scenario_script_asset_path*/"", /*live_difficulty_id*/51069001, /*target_voltage*/6001700, /*super_stage_asset_path*/"", /*still_asset_path*/"", /*music_id*/"", /*tower_clear_reward_id*/33001012, /*tower_progress_reward_id*/"");
INSERT INTO `m_tower_composition` VALUES (/*tower_id*/33001, /*floor_no*/13, /*name*/"m.event_tower_title_33001_000", /*thumbnail_asset_path*/"", /*consume_performance*/1, /*tower_cell_type*/2, /*scenario_script_asset_path*/"", /*live_difficulty_id*/52008001, /*target_voltage*/7013800, /*super_stage_asset_path*/"", /*still_asset_path*/"", /*music_id*/"", /*tower_clear_reward_id*/33001013, /*tower_progress_reward_id*/"");
INSERT INTO `m_tower_composition` VALUES (/*tower_id*/33001, /*floor_no*/14, /*name*/"m.event_tower_title_33001_000", /*thumbnail_asset_path*/"", /*consume_performance*/1, /*tower_cell_type*/2, /*scenario_script_asset_path*/"", /*live_difficulty_id*/52013001, /*target_voltage*/7224600, /*super_stage_asset_path*/"", /*still_asset_path*/"", /*music_id*/"", /*tower_clear_reward_id*/33001014, /*tower_progress_reward_id*/"");
INSERT INTO `m_tower_composition` VALUES (/*tower_id*/33001, /*floor_no*/15, /*name*/"m.event_tower_title_33001_000", /*thumbnail_asset_path*/"", /*consume_performance*/1, /*tower_cell_type*/2, /*scenario_script_asset_path*/"", /*live_difficulty_id*/52006001, /*target_voltage*/8221800, /*super_stage_asset_path*/"", /*still_asset_path*/"", /*music_id*/"", /*tower_clear_reward_id*/33001015, /*tower_progress_reward_id*/"");
INSERT INTO `m_tower_composition` VALUES (/*tower_id*/33001, /*floor_no*/16, /*name*/"m.event_tower_title_33001_000", /*thumbnail_asset_path*/"", /*consume_performance*/1, /*tower_cell_type*/2, /*scenario_script_asset_path*/"", /*live_difficulty_id*/51004001, /*target_voltage*/8664960, /*super_stage_asset_path*/"", /*still_asset_path*/"", /*music_id*/"", /*tower_clear_reward_id*/33001016, /*tower_progress_reward_id*/"");
INSERT INTO `m_tower_composition` VALUES (/*tower_id*/33001, /*floor_no*/17, /*name*/"m.event_tower_title_33001_000", /*thumbnail_asset_path*/"", /*consume_performance*/1, /*tower_cell_type*/2, /*scenario_script_asset_path*/"", /*live_difficulty_id*/50011001, /*target_voltage*/9643400, /*super_stage_asset_path*/"", /*still_asset_path*/"", /*music_id*/"", /*tower_clear_reward_id*/33001017, /*tower_progress_reward_id*/"");
INSERT INTO `m_tower_composition` VALUES (/*tower_id*/33001, /*floor_no*/18, /*name*/"m.event_tower_title_33001_000", /*thumbnail_asset_path*/"", /*consume_performance*/1, /*tower_cell_type*/2, /*scenario_script_asset_path*/"", /*live_difficulty_id*/50062001, /*target_voltage*/9854160, /*super_stage_asset_path*/"", /*still_asset_path*/"", /*music_id*/"", /*tower_clear_reward_id*/33001018, /*tower_progress_reward_id*/"");
INSERT INTO `m_tower_composition` VALUES (/*tower_id*/33001, /*floor_no*/19, /*name*/"m.event_tower_title_33001_000", /*thumbnail_asset_path*/"", /*consume_performance*/1, /*tower_cell_type*/2, /*scenario_script_asset_path*/"", /*live_difficulty_id*/51002001, /*target_voltage*/10818960, /*super_stage_asset_path*/"", /*still_asset_path*/"", /*music_id*/"", /*tower_clear_reward_id*/33001019, /*tower_progress_reward_id*/"");
INSERT INTO `m_tower_composition` VALUES (/*tower_id*/33001, /*floor_no*/20, /*name*/"m.event_tower_title_33001_000", /*thumbnail_asset_path*/"", /*consume_performance*/1, /*tower_cell_type*/5, /*scenario_script_asset_path*/"", /*live_difficulty_id*/50015001, /*target_voltage*/11147760, /*super_stage_asset_path*/"", /*still_asset_path*/"", /*music_id*/"", /*tower_clear_reward_id*/33001020, /*tower_progress_reward_id*/33001002);
INSERT INTO `m_tower_composition` VALUES (/*tower_id*/33001, /*floor_no*/21, /*name*/"m.event_tower_title_33001_000", /*thumbnail_asset_path*/"", /*consume_performance*/1, /*tower_cell_type*/2, /*scenario_script_asset_path*/"", /*live_difficulty_id*/50073001, /*target_voltage*/12605920, /*super_stage_asset_path*/"", /*still_asset_path*/"", /*music_id*/"", /*tower_clear_reward_id*/33001021, /*tower_progress_reward_id*/"");
INSERT INTO `m_tower_composition` VALUES (/*tower_id*/33001, /*floor_no*/22, /*name*/"m.event_tower_title_33001_000", /*thumbnail_asset_path*/"", /*consume_performance*/1, /*tower_cell_type*/2, /*scenario_script_asset_path*/"", /*live_difficulty_id*/52019001, /*target_voltage*/13092700, /*super_stage_asset_path*/"", /*still_asset_path*/"", /*music_id*/"", /*tower_clear_reward_id*/33001022, /*tower_progress_reward_id*/"");
INSERT INTO `m_tower_composition` VALUES (/*tower_id*/33001, /*floor_no*/23, /*name*/"m.event_tower_title_33001_000", /*thumbnail_asset_path*/"", /*consume_performance*/1, /*tower_cell_type*/2, /*scenario_script_asset_path*/"", /*live_difficulty_id*/51005001, /*target_voltage*/12691000, /*super_stage_asset_path*/"", /*still_asset_path*/"", /*music_id*/"", /*tower_clear_reward_id*/33001023, /*tower_progress_reward_id*/"");
INSERT INTO `m_tower_composition` VALUES (/*tower_id*/33001, /*floor_no*/24, /*name*/"m.event_tower_title_33001_000", /*thumbnail_asset_path*/"", /*consume_performance*/1, /*tower_cell_type*/2, /*scenario_script_asset_path*/"", /*live_difficulty_id*/50013001, /*target_voltage*/15302520, /*super_stage_asset_path*/"", /*still_asset_path*/"", /*music_id*/"", /*tower_clear_reward_id*/33001024, /*tower_progress_reward_id*/"");
INSERT INTO `m_tower_composition` VALUES (/*tower_id*/33001, /*floor_no*/25, /*name*/"m.event_tower_title_33001_000", /*thumbnail_asset_path*/"", /*consume_performance*/1, /*tower_cell_type*/2, /*scenario_script_asset_path*/"", /*live_difficulty_id*/51012001, /*target_voltage*/15686760, /*super_stage_asset_path*/"", /*still_asset_path*/"", /*music_id*/"", /*tower_clear_reward_id*/33001025, /*tower_progress_reward_id*/"");
INSERT INTO `m_tower_composition` VALUES (/*tower_id*/33001, /*floor_no*/26, /*name*/"m.event_tower_title_33001_000", /*thumbnail_asset_path*/"", /*consume_performance*/1, /*tower_cell_type*/2, /*scenario_script_asset_path*/"", /*live_difficulty_id*/51011001, /*target_voltage*/15583440, /*super_stage_asset_path*/"", /*still_asset_path*/"", /*music_id*/"", /*tower_clear_reward_id*/33001026, /*tower_progress_reward_id*/"");
INSERT INTO `m_tower_composition` VALUES (/*tower_id*/33001, /*floor_no*/27, /*name*/"m.event_tower_title_33001_000", /*thumbnail_asset_path*/"", /*consume_performance*/1, /*tower_cell_type*/2, /*scenario_script_asset_path*/"", /*live_difficulty_id*/50016001, /*target_voltage*/19183200, /*super_stage_asset_path*/"", /*still_asset_path*/"", /*music_id*/"", /*tower_clear_reward_id*/33001027, /*tower_progress_reward_id*/"");
INSERT INTO `m_tower_composition` VALUES (/*tower_id*/33001, /*floor_no*/28, /*name*/"m.event_tower_title_33001_000", /*thumbnail_asset_path*/"", /*consume_performance*/1, /*tower_cell_type*/2, /*scenario_script_asset_path*/"", /*live_difficulty_id*/52018001, /*target_voltage*/20250000, /*super_stage_asset_path*/"", /*still_asset_path*/"", /*music_id*/"", /*tower_clear_reward_id*/33001028, /*tower_progress_reward_id*/"");
INSERT INTO `m_tower_composition` VALUES (/*tower_id*/33001, /*floor_no*/29, /*name*/"m.event_tower_title_33001_000", /*thumbnail_asset_path*/"", /*consume_performance*/1, /*tower_cell_type*/2, /*scenario_script_asset_path*/"", /*live_difficulty_id*/51008001, /*target_voltage*/23808000, /*super_stage_asset_path*/"", /*still_asset_path*/"", /*music_id*/"", /*tower_clear_reward_id*/33001029, /*tower_progress_reward_id*/"");
INSERT INTO `m_tower_composition` VALUES (/*tower_id*/33001, /*floor_no*/30, /*name*/"m.event_tower_title_33001_000", /*thumbnail_asset_path*/"", /*consume_performance*/1, /*tower_cell_type*/5, /*scenario_script_asset_path*/"", /*live_difficulty_id*/52020001, /*target_voltage*/24336000, /*super_stage_asset_path*/"", /*still_asset_path*/"", /*music_id*/"", /*tower_clear_reward_id*/33001030, /*tower_progress_reward_id*/33001003);
