CREATE TABLE pack_category(
  pack_name TEXT NOT NULL,
  category INTEGER NOT NULL,
  file_size INTEGER NOT NULL,
  PRIMARY KEY (pack_name, category)
);
INSERT INTO `pack_category` VALUES (/*pack_name*/"cpmjzu", /*category*/6, /*file_size*/3049330);
INSERT INTO `pack_category` VALUES (/*pack_name*/"cpmjzu", /*category*/7, /*file_size*/7274336);
INSERT INTO `pack_category` VALUES (/*pack_name*/"4q4181", /*category*/6, /*file_size*/9618019);
INSERT INTO `pack_category` VALUES (/*pack_name*/"4q4181", /*category*/7, /*file_size*/811616);
INSERT INTO `pack_category` VALUES (/*pack_name*/"bcrcff", /*category*/6, /*file_size*/9843784);
INSERT INTO `pack_category` VALUES (/*pack_name*/"bcrcff", /*category*/7, /*file_size*/631840);
INSERT INTO `pack_category` VALUES (/*pack_name*/"8a1hd6", /*category*/6, /*file_size*/9158494);
INSERT INTO `pack_category` VALUES (/*pack_name*/"8a1hd6", /*category*/7, /*file_size*/1322592);
INSERT INTO `pack_category` VALUES (/*pack_name*/"6fwdlf", /*category*/6, /*file_size*/6538227);
INSERT INTO `pack_category` VALUES (/*pack_name*/"6fwdlf", /*category*/7, /*file_size*/3709376);
INSERT INTO `pack_category` VALUES (/*pack_name*/"qesb86", /*category*/6, /*file_size*/9191530);
INSERT INTO `pack_category` VALUES (/*pack_name*/"qesb86", /*category*/7, /*file_size*/720320);
INSERT INTO `pack_category` VALUES (/*pack_name*/"b907lw", /*category*/6, /*file_size*/9808305);
INSERT INTO `pack_category` VALUES (/*pack_name*/"b907lw", /*category*/7, /*file_size*/673984);
INSERT INTO `pack_category` VALUES (/*pack_name*/"4nkspk", /*category*/6, /*file_size*/9079687);
INSERT INTO `pack_category` VALUES (/*pack_name*/"4nkspk", /*category*/7, /*file_size*/827744);
INSERT INTO `pack_category` VALUES (/*pack_name*/"ma3xux", /*category*/6, /*file_size*/3394108);
INSERT INTO `pack_category` VALUES (/*pack_name*/"ma3xux", /*category*/7, /*file_size*/7086432);
INSERT INTO `pack_category` VALUES (/*pack_name*/"sdt13g", /*category*/6, /*file_size*/8118401);
INSERT INTO `pack_category` VALUES (/*pack_name*/"sdt13g", /*category*/7, /*file_size*/733632);
INSERT INTO `pack_category` VALUES (/*pack_name*/"rs5jxv", /*category*/6, /*file_size*/9688742);
INSERT INTO `pack_category` VALUES (/*pack_name*/"rs5jxv", /*category*/7, /*file_size*/744160);
INSERT INTO `pack_category` VALUES (/*pack_name*/"rkev5y", /*category*/6, /*file_size*/9284664);
INSERT INTO `pack_category` VALUES (/*pack_name*/"rkev5y", /*category*/7, /*file_size*/911680);
INSERT INTO `pack_category` VALUES (/*pack_name*/"iuc04a", /*category*/6, /*file_size*/5122546);
INSERT INTO `pack_category` VALUES (/*pack_name*/"iuc04a", /*category*/7, /*file_size*/5349536);
INSERT INTO `pack_category` VALUES (/*pack_name*/"kgm7lv", /*category*/6, /*file_size*/1046563);
INSERT INTO `pack_category` VALUES (/*pack_name*/"kgm7lv", /*category*/7, /*file_size*/9105056);
INSERT INTO `pack_category` VALUES (/*pack_name*/"5ahn1l", /*category*/6, /*file_size*/8860549);
INSERT INTO `pack_category` VALUES (/*pack_name*/"5ahn1l", /*category*/7, /*file_size*/1625056);
INSERT INTO `pack_category` VALUES (/*pack_name*/"13gvtj", /*category*/6, /*file_size*/9732940);
INSERT INTO `pack_category` VALUES (/*pack_name*/"13gvtj", /*category*/7, /*file_size*/728896);
INSERT INTO `pack_category` VALUES (/*pack_name*/"n54wjh", /*category*/6, /*file_size*/9752001);
INSERT INTO `pack_category` VALUES (/*pack_name*/"n54wjh", /*category*/7, /*file_size*/706304);
INSERT INTO `pack_category` VALUES (/*pack_name*/"fj8tyy", /*category*/6, /*file_size*/6356009);
INSERT INTO `pack_category` VALUES (/*pack_name*/"fj8tyy", /*category*/7, /*file_size*/4107616);
INSERT INTO `pack_category` VALUES (/*pack_name*/"0xb284", /*category*/6, /*file_size*/8423553);
INSERT INTO `pack_category` VALUES (/*pack_name*/"0xb284", /*category*/7, /*file_size*/2051936);
INSERT INTO `pack_category` VALUES (/*pack_name*/"qsrxsp", /*category*/6, /*file_size*/9642761);
INSERT INTO `pack_category` VALUES (/*pack_name*/"qsrxsp", /*category*/7, /*file_size*/838784);
INSERT INTO `pack_category` VALUES (/*pack_name*/"7arx51", /*category*/6, /*file_size*/5858296);
INSERT INTO `pack_category` VALUES (/*pack_name*/"7arx51", /*category*/7, /*file_size*/4005376);
INSERT INTO `pack_category` VALUES (/*pack_name*/"2t02qo", /*category*/6, /*file_size*/8194154);
INSERT INTO `pack_category` VALUES (/*pack_name*/"2t02qo", /*category*/7, /*file_size*/690432);
INSERT INTO `pack_category` VALUES (/*pack_name*/"2hy85l", /*category*/6, /*file_size*/8586947);
INSERT INTO `pack_category` VALUES (/*pack_name*/"2hy85l", /*category*/7, /*file_size*/1791168);
INSERT INTO `pack_category` VALUES (/*pack_name*/"8lwgkc", /*category*/6, /*file_size*/4796753);
INSERT INTO `pack_category` VALUES (/*pack_name*/"8lwgkc", /*category*/7, /*file_size*/3999296);
INSERT INTO `pack_category` VALUES (/*pack_name*/"i9losu", /*category*/6, /*file_size*/8834196);
INSERT INTO `pack_category` VALUES (/*pack_name*/"i9losu", /*category*/7, /*file_size*/1629504);
INSERT INTO `pack_category` VALUES (/*pack_name*/"dfbxhq", /*category*/6, /*file_size*/6731350);
INSERT INTO `pack_category` VALUES (/*pack_name*/"dfbxhq", /*category*/7, /*file_size*/2188096);
INSERT INTO `pack_category` VALUES (/*pack_name*/"g8nrie", /*category*/6, /*file_size*/9797077);
INSERT INTO `pack_category` VALUES (/*pack_name*/"g8nrie", /*category*/7, /*file_size*/625824);
INSERT INTO `pack_category` VALUES (/*pack_name*/"sae7uj", /*category*/6, /*file_size*/8597225);
INSERT INTO `pack_category` VALUES (/*pack_name*/"sae7uj", /*category*/7, /*file_size*/630432);
