CREATE TABLE pack_category(
  pack_name TEXT NOT NULL,
  category INTEGER NOT NULL,
  file_size INTEGER NOT NULL,
  PRIMARY KEY (pack_name, category)
);
INSERT INTO `pack_category` VALUES (/*pack_name*/"qlx5o5", /*category*/6, /*file_size*/9745978);
INSERT INTO `pack_category` VALUES (/*pack_name*/"qlx5o5", /*category*/7, /*file_size*/706304);
INSERT INTO `pack_category` VALUES (/*pack_name*/"gdewmh", /*category*/6, /*file_size*/6349449);
INSERT INTO `pack_category` VALUES (/*pack_name*/"gdewmh", /*category*/7, /*file_size*/4107616);
INSERT INTO `pack_category` VALUES (/*pack_name*/"q0jvg2", /*category*/6, /*file_size*/9782971);
INSERT INTO `pack_category` VALUES (/*pack_name*/"q0jvg2", /*category*/7, /*file_size*/673984);
INSERT INTO `pack_category` VALUES (/*pack_name*/"pj8lty", /*category*/6, /*file_size*/9252856);
INSERT INTO `pack_category` VALUES (/*pack_name*/"pj8lty", /*category*/7, /*file_size*/911680);
INSERT INTO `pack_category` VALUES (/*pack_name*/"751cmh", /*category*/6, /*file_size*/9845194);
INSERT INTO `pack_category` VALUES (/*pack_name*/"751cmh", /*category*/7, /*file_size*/631840);
INSERT INTO `pack_category` VALUES (/*pack_name*/"q6tyxf", /*category*/6, /*file_size*/8836581);
INSERT INTO `pack_category` VALUES (/*pack_name*/"q6tyxf", /*category*/7, /*file_size*/1625056);
INSERT INTO `pack_category` VALUES (/*pack_name*/"uk90ia", /*category*/6, /*file_size*/9160459);
INSERT INTO `pack_category` VALUES (/*pack_name*/"uk90ia", /*category*/7, /*file_size*/1322592);
INSERT INTO `pack_category` VALUES (/*pack_name*/"x7flbl", /*category*/6, /*file_size*/6057528);
INSERT INTO `pack_category` VALUES (/*pack_name*/"x7flbl", /*category*/7, /*file_size*/4005376);
INSERT INTO `pack_category` VALUES (/*pack_name*/"qkzxrf", /*category*/6, /*file_size*/8854277);
INSERT INTO `pack_category` VALUES (/*pack_name*/"qkzxrf", /*category*/7, /*file_size*/1629504);
INSERT INTO `pack_category` VALUES (/*pack_name*/"6prxkn", /*category*/6, /*file_size*/8603785);
INSERT INTO `pack_category` VALUES (/*pack_name*/"6prxkn", /*category*/7, /*file_size*/630432);
INSERT INTO `pack_category` VALUES (/*pack_name*/"5aktlo", /*category*/6, /*file_size*/6867671);
INSERT INTO `pack_category` VALUES (/*pack_name*/"5aktlo", /*category*/7, /*file_size*/2188096);
INSERT INTO `pack_category` VALUES (/*pack_name*/"sshnd1", /*category*/6, /*file_size*/7658470);
INSERT INTO `pack_category` VALUES (/*pack_name*/"sshnd1", /*category*/7, /*file_size*/2644032);
INSERT INTO `pack_category` VALUES (/*pack_name*/"v6v85z", /*category*/6, /*file_size*/9668416);
INSERT INTO `pack_category` VALUES (/*pack_name*/"v6v85z", /*category*/7, /*file_size*/811616);
INSERT INTO `pack_category` VALUES (/*pack_name*/"xi4yox", /*category*/6, /*file_size*/9732476);
INSERT INTO `pack_category` VALUES (/*pack_name*/"xi4yox", /*category*/7, /*file_size*/744160);
INSERT INTO `pack_category` VALUES (/*pack_name*/"y3vskr", /*category*/6, /*file_size*/4803313);
INSERT INTO `pack_category` VALUES (/*pack_name*/"y3vskr", /*category*/7, /*file_size*/3999296);
INSERT INTO `pack_category` VALUES (/*pack_name*/"bdr4x2", /*category*/6, /*file_size*/7893466);
INSERT INTO `pack_category` VALUES (/*pack_name*/"bdr4x2", /*category*/7, /*file_size*/733632);
INSERT INTO `pack_category` VALUES (/*pack_name*/"kgm7lv", /*category*/6, /*file_size*/1046563);
INSERT INTO `pack_category` VALUES (/*pack_name*/"kgm7lv", /*category*/7, /*file_size*/9105056);
INSERT INTO `pack_category` VALUES (/*pack_name*/"4rq318", /*category*/6, /*file_size*/7908068);
INSERT INTO `pack_category` VALUES (/*pack_name*/"4rq318", /*category*/7, /*file_size*/720320);
INSERT INTO `pack_category` VALUES (/*pack_name*/"09bhnu", /*category*/6, /*file_size*/9191991);
INSERT INTO `pack_category` VALUES (/*pack_name*/"09bhnu", /*category*/7, /*file_size*/827744);
INSERT INTO `pack_category` VALUES (/*pack_name*/"t8ca3e", /*category*/6, /*file_size*/3049426);
INSERT INTO `pack_category` VALUES (/*pack_name*/"t8ca3e", /*category*/7, /*file_size*/7274336);
INSERT INTO `pack_category` VALUES (/*pack_name*/"b88g5o", /*category*/6, /*file_size*/5104706);
INSERT INTO `pack_category` VALUES (/*pack_name*/"b88g5o", /*category*/7, /*file_size*/5349536);
INSERT INTO `pack_category` VALUES (/*pack_name*/"xh2clb", /*category*/6, /*file_size*/9657584);
INSERT INTO `pack_category` VALUES (/*pack_name*/"xh2clb", /*category*/7, /*file_size*/728896);
INSERT INTO `pack_category` VALUES (/*pack_name*/"oncl93", /*category*/6, /*file_size*/3447601);
INSERT INTO `pack_category` VALUES (/*pack_name*/"oncl93", /*category*/7, /*file_size*/6233568);
INSERT INTO `pack_category` VALUES (/*pack_name*/"6d75yp", /*category*/6, /*file_size*/9829217);
INSERT INTO `pack_category` VALUES (/*pack_name*/"6d75yp", /*category*/7, /*file_size*/625824);
INSERT INTO `pack_category` VALUES (/*pack_name*/"1hjdsj", /*category*/6, /*file_size*/9037117);
INSERT INTO `pack_category` VALUES (/*pack_name*/"1hjdsj", /*category*/7, /*file_size*/690432);
INSERT INTO `pack_category` VALUES (/*pack_name*/"to07fx", /*category*/6, /*file_size*/6531607);
INSERT INTO `pack_category` VALUES (/*pack_name*/"to07fx", /*category*/7, /*file_size*/3709376);
INSERT INTO `pack_category` VALUES (/*pack_name*/"2p55q3", /*category*/6, /*file_size*/8387990);
INSERT INTO `pack_category` VALUES (/*pack_name*/"2p55q3", /*category*/7, /*file_size*/2051936);
INSERT INTO `pack_category` VALUES (/*pack_name*/"2q607q", /*category*/6, /*file_size*/9626458);
INSERT INTO `pack_category` VALUES (/*pack_name*/"2q607q", /*category*/7, /*file_size*/838784);
