CREATE TABLE pack_category(
  pack_name TEXT NOT NULL,
  category INTEGER NOT NULL,
  file_size INTEGER NOT NULL,
  PRIMARY KEY (pack_name, category)
);
INSERT INTO `pack_category` VALUES (/*pack_name*/"j86h3p", /*category*/6, /*file_size*/4973729);
INSERT INTO `pack_category` VALUES (/*pack_name*/"j86h3p", /*category*/7, /*file_size*/3999296);
INSERT INTO `pack_category` VALUES (/*pack_name*/"ifd7mt", /*category*/6, /*file_size*/7830457);
INSERT INTO `pack_category` VALUES (/*pack_name*/"ifd7mt", /*category*/7, /*file_size*/733632);
INSERT INTO `pack_category` VALUES (/*pack_name*/"fyxg29", /*category*/6, /*file_size*/9131483);
INSERT INTO `pack_category` VALUES (/*pack_name*/"fyxg29", /*category*/7, /*file_size*/1322592);
INSERT INTO `pack_category` VALUES (/*pack_name*/"wvfhit", /*category*/6, /*file_size*/6268115);
INSERT INTO `pack_category` VALUES (/*pack_name*/"wvfhit", /*category*/7, /*file_size*/4107616);
INSERT INTO `pack_category` VALUES (/*pack_name*/"j0304l", /*category*/6, /*file_size*/7972821);
INSERT INTO `pack_category` VALUES (/*pack_name*/"j0304l", /*category*/7, /*file_size*/720320);
INSERT INTO `pack_category` VALUES (/*pack_name*/"x32jqe", /*category*/6, /*file_size*/9500762);
INSERT INTO `pack_category` VALUES (/*pack_name*/"x32jqe", /*category*/7, /*file_size*/911680);
INSERT INTO `pack_category` VALUES (/*pack_name*/"mzyum6", /*category*/6, /*file_size*/3109264);
INSERT INTO `pack_category` VALUES (/*pack_name*/"mzyum6", /*category*/7, /*file_size*/7274336);
INSERT INTO `pack_category` VALUES (/*pack_name*/"ui3i3g", /*category*/6, /*file_size*/9633313);
INSERT INTO `pack_category` VALUES (/*pack_name*/"ui3i3g", /*category*/7, /*file_size*/838784);
INSERT INTO `pack_category` VALUES (/*pack_name*/"6g2r36", /*category*/6, /*file_size*/5928173);
INSERT INTO `pack_category` VALUES (/*pack_name*/"6g2r36", /*category*/7, /*file_size*/4005376);
INSERT INTO `pack_category` VALUES (/*pack_name*/"xfmuoy", /*category*/6, /*file_size*/9348169);
INSERT INTO `pack_category` VALUES (/*pack_name*/"xfmuoy", /*category*/7, /*file_size*/827744);
INSERT INTO `pack_category` VALUES (/*pack_name*/"a74eej", /*category*/6, /*file_size*/8646723);
INSERT INTO `pack_category` VALUES (/*pack_name*/"a74eej", /*category*/7, /*file_size*/630432);
INSERT INTO `pack_category` VALUES (/*pack_name*/"ma3xux", /*category*/6, /*file_size*/3394108);
INSERT INTO `pack_category` VALUES (/*pack_name*/"ma3xux", /*category*/7, /*file_size*/7086432);
INSERT INTO `pack_category` VALUES (/*pack_name*/"n6ibpg", /*category*/6, /*file_size*/9627886);
INSERT INTO `pack_category` VALUES (/*pack_name*/"n6ibpg", /*category*/7, /*file_size*/728896);
INSERT INTO `pack_category` VALUES (/*pack_name*/"1kih0m", /*category*/6, /*file_size*/9669181);
INSERT INTO `pack_category` VALUES (/*pack_name*/"1kih0m", /*category*/7, /*file_size*/811616);
INSERT INTO `pack_category` VALUES (/*pack_name*/"a74p6i", /*category*/6, /*file_size*/8768773);
INSERT INTO `pack_category` VALUES (/*pack_name*/"a74p6i", /*category*/7, /*file_size*/1625056);
INSERT INTO `pack_category` VALUES (/*pack_name*/"vxipt0", /*category*/6, /*file_size*/6609599);
INSERT INTO `pack_category` VALUES (/*pack_name*/"vxipt0", /*category*/7, /*file_size*/2188096);
INSERT INTO `pack_category` VALUES (/*pack_name*/"caa3g9", /*category*/6, /*file_size*/8430549);
INSERT INTO `pack_category` VALUES (/*pack_name*/"caa3g9", /*category*/7, /*file_size*/2051936);
INSERT INTO `pack_category` VALUES (/*pack_name*/"kgm7lv", /*category*/6, /*file_size*/1046563);
INSERT INTO `pack_category` VALUES (/*pack_name*/"kgm7lv", /*category*/7, /*file_size*/9105056);
INSERT INTO `pack_category` VALUES (/*pack_name*/"6hgfwu", /*category*/6, /*file_size*/9728541);
INSERT INTO `pack_category` VALUES (/*pack_name*/"6hgfwu", /*category*/7, /*file_size*/744160);
INSERT INTO `pack_category` VALUES (/*pack_name*/"g6ap42", /*category*/6, /*file_size*/9837224);
INSERT INTO `pack_category` VALUES (/*pack_name*/"g6ap42", /*category*/7, /*file_size*/631840);
INSERT INTO `pack_category` VALUES (/*pack_name*/"7cv6sc", /*category*/6, /*file_size*/9739418);
INSERT INTO `pack_category` VALUES (/*pack_name*/"7cv6sc", /*category*/7, /*file_size*/706304);
INSERT INTO `pack_category` VALUES (/*pack_name*/"tszwzh", /*category*/6, /*file_size*/8842545);
INSERT INTO `pack_category` VALUES (/*pack_name*/"tszwzh", /*category*/7, /*file_size*/1629504);
INSERT INTO `pack_category` VALUES (/*pack_name*/"7s7y1c", /*category*/6, /*file_size*/9854341);
INSERT INTO `pack_category` VALUES (/*pack_name*/"7s7y1c", /*category*/7, /*file_size*/625824);
INSERT INTO `pack_category` VALUES (/*pack_name*/"ogqxw0", /*category*/6, /*file_size*/5136077);
INSERT INTO `pack_category` VALUES (/*pack_name*/"ogqxw0", /*category*/7, /*file_size*/5349536);
INSERT INTO `pack_category` VALUES (/*pack_name*/"zf7ph0", /*category*/6, /*file_size*/6554892);
INSERT INTO `pack_category` VALUES (/*pack_name*/"zf7ph0", /*category*/7, /*file_size*/3709376);
INSERT INTO `pack_category` VALUES (/*pack_name*/"7pcgt3", /*category*/6, /*file_size*/8072148);
INSERT INTO `pack_category` VALUES (/*pack_name*/"7pcgt3", /*category*/7, /*file_size*/690432);
INSERT INTO `pack_category` VALUES (/*pack_name*/"nvjol4", /*category*/6, /*file_size*/9802467);
INSERT INTO `pack_category` VALUES (/*pack_name*/"nvjol4", /*category*/7, /*file_size*/673984);
INSERT INTO `pack_category` VALUES (/*pack_name*/"4epjk2", /*category*/6, /*file_size*/8471648);
INSERT INTO `pack_category` VALUES (/*pack_name*/"4epjk2", /*category*/7, /*file_size*/1791168);
