CREATE TABLE skill_effect_dependency(
  asset_path TEXT NOT NULL,
  dependency TEXT NOT NULL,
  PRIMARY KEY (asset_path, dependency)
);
INSERT INTO `skill_effect_dependency` VALUES (/*asset_path*/"r4", /*dependency*/"§Vr");
INSERT INTO `skill_effect_dependency` VALUES (/*asset_path*/"nj", /*dependency*/"§Vr");
INSERT INTO `skill_effect_dependency` VALUES (/*asset_path*/"`O", /*dependency*/"§Vr");
INSERT INTO `skill_effect_dependency` VALUES (/*asset_path*/"+l", /*dependency*/"§Vr");
INSERT INTO `skill_effect_dependency` VALUES (/*asset_path*/"C/", /*dependency*/"§Vr");
INSERT INTO `skill_effect_dependency` VALUES (/*asset_path*/"~?", /*dependency*/"§Vr");
INSERT INTO `skill_effect_dependency` VALUES (/*asset_path*/"W]", /*dependency*/"§Vr");
INSERT INTO `skill_effect_dependency` VALUES (/*asset_path*/"OQ", /*dependency*/"§Vr");
INSERT INTO `skill_effect_dependency` VALUES (/*asset_path*/"D#", /*dependency*/"§Vr");
INSERT INTO `skill_effect_dependency` VALUES (/*asset_path*/"qz", /*dependency*/"§Vr");
INSERT INTO `skill_effect_dependency` VALUES (/*asset_path*/"-`", /*dependency*/"§Vr");
INSERT INTO `skill_effect_dependency` VALUES (/*asset_path*/"BO", /*dependency*/"§Vr");
INSERT INTO `skill_effect_dependency` VALUES (/*asset_path*/"Dz", /*dependency*/"§Vr");
INSERT INTO `skill_effect_dependency` VALUES (/*asset_path*/"]Z", /*dependency*/"§Vr");
INSERT INTO `skill_effect_dependency` VALUES (/*asset_path*/"+S", /*dependency*/"§Vr");
INSERT INTO `skill_effect_dependency` VALUES (/*asset_path*/":0", /*dependency*/"§Vr");
INSERT INTO `skill_effect_dependency` VALUES (/*asset_path*/"Q^", /*dependency*/"§Vr");
INSERT INTO `skill_effect_dependency` VALUES (/*asset_path*/"T*", /*dependency*/"§Vr");
INSERT INTO `skill_effect_dependency` VALUES (/*asset_path*/"\"(", /*dependency*/"§Vr");
INSERT INTO `skill_effect_dependency` VALUES (/*asset_path*/"~*", /*dependency*/"§Vr");
INSERT INTO `skill_effect_dependency` VALUES (/*asset_path*/"zx", /*dependency*/"§Vr");
INSERT INTO `skill_effect_dependency` VALUES (/*asset_path*/"~1", /*dependency*/"§Vr");
INSERT INTO `skill_effect_dependency` VALUES (/*asset_path*/"Y=", /*dependency*/"§Vr");
INSERT INTO `skill_effect_dependency` VALUES (/*asset_path*/"C#", /*dependency*/"§Vr");
INSERT INTO `skill_effect_dependency` VALUES (/*asset_path*/"nM", /*dependency*/"§Vr");
INSERT INTO `skill_effect_dependency` VALUES (/*asset_path*/"F2", /*dependency*/"§Vr");
INSERT INTO `skill_effect_dependency` VALUES (/*asset_path*/"AI", /*dependency*/"§Vr");
INSERT INTO `skill_effect_dependency` VALUES (/*asset_path*/"W(", /*dependency*/"§Vr");
INSERT INTO `skill_effect_dependency` VALUES (/*asset_path*/"^,", /*dependency*/"§Vr");
INSERT INTO `skill_effect_dependency` VALUES (/*asset_path*/"Xq", /*dependency*/"§Vr");
INSERT INTO `skill_effect_dependency` VALUES (/*asset_path*/"Uq", /*dependency*/"§Vr");
INSERT INTO `skill_effect_dependency` VALUES (/*asset_path*/"J{|", /*dependency*/"§Vr");
INSERT INTO `skill_effect_dependency` VALUES (/*asset_path*/"@5e", /*dependency*/"§Vr");
INSERT INTO `skill_effect_dependency` VALUES (/*asset_path*/"'zr", /*dependency*/"§Vr");
INSERT INTO `skill_effect_dependency` VALUES (/*asset_path*/"eJ", /*dependency*/"§Vr");
INSERT INTO `skill_effect_dependency` VALUES (/*asset_path*/"ni", /*dependency*/"§Vr");
INSERT INTO `skill_effect_dependency` VALUES (/*asset_path*/"}G", /*dependency*/"§Vr");
INSERT INTO `skill_effect_dependency` VALUES (/*asset_path*/"ZF", /*dependency*/"§Vr");
INSERT INTO `skill_effect_dependency` VALUES (/*asset_path*/"3F", /*dependency*/"§Vr");
INSERT INTO `skill_effect_dependency` VALUES (/*asset_path*/"r9", /*dependency*/"§Vr");
INSERT INTO `skill_effect_dependency` VALUES (/*asset_path*/",+", /*dependency*/"§Vr");
INSERT INTO `skill_effect_dependency` VALUES (/*asset_path*/"=8", /*dependency*/"§Vr");
INSERT INTO `skill_effect_dependency` VALUES (/*asset_path*/"0V", /*dependency*/"§Vr");
INSERT INTO `skill_effect_dependency` VALUES (/*asset_path*/"|RB", /*dependency*/"§Vr");
INSERT INTO `skill_effect_dependency` VALUES (/*asset_path*/";`)", /*dependency*/"§Vr");
INSERT INTO `skill_effect_dependency` VALUES (/*asset_path*/"zz\", /*dependency*/"§Vr");
INSERT INTO `skill_effect_dependency` VALUES (/*asset_path*/"MlF", /*dependency*/"§Vr");
